In [1]:
from IPython.display import display
import time
import hmac
import hashlib
import urllib.request
from urllib.parse import quote
import json
import pandas as pd

In [2]:
API_KEY = "9cc2976dc30ff6190b7b0485536cc483"
SECRET  = "61f2cb7a045b539c7a530af70a5be50cbff571f69e6dd8fbaa3dcc1fb8835ac8"

METHOD = "GET"
PATH   = "prediction/playerSeason"
QUERY  = {"p_no": "16287"}

def normalize_query(params: dict) -> str:
    safe = "-_.!~*'()"
    return "&".join(
        f"{quote(str(k), safe=safe)}={quote(str(params[k]), safe=safe)}"
        for k in sorted(params.keys())
    )

def make_signature(secret: str, payload: str) -> str:
    return hmac.new(
        secret.encode("utf-8"),
        payload.encode("utf-8"),
        hashlib.sha256
    ).hexdigest()

normalized = normalize_query(QUERY)
timestamp = str(int(time.time()))

payload = f"{METHOD}|{PATH}|{normalized}|{timestamp}"
signature = make_signature(SECRET, payload)

url = f"https://api.statiz.co.kr/baseballApi/{PATH}?{normalized}"

headers = {
    "X-API-KEY": API_KEY,
    "X-TIMESTAMP": timestamp,
    "X-SIGNATURE": signature,
}

req = urllib.request.Request(url, method=METHOD, headers=headers)

with urllib.request.urlopen(req, timeout=30) as resp:
    body = resp.read().decode("utf-8")

# JSON 변환
json_data = json.loads(body)

# 확인
display(json_data)

{'basic': {'list': [{'p_no': 16287,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '박준순',
    'year': '2025',
    'p_nameEN': 'PARK Jun Soon',
    'G': '91',
    'WAROff': 0.50665,
    'WARDef': -0.5615888945758343,
    'PA': '298',
    'ePA': '295',
    'AB': '282',
    'R': '34',
    'H': '80',
    '2B': '11',
    '3B': '2',
    'HR': '4',
    'TB': '107',
    'RBI': '19',
    'SB': '10',
    'CS': '2',
    'BB': '10',
    'HP': '1',
    'IB': '1',
    'SO': '56',
    'GDP': '6',
    'SH': '2',
    'SF': '3',
    'AVG': 0.284,
    'OBP': 0.307,
    'SLG': 0.379,
    'OPS': 0.686,
    'wRCplus': 82.21247100830078,
    'WAR': -0.054939042776823044,
    'p_position': 6},
   {'p_no': 16287,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '박준순',
    'year': '2026',
    'p_nameEN': 'PARK Jun Soon',
    'G': '4',
    'WAROff': 0.0546772,
    'WARDef': 0.02889319881796837,
    'PA': '12',
    'ePA': '12',
    'AB': '11',
    'R': '0',
    'H': '4',
    '2B': '0',
    '3B': '0',
    'HR': '0',
    'TB': '4',
    'RBI': '2',
    'SB': '0',
    'CS': '0',
    'BB': '0',
    'HP': '1',
    'IB': '0',
    'SO': '3',
    'GDP': '0',
    'SH': '0',
    'SF': '0',
    'AVG': 0.364,
    'OBP': 0.417,
    'SLG': 0.364,
    'OPS': 0.781,
    'wRCplus': 105.10546875,
    'WAR': 0.08357036113739014,
    'p_position': 6}]},
 'deepen': {'list': [{'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'BBK': '0.1786',
    'BABIP': '0.3378',
    'wOBA': 0.308207631111145},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'BBK': '0.0000',
    'BABIP': '0.5000',
    'wOBA': 0.3744858205318451}]},
 'fielding': {'list': [{'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '44',
    'Ass': '55',
    'E': '4',
    'p_position': 4},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '30',
    'Ass': '95',
    'E': '19',
    'p_position': 5},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '3',
    'Ass': '6',
    'E': '1',
    'p_position': 6},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '7',
    'Ass': '12',
    'E': '2',
    'p_position': 4}]},
 'result_cd': 100,
 'result_msg': '성공',
 'update_time': None}

In [7]:
# json 저장
with open("박준순_16287.json", "w", encoding="utf-8") as f:
    json.dump(json_data, f, ensure_ascii=False, indent=4)

In [2]:
# json 불러오기
with open("박준순_16287.json", "r", encoding="utf-8") as f:
    json_data = json.load(f) # 데이터명 'json_data'

In [11]:
json_data

{'basic': {'list': [{'p_no': 16287,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '박준순',
    'year': '2025',
    'p_nameEN': 'PARK Jun Soon',
    'G': '91',
    'WAROff': 0.50665,
    'WARDef': -0.5615888945758343,
    'PA': '298',
    'ePA': '295',
    'AB': '282',
    'R': '34',
    'H': '80',
    '2B': '11',
    '3B': '2',
    'HR': '4',
    'TB': '107',
    'RBI': '19',
    'SB': '10',
    'CS': '2',
    'BB': '10',
    'HP': '1',
    'IB': '1',
    'SO': '56',
    'GDP': '6',
    'SH': '2',
    'SF': '3',
    'AVG': 0.284,
    'OBP': 0.307,
    'SLG': 0.379,
    'OPS': 0.686,
    'wRCplus': 82.21247100830078,
    'WAR': -0.054939042776823044,
    'p_position': 6}]},
 'deepen': {'list': [{'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'BBK': '0.1786',
    'BABIP': '0.3378',
    'wOBA': 0.308207631111145}]},
 'fielding': {'list': [{'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '44',
    'Ass': '55',
    'E': '4',
    'p_position': 4},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '30',
    'Ass': '95',
    'E': '19',
    'p_position': 5},
   {'p_no': 16287,
    't_code': '6002',
    'p_name': '박준순',
    'PO': '3',
    'Ass': '6',
    'E': '1',
    'p_position': 6}]},
 'result_cd': 100,
 'result_msg': '성공',
 'update_time': None}

In [5]:
json_data.keys()

dict_keys(['basic', 'deepen', 'fielding', 'result_cd', 'result_msg', 'update_time'])

In [3]:
# DataFrame 변환
basic_df = pd.DataFrame(json_data["basic"]["list"])
deepen_df = pd.DataFrame(json_data["deepen"]["list"])

display(basic_df.head())
display(deepen_df.head())

print(basic_df.columns)

,p_no,leagueType,t_code,p_name,year,p_nameEN,G,WAROff,WARDef,PA,...,GDP,SH,SF,AVG,OBP,SLG,OPS,wRCplus,WAR,p_position
0,16287,10100,6002,박준순,2025,PARK Jun Soon,91,0.506650,-0.561589,298,...,6,2,3,0.284,0.307,0.379,0.686,82.212471,-0.054939,6
1,16287,10100,6002,박준순,2026,PARK Jun Soon,4,0.054677,0.028893,12,...,0,0,0,0.364,0.417,0.364,0.781,105.105469,0.083570,6

    p_no t_code p_name     BBK   BABIP      wOBA
0  16287   6002    박준순  0.1786  0.3378  0.308208
1  16287   6002    박준순  0.0000  0.5000  0.374486

Index(['p_no', 'leagueType', 't_code', 'p_name', 'year', 'p_nameEN', 'G',
       'WAROff', 'WARDef', 'PA', 'ePA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'TB',
       'RBI', 'SB', 'CS', 'BB', 'HP', 'IB', 'SO', 'GDP', 'SH', 'SF', 'AVG',
       'OBP', 'SLG', 'OPS', 'wRCplus', 'WAR', 'p_position'],
      dtype='object')

In [4]:
deepen_df["year"] = basic_df["year"].values

display(basic_df)
display(deepen_df)

,p_no,leagueType,t_code,p_name,year,p_nameEN,G,WAROff,WARDef,PA,...,GDP,SH,SF,AVG,OBP,SLG,OPS,wRCplus,WAR,p_position
0,16287,10100,6002,박준순,2025,PARK Jun Soon,91,0.506650,-0.561589,298,...,6,2,3,0.284,0.307,0.379,0.686,82.212471,-0.054939,6
1,16287,10100,6002,박준순,2026,PARK Jun Soon,4,0.054677,0.028893,12,...,0,0,0,0.364,0.417,0.364,0.781,105.105469,0.083570,6

    p_no t_code p_name     BBK   BABIP      wOBA  year
0  16287   6002    박준순  0.1786  0.3378  0.308208  2025
1  16287   6002    박준순  0.0000  0.5000  0.374486  2026