In [1]:
from IPython.display import display
import time
import hmac
import hashlib
import urllib.request
from urllib.parse import quote
import json
import pandas as pd

In [2]:
API_KEY = "9cc2976dc30ff6190b7b0485536cc483"
SECRET  = "61f2cb7a045b539c7a530af70a5be50cbff571f69e6dd8fbaa3dcc1fb8835ac8"

METHOD = "GET"
PATH   = "prediction/playerSeason"
QUERY  = {"p_no": "10195"}

def normalize_query(params: dict) -> str:
    safe = "-_.!~*'()"
    return "&".join(
        f"{quote(str(k), safe=safe)}={quote(str(params[k]), safe=safe)}"
        for k in sorted(params.keys())
    )

def make_signature(secret: str, payload: str) -> str:
    return hmac.new(
        secret.encode("utf-8"),
        payload.encode("utf-8"),
        hashlib.sha256
    ).hexdigest()

normalized = normalize_query(QUERY)
timestamp = str(int(time.time()))

payload = f"{METHOD}|{PATH}|{normalized}|{timestamp}"
signature = make_signature(SECRET, payload)

url = f"https://api.statiz.co.kr/baseballApi/{PATH}?{normalized}"

headers = {
    "X-API-KEY": API_KEY,
    "X-TIMESTAMP": timestamp,
    "X-SIGNATURE": signature,
}

req = urllib.request.Request(url, method=METHOD, headers=headers)

with urllib.request.urlopen(req, timeout=30) as resp:
    body = resp.read().decode("utf-8")

# JSON 변환
json_data = json.loads(body)

# 확인
display(json_data)

{'basic': {'list': [{'p_no': 10195,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '정수빈',
    'year': '2023',
    'p_nameEN': 'Soo-Bin Jeong',
    'G': '137',
    'WAROff': 3.93437,
    'WARDef': 0.46867990493774414,
    'PA': '583',
    'ePA': '571',
    'AB': '498',
    'R': '75',
    'H': '143',
    '2B': '14',
    '3B': '11',
    'HR': '2',
    'TB': '185',
    'RBI': '33',
    'SB': '39',
    'CS': '8',
    'BB': '64',
    'HP': '7',
    'IB': '1',
    'SO': '63',
    'GDP': '2',
    'SH': '12',
    'SF': '2',
    'AVG': 0.287,
    'OBP': 0.375,
    'SLG': 0.371,
    'OPS': 0.746,
    'wRCplus': 121.20800018310547,
    'WAR': 4.403049945831299,
    'p_position': 8},
   {'p_no': 10195,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '정수빈',
    'year': '2024',
    'p_nameEN': 'Soo-Bin Jeong',
    'G': '136',
    'WAROff': 2.61836,
    'WARDef': 0.4507601261138916,
    'PA': '608',
    'ePA': '598',
    'AB': '510',
    'R': '95',
    'H': '145',
    '2B': '21',
    '3B': '3',
    'HR': '4',
    'TB': '184',
    'RBI': '47',
    'SB': '52',
    'CS': '13',
    'BB': '71',
    'HP': '9',
    'IB': '1',
    'SO': '72',
    'GDP': '8',
    'SH': '10',
    'SF': '8',
    'AVG': 0.284,
    'OBP': 0.376,
    'SLG': 0.361,
    'OPS': 0.737,
    'wRCplus': 100.18299865722656,
    'WAR': 3.069124698638916,
    'p_position': 8},
   {'p_no': 10195,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '정수빈',
    'year': '2025',
    'p_nameEN': 'Soo-Bin Jeong',
    'G': '132',
    'WAROff': 2.31874,
    'WARDef': 0.5106277465820312,
    'PA': '546',
    'ePA': '537',
    'AB': '462',
    'R': '89',
    'H': '119',
    '2B': '16',
    '3B': '4',
    'HR': '6',
    'TB': '161',
    'RBI': '38',
    'SB': '26',
    'CS': '13',
    'BB': '61',
    'HP': '11',
    'IB': '2',
    'SO': '57',
    'GDP': '7',
    'SH': '8',
    'SF': '4',
    'AVG': 0.258,
    'OBP': 0.355,
    'SLG': 0.348,
    'OPS': 0.703,
    'wRCplus': 104.75100708007812,
    'WAR': 2.8293652534484863,
    'p_position': 8},
   {'p_no': 10195,
    'leagueType': 10100,
    't_code': '6002',
    'p_name': '정수빈',
    'year': '2026',
    'p_nameEN': 'Soo-Bin Jeong',
    'G': '4',
    'WAROff': 0.0831482,
    'WARDef': -0.027658812701702118,
    'PA': '18',
    'ePA': '18',
    'AB': '15',
    'R': '1',
    'H': '4',
    '2B': '0',
    '3B': '0',
    'HR': '0',
    'TB': '4',
    'RBI': '2',
    'SB': '3',
    'CS': '0',
    'BB': '3',
    'HP': '0',
    'IB': '0',
    'SO': '3',
    'GDP': '0',
    'SH': '0',
    'SF': '0',
    'AVG': 0.267,
    'OBP': 0.389,
    'SLG': 0.267,
    'OPS': 0.656,
    'wRCplus': 71.22319030761719,
    'WAR': 0.05548936128616333,
    'p_position': 8}]},
 'deepen': {'list': [{'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'BBK': '1.0159',
    'BABIP': '0.3241',
    'wOBA': 0.361068993806839},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'BBK': '0.9861',
    'BABIP': '0.3190',
    'wOBA': 0.3476249873638153},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'BBK': '1.0702',
    'BABIP': '0.2804',
    'wOBA': 0.33873340487480164},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'BBK': '1.0000',
    'BABIP': '0.3333',
    'wOBA': 0.33508574962615967}]},
 'fielding': {'list': [{'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'PO': '318',
    'Ass': '8',
    'E': '0',
    'p_position': 8},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'PO': '313',
    'Ass': '5',
    'E': '1',
    'p_position': 8},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'PO': '262',
    'Ass': '4',
    'E': '3',
    'p_position': 8},
   {'p_no': 10195,
    't_code': '6002',
    'p_name': '정수빈',
    'PO': '8',
    'Ass': '0',
    'E': '0',
    'p_position': 8}]},
 'result_cd': 100,
 'result_msg': '성공',
 'update_time': None}

In [10]:
# json 저장
with open("정수빈_10195.json", "w", encoding="utf-8") as f:
    json.dump(json_data, f, ensure_ascii=False, indent=4)

In [3]:
# json 불러오기
with open("정수빈_10195.json", "r", encoding="utf-8") as f:
    json_data = json.load(f) # 데이터명 'json_data'

In [4]:
# DataFrame 변환
basic_df = pd.DataFrame(json_data["basic"]["list"])
deepen_df = pd.DataFrame(json_data["deepen"]["list"])
fielding_df = pd.DataFrame(json_data["fielding"]["list"])

display(basic_df.head())
display(deepen_df.head())
display(fielding_df.head())

print(basic_df.columns)

,p_no,leagueType,t_code,p_name,year,p_nameEN,G,WAROff,WARDef,PA,...,GDP,SH,SF,AVG,OBP,SLG,OPS,wRCplus,WAR,p_position
0,10195,10100,6002,정수빈,2023,Soo-Bin Jeong,137,3.93437,0.468680,583,...,2,12,2,0.287,0.375,0.371,0.746,121.208000,4.403050,8
1,10195,10100,6002,정수빈,2024,Soo-Bin Jeong,136,2.61836,0.450760,608,...,8,10,8,0.284,0.376,0.361,0.737,100.182999,3.069125,8
2,10195,10100,6002,정수빈,2025,Soo-Bin Jeong,132,2.31874,0.510628,546,...,7,8,4,0.258,0.355,0.348,0.703,104.751007,2.829365,8

    p_no t_code p_name     BBK   BABIP      wOBA
0  10195   6002    정수빈  1.0159  0.3241  0.361069
1  10195   6002    정수빈  0.9861  0.3190  0.347625
2  10195   6002    정수빈  1.0702  0.2804  0.338733

    p_no t_code p_name   PO Ass  E  p_position
0  10195   6002    정수빈  318   8  0           8
1  10195   6002    정수빈  313   5  1           8
2  10195   6002    정수빈  262   4  3           8

Index(['p_no', 'leagueType', 't_code', 'p_name', 'year', 'p_nameEN', 'G',
       'WAROff', 'WARDef', 'PA', 'ePA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'TB',
       'RBI', 'SB', 'CS', 'BB', 'HP', 'IB', 'SO', 'GDP', 'SH', 'SF', 'AVG',
       'OBP', 'SLG', 'OPS', 'wRCplus', 'WAR', 'p_position'],
      dtype='object')

In [7]:
deepen_df["year"] = basic_df["year"].values

display(basic_df)
display(deepen_df)

,p_no,leagueType,t_code,p_name,year,p_nameEN,G,WAROff,WARDef,PA,...,GDP,SH,SF,AVG,OBP,SLG,OPS,wRCplus,WAR,p_position
0,10195,10100,6002,정수빈,2023,Soo-Bin Jeong,137,3.93437,0.468680,583,...,2,12,2,0.287,0.375,0.371,0.746,121.208000,4.403050,8
1,10195,10100,6002,정수빈,2024,Soo-Bin Jeong,136,2.61836,0.450760,608,...,8,10,8,0.284,0.376,0.361,0.737,100.182999,3.069125,8
2,10195,10100,6002,정수빈,2025,Soo-Bin Jeong,132,2.31874,0.510628,546,...,7,8,4,0.258,0.355,0.348,0.703,104.751007,2.829365,8

    p_no t_code p_name     BBK   BABIP      wOBA  year
0  10195   6002    정수빈  1.0159  0.3241  0.361069  2023
1  10195   6002    정수빈  0.9861  0.3190  0.347625  2024
2  10195   6002    정수빈  1.0702  0.2804  0.338733  2025

In [7]:
merged_df = basic_df.merge(
    deepen_df[["year", "BBK", "BABIP", "wOBA"]],
    on="year",
    how="left"
).merge(
    fielding_df[["year", "PO", "Ass", "E"]],
    on="year",
    how="left"
)

display(merged_df.head())
print(merged_df.columns)

,p_no,leagueType,t_code,p_name,year,p_nameEN,G,WAROff,WARDef,PA,...,OPS,wRCplus,WAR,p_position,BBK,BABIP,wOBA,PO,Ass,E
0,10195,10100,6002,정수빈,2023,Soo-Bin Jeong,137,3.93437,0.468680,583,...,0.746,121.208000,4.403050,8,1.0159,0.3241,0.361069,318,8,0
1,10195,10100,6002,정수빈,2024,Soo-Bin Jeong,136,2.61836,0.450760,608,...,0.737,100.182999,3.069125,8,0.9861,0.3190,0.347625,313,5,1
2,10195,10100,6002,정수빈,2025,Soo-Bin Jeong,132,2.31874,0.510628,546,...,0.703,104.751007,2.829365,8,1.0702,0.2804,0.338733,262,4,3

Index(['p_no', 'leagueType', 't_code', 'p_name', 'year', 'p_nameEN', 'G',
       'WAROff', 'WARDef', 'PA', 'ePA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'TB',
       'RBI', 'SB', 'CS', 'BB', 'HP', 'IB', 'SO', 'GDP', 'SH', 'SF', 'AVG',
       'OBP', 'SLG', 'OPS', 'wRCplus', 'WAR', 'p_position', 'BBK', 'BABIP',
       'wOBA', 'PO', 'Ass', 'E'],
      dtype='object')

In [8]:
merged_df.dtypes

p_no            int64
leagueType      int64
t_code         object
p_name         object
year           object
p_nameEN       object
G              object
WAROff        float64
WARDef        float64
PA             object
ePA            object
AB             object
R              object
H              object
2B             object
3B             object
HR             object
TB             object
RBI            object
SB             object
CS             object
BB             object
HP             object
IB             object
SO             object
GDP            object
SH             object
SF             object
AVG           float64
OBP           float64
SLG           float64
OPS           float64
wRCplus       float64
WAR           float64
p_position      int64
BBK            object
BABIP          object
wOBA          float64
PO             object
Ass            object
E              object
dtype: object

In [9]:
str_cols = ["p_name","p_nameEN","t_code"]
int_cols = [
"p_no","leagueType","year","p_position",
"G","PA","ePA","AB","R","H","2B","3B","HR","TB", # PA(타석), ePA(유효타석), AB(타수), TB(루타수)
"RBI","SB","CS","BB","HP","IB","SO","GDP","SH","SF", # RBI(타점), SB(도루성공), CS(도루자), IB(고의사구), GDP(병살타), SH(희생번트), SF(희생플라이)
"PO","Ass","E" # PO(자살), Ass(보살), E(실책)
]
float_cols = [
"WAROff","WARDef", # 타격WAR, 수비WAR
"AVG","OBP","SLG","OPS","wRCplus","WAR", # OBP(출루율), SLG(장타율)
"BBK","BABIP","wOBA" # BBK(4구/삼진)
]

merged_df[str_cols] = merged_df[str_cols].astype("object")

for c in int_cols:
    if c in merged_df.columns:
        merged_df[c] = pd.to_numeric(merged_df[c], errors="coerce").astype("int64")

for c in float_cols:
    if c in merged_df.columns:
        merged_df[c] = pd.to_numeric(merged_df[c], errors="coerce")

In [1]:
display(merged_df)

merged_df.dtypes

NameError: name 'merged_df' is not defined

In [35]:
merged_df.to_csv(
    "playerSeason_10195.csv",
    index=False,
    encoding="utf-8-sig"
)

In [14]:
merged_df.shape

(3, 41)

In [22]:
print(merged_df[["PO", "Ass"]])

    PO  Ass
0  318    8
1  313    5
2  262    4