In [36]:
from IPython.display import display
import time
import hmac
import hashlib
import urllib.request
from urllib.parse import quote
import json
import pandas as pd
import numpy as np
from typing import Dict, Any, List, Optional

API_KEY = "9cc2976dc30ff6190b7b0485536cc483"
SECRET  = "61f2cb7a045b539c7a530af70a5be50cbff571f69e6dd8fbaa3dcc1fb8835ac8"

BASE_URL = "https://api.statiz.co.kr/baseballApi"

### 공통함수

In [3]:
# 공통 함수

def normalize_query(params: dict) -> str:
    safe = "-_.!~*'()"
    return "&".join(
        f"{quote(str(k), safe=safe)}={quote(str(params[k]), safe=safe)}"
        for k in sorted(params.keys())
        if params[k] is not None
    )


def make_signature(secret: str, payload: str) -> str:
    return hmac.new(
        secret.encode("utf-8"),
        payload.encode("utf-8"),
        hashlib.sha256
    ).hexdigest()


def api_get(path: str, query: Dict[str, Any], timeout: int = 30, verbose: bool = False) -> Dict[str, Any]:
    method = "GET"
    normalized = normalize_query(query)
    timestamp = str(int(time.time()))
    payload = f"{method}|{path}|{normalized}|{timestamp}"
    signature = make_signature(SECRET, payload)

    url = f"{BASE_URL}/{path}"
    if normalized:
        url = f"{url}?{normalized}"

    headers = {
        "X-API-KEY": API_KEY,
        "X-TIMESTAMP": timestamp,
        "X-SIGNATURE": signature,
    }

    if verbose:
        print("URL:", url)
        print("Payload:", payload)

    req = urllib.request.Request(url, method=method, headers=headers)

    with urllib.request.urlopen(req, timeout=timeout) as resp:
        body = resp.read().decode("utf-8")

    data = json.loads(body)

    # 공통 실패 처리
    if isinstance(data, dict):
        result_cd = str(data.get("result_cd", ""))
        if result_cd and result_cd != "100":
            raise ValueError(f"API 실패: result_cd={result_cd}, result_msg={data.get('result_msg')}")

    return data


def numeric_key_rows(obj: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    응답이 {'0': {...}, '1': {...}, 'result_cd': '100', ...} 형태일 때
    숫자 key row들만 추출.
    """
    rows = []
    for k, v in obj.items():
        if str(k).isdigit() and isinstance(v, dict):
            rows.append(v)
    return rows


def to_df_from_list_or_numeric_dict(obj: Dict[str, Any], list_key: Optional[str] = None) -> pd.DataFrame:
    """
    응답이
    1) {'list': [...]} 형태이거나
    2) {'0': {...}, '1': {...}} 형태일 때
    DataFrame으로 변환.
    """
    if list_key is not None and list_key in obj and isinstance(obj[list_key], list):
        return pd.DataFrame(obj[list_key])

    rows = numeric_key_rows(obj)
    if rows:
        return pd.DataFrame(rows)

    return pd.DataFrame()

### 경기 일정 수집

In [4]:
def fetch_game_schedule(year: int, month: int, day: int, verbose: bool = False) -> pd.DataFrame:
    path = "prediction/gameSchedule"
    query = {
        "year": year,
        "month": month,
        "day": day
    }

    data = api_get(path, query, verbose=verbose)

    rows = []

    # 1) top-level에서 메타 키(result_cd 등) 제외하고, list value인 항목 수집
    if isinstance(data, dict):
        meta_keys = {"result_cd", "result_msg", "update_time"}
        for k, v in data.items():
            if k not in meta_keys and isinstance(v, list):
                rows.extend(v)

    df = pd.DataFrame(rows)

    if df.empty:
        if verbose:
            print("[fetch_game_schedule] rows is empty")
            print("raw keys:", list(data.keys()) if isinstance(data, dict) else type(data))
        return df

    # 컬럼명 표준화
    rename_map = {
        "s_no": "game_id",
        "gameDate": "game_date",
        "awayTeam": "away_team_code",
        "homeTeam": "home_team_code",
        "s_code": "stadium_code",
        "awaySP": "away_sp_id",
        "homeSP": "home_sp_id",
        "awaySPName": "away_sp_name",
        "homeSPName": "home_sp_name",
        "awayScore": "away_score",
        "homeScore": "home_score",
        "state": "game_state",
        "hm": "game_time",
    }
    df = df.rename(columns=rename_map)

    # game_date가 unix timestamp(초) 형태이므로 변환
    if "game_date" in df.columns:
        df["game_date"] = pd.to_datetime(df["game_date"], unit="s", errors="coerce")
    else:
        df["game_date"] = pd.to_datetime(f"{year}-{month:02d}-{day:02d}", errors="coerce")

    # season 보강
    if "season" not in df.columns:
        if "year" in df.columns:
            df["season"] = pd.to_numeric(df["year"], errors="coerce")
        else:
            df["season"] = year

    # home_win 생성
    if {"home_score", "away_score"}.issubset(df.columns):
        df["home_win"] = (
            pd.to_numeric(df["home_score"], errors="coerce") >
            pd.to_numeric(df["away_score"], errors="coerce")
        ).astype("Int64")
    else:
        df["home_win"] = pd.NA

    keep_cols = [
        "game_id",
        "game_date",
        "season",
        "home_team_code",
        "away_team_code",
        "stadium_code",
        "home_sp_id",
        "away_sp_id",
        "home_sp_name",
        "away_sp_name",
        "home_score",
        "away_score",
        "home_win",
        "game_state",
        "game_time",
        "weather",
        "temperature",
        "humidity",
        "windDirection",
        "windSpeed",
        "rainprobability",
    ]
    keep_cols = [c for c in keep_cols if c in df.columns]

    return df[keep_cols].copy()

In [5]:
# 여러날 일괄 수집

def collect_games(date_list: List[str], sleep_sec: float = 0.2) -> pd.DataFrame:
    all_dfs = []

    for dt in date_list:
        y, m, d = map(int, dt.split("-"))
        try:
            df = fetch_game_schedule(y, m, d)
            if not df.empty:
                all_dfs.append(df)
            print(f"[games] {dt}: {len(df)} rows")
        except Exception as e:
            print(f"[games] {dt}: ERROR -> {e}")
        time.sleep(sleep_sec)

    if all_dfs:
        out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()
    else:
        out = pd.DataFrame()

    return out

### 경기 라인업 수집

In [6]:
def fetch_game_lineup(game_id: str, verbose: bool = False) -> pd.DataFrame:
    path = "prediction/gameLineup"
    query = {"s_no": str(game_id)}

    data = api_get(path, query, verbose=verbose)

    rows = []

    # 메타 키 제외, 팀코드 key 아래 list 수집
    if isinstance(data, dict):
        meta_keys = {"result_cd", "result_msg", "update_time"}
        for k, v in data.items():
            if k not in meta_keys and isinstance(v, list):
                rows.extend(v)

    df = pd.DataFrame(rows)

    if df.empty:
        if verbose:
            print("[fetch_game_lineup] rows is empty")
            if isinstance(data, dict):
                print("raw keys:", list(data.keys()))
        return df

    # 컬럼 표준화
    rename_map = {
        "s_no": "game_id",
        "p_no": "player_id",
        "t_code": "team_code",
        "p_name": "player_name",
        "starting": "is_starting",
        "battingOrder": "batting_order",
        "p_throw": "throws",
        "p_bat": "bats",
        "p_backNumber": "back_number",
    }
    df = df.rename(columns=rename_map)

    # game_id 문자열 통일
    df["game_id"] = df["game_id"].astype(str)

    # starting: Y/N -> 1/0
    if "is_starting" in df.columns:
        df["is_starting"] = df["is_starting"].map({"Y": 1, "N": 0}).fillna(df["is_starting"])

    # batting_order 숫자화
    if "batting_order" in df.columns:
        df["batting_order"] = pd.to_numeric(df["batting_order"], errors="coerce")

    # 선발투수 flag
    # position==1 이 투수라고 가정
    if "position" in df.columns:
        pos = pd.to_numeric(df["position"], errors="coerce")
        if "is_starting" in df.columns:
            st = pd.to_numeric(df["is_starting"], errors="coerce")
            df["is_starting_pitcher"] = ((pos == 1) & (st == 1)).astype(int)
        else:
            df["is_starting_pitcher"] = (pos == 1).astype(int)
    else:
        df["is_starting_pitcher"] = pd.NA

    # 중복 제거
    subset_cols = [c for c in ["game_id", "team_code", "player_id"] if c in df.columns]
    if subset_cols:
        df = df.drop_duplicates(subset=subset_cols).reset_index(drop=True)

    keep_cols = [
        "game_id",
        "game_date",
        "team_code",
        "player_id",
        "player_name",
        "is_starting",
        "lineupState",
        "batting_order",
        "position",
        "is_starting_pitcher",
        "throws",
        "bats",
        "back_number",
    ]
    keep_cols = [c for c in keep_cols if c in df.columns]

    return df[keep_cols].copy()

In [7]:
# games에서 lineup일괄 수집

def collect_lineups(games_df: pd.DataFrame, sleep_sec: float = 0.2) -> pd.DataFrame:
    if "game_id" not in games_df.columns:
        raise ValueError("games_df에 game_id 컬럼이 필요합니다.")

    all_dfs = []

    for game_id in games_df["game_id"].astype(str).tolist():
        try:
            df = fetch_game_lineup(game_id)

            if not df.empty:
                game_date = games_df.loc[
                    games_df["game_id"].astype(str) == game_id, "game_date"
                ]
                if not game_date.empty:
                    df["game_date"] = game_date.iloc[0]

                all_dfs.append(df)

            print(f"[lineup] {game_id}: {len(df)} rows")

        except Exception as e:
            print(f"[lineup] {game_id}: ERROR -> {e}")

        time.sleep(sleep_sec)  # 429 방지

    if all_dfs:
        out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()
    else:
        out = pd.DataFrame()

    return out

### playerSeason: 타자/투수 시즌 누적 시트 수집

In [8]:
def convert_ip_baseball_to_decimal(x): ## 얘 다시
    """
    예: 66.1 -> 66.333..., 66.2 -> 66.666...
    문자열/숫자 모두 대응
    """
    if pd.isna(x):
        return pd.NA
    try:
        s = str(x)
        if "." not in s:
            return float(s)
        whole, frac = s.split(".")
        whole = int(whole)
        frac = int(frac)
        if frac == 0:
            return float(whole)
        elif frac == 1:
            return whole + 1/3
        elif frac == 2:
            return whole + 2/3
        else:
            return float(s)
    except Exception:
        return pd.NA


def fetch_player_season(player_id: str, verbose: bool = False) -> Dict[str, pd.DataFrame]:
    path = "prediction/playerSeason"
    query = {"p_no": str(player_id)}

    data = api_get(path, query, verbose=verbose)

    basic_df   = pd.DataFrame(data.get("basic", {}).get("list", []))
    deepen_df  = pd.DataFrame(data.get("deepen", {}).get("list", []))
    field_df   = pd.DataFrame(data.get("fielding", {}).get("list", []))

    # year 기준 merge
    if not basic_df.empty and not deepen_df.empty and "year" in basic_df.columns and "year" in deepen_df.columns:
        merged = basic_df.merge(deepen_df, on="year", how="left", suffixes=("", "_deepen"))
    else:
        merged = basic_df.copy()

    if not merged.empty:
        merged["player_id"] = str(player_id)

    # 투수/타자 구분: 보통 p_position == 1 이면 투수
    is_pitcher = False
    if not merged.empty and "p_position" in merged.columns:
        vals = merged["p_position"].dropna().astype(str).unique().tolist()
        is_pitcher = ("1" in vals)

    # 공통 컬럼명 표준화
    if "t_code" in merged.columns:
        merged = merged.rename(columns={"t_code": "team_code"})

    # IP 변환
    if "IP" in merged.columns:
        merged["IP_decimal"] = merged["IP"].apply(convert_ip_baseball_to_decimal)

    if is_pitcher:
        keep_cols = [
            "player_id", "year", "team_code",
            "GS", "IP", "IP_decimal", "ERA", "FIP", "WHIP",
            "K9", "BB9", "HR9", "KBB", "QS"
        ]
        keep_cols = [c for c in keep_cols if c in merged.columns]
        pitcher_df = merged[keep_cols].copy()
        hitter_df = pd.DataFrame()
    else:
        keep_cols = [
            "player_id", "year", "team_code",
            "PA", "AB", "H", "HR", "RBI", "BB", "SO",
            "AVG", "OBP", "SLG", "OPS", "wOBA", "wRCplus", "BBK"
        ]
        keep_cols = [c for c in keep_cols if c in merged.columns]
        hitter_df = merged[keep_cols].copy()
        pitcher_df = pd.DataFrame()

    return {
        "hitter": hitter_df,
        "pitcher": pitcher_df,
        "raw_basic": basic_df,
        "raw_deepen": deepen_df,
        "raw_fielding": field_df
    }

In [9]:
# 일괄수집

def collect_player_season(player_ids: List[str], snapshot_date: str, sleep_sec: float = 0.2):
    hitter_list = []
    pitcher_list = []

    for pid in map(str, player_ids):
        try:
            res = fetch_player_season(pid)
            if not res["hitter"].empty:
                df = res["hitter"].copy()
                df["snapshot_date"] = snapshot_date
                hitter_list.append(df)
            if not res["pitcher"].empty:
                df = res["pitcher"].copy()
                df["snapshot_date"] = snapshot_date
                pitcher_list.append(df)
            print(f"[playerSeason] {pid}: OK")
        except Exception as e:
            print(f"[playerSeason] {pid}: ERROR -> {e}")
        time.sleep(sleep_sec)

    hitter_out = pd.concat(hitter_list, ignore_index=True) if hitter_list else pd.DataFrame()
    pitcher_out = pd.concat(pitcher_list, ignore_index=True) if pitcher_list else pd.DataFrame()

    return hitter_out, pitcher_out

### playerRoster: 날짜별 팀 로스터 수집 (player_id list 확보용)

In [10]:
def fetch_player_roster(date: str, code: str, t_code: str, verbose: bool = False) -> pd.DataFrame:
    path = "prediction/playerRoster"
    query = {
        "date": date,
        "code": str(code),
        "t_code": str(t_code)
    }

    data = api_get(path, query, verbose=verbose)
    df = to_df_from_list_or_numeric_dict(data, list_key="list")

    if df.empty:
        return df

    rename_map = {
        "name": "player_name",
        "p_no": "player_id",
        "t_code": "team_code",
        "pj_date": "join_date"
    }
    df = df.rename(columns=rename_map)
    df["snapshot_date"] = date

    keep_cols = ["snapshot_date", "team_code", "player_id", "player_name", "join_date"]
    keep_cols = [c for c in keep_cols if c in df.columns]

    return df[keep_cols].copy()

In [11]:
# 일괄 수집

def collect_rosters(date: str, team_codes: List[str], code: str = "1", sleep_sec: float = 0.2) -> pd.DataFrame:
    all_dfs = []

    for t_code in map(str, team_codes):
        try:
            df = fetch_player_roster(date=date, code=code, t_code=t_code)
            if not df.empty:
                all_dfs.append(df)
            print(f"[roster] {date} team={t_code}: {len(df)} rows")
        except Exception as e:
            print(f"[roster] {date} team={t_code}: ERROR -> {e}")
        time.sleep(sleep_sec)

    if all_dfs:
        out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()
    else:
        out = pd.DataFrame()

    return out

### playerDay: 타자/투수 일별 시트 수집 
- query 부분의 파라미터 명을 문서에 맞게 바꿀 것
> 보류

In [12]:
def fetch_player_day(player_id: str,
                     start_date: Optional[str] = None,
                     end_date: Optional[str] = None,
                     year: Optional[int] = None,
                     verbose: bool = False) -> Dict[str, pd.DataFrame]:
    """
    주의:
    playerDay의 실제 query 파라미터명(start_date/end_date 또는 year 등)은
    문서에 맞게 수정 필요할 수 있음.
    """
    path = "prediction/playerDay"

    query = {"p_no": str(player_id)}
    if start_date is not None:
        query["start_date"] = start_date
        query["startDate"] = start_date
    if end_date is not None:
        query["end_date"] = end_date
        query["endDate"] = end_date
    if year is not None:
        query["year"] = int(year)

    data = api_get(path, query, verbose=verbose)

    # 구조 방어적으로 파싱
    df = to_df_from_list_or_numeric_dict(data, list_key="list")
    if df.empty and "data" in data and isinstance(data["data"], dict):
        df = to_df_from_list_or_numeric_dict(data["data"], list_key="list")

    if df.empty:
        return {"hitter": pd.DataFrame(), "pitcher": pd.DataFrame(), "raw": df}

    # 공통 표준화
    rename_map = {
        "s_no": "game_id",
        "p_no": "player_id",
        "t_code": "team_code",
        "battingOrder": "batting_order"
    }
    df = df.rename(columns=rename_map)

    if "gameDate" in df.columns:
        df = df.rename(columns={"gameDate": "game_date"})

    if "game_date" in df.columns:
        raw_game_date = df["game_date"].astype(str).str.strip()
        numeric_game_date = pd.to_numeric(raw_game_date, errors="coerce")
        parsed_game_date = pd.Series(pd.NaT, index=df.index, dtype="datetime64[ns]")

        numeric_mask = numeric_game_date.notna()
        if numeric_mask.any():
            unit = "ms" if numeric_game_date[numeric_mask].ge(10**12).any() else "s"
            parsed_game_date.loc[numeric_mask] = pd.to_datetime(
                numeric_game_date.loc[numeric_mask], unit=unit, errors="coerce"
            )

        text_mask = ~numeric_mask & raw_game_date.ne("") & raw_game_date.ne("nan")
        if text_mask.any():
            text_values = raw_game_date.loc[text_mask]
            parsed_text = pd.to_datetime(text_values, format="%Y-%m-%d %H:%M:%S", errors="coerce")
            parsed_text = parsed_text.fillna(
                pd.to_datetime(text_values, format="%Y-%m-%d", errors="coerce")
            )
            parsed_game_date.loc[text_mask] = parsed_text

        df["game_date"] = parsed_game_date

    # hitter / pitcher 분리
    # GS/IP/NP 존재하면 투수 가능성 높음
    pitcher_cols_signal = {"GS", "IP", "NP", "ERA", "WHIP"}
    hitter_cols_signal  = {"PA", "OBP", "SLG", "OPS", "batting_order"}

    pitcher_df = pd.DataFrame()
    hitter_df = pd.DataFrame()

    if len(pitcher_cols_signal.intersection(df.columns)) >= 2:
        keep_cols = [
            "game_id", "game_date", "player_id", "team_code",
            "GS", "IP", "ER", "H", "HR", "BB", "SO", "NP", "ERA", "WHIP"
        ]
        keep_cols = [c for c in keep_cols if c in df.columns]
        pitcher_df = df[keep_cols].copy()
        for col in ["IP", "ER", "H", "HR", "BB", "SO", "NP", "ERA", "WHIP"]:
            if col in pitcher_df.columns:
                pitcher_df[col] = pd.to_numeric(pitcher_df[col], errors="coerce")

        if "IP" in pitcher_df.columns:
            valid_pitching_row = pitcher_df["IP"].notna()
            if "NP" in pitcher_df.columns:
                valid_pitching_row = valid_pitching_row | pitcher_df["NP"].ge(10)
            if "ERA" in pitcher_df.columns:
                valid_pitching_row = valid_pitching_row | pitcher_df["ERA"].notna()
            if "WHIP" in pitcher_df.columns:
                valid_pitching_row = valid_pitching_row | pitcher_df["WHIP"].notna()
            pitcher_df = pitcher_df.loc[valid_pitching_row].copy()

    if len(hitter_cols_signal.intersection(df.columns)) >= 2:
        keep_cols = [
            "game_id", "game_date", "player_id", "team_code",
            "PA", "AB", "H", "HR", "RBI", "BB", "SO", "OBP", "SLG", "OPS", "batting_order"
        ]
        keep_cols = [c for c in keep_cols if c in df.columns]
        hitter_df = df[keep_cols].copy()

    return {"hitter": hitter_df, "pitcher": pitcher_df, "raw": df}

In [13]:
# 일괄 수집

def collect_player_day(player_ids: List[str],
                       start_date: Optional[str] = None,
                       end_date: Optional[str] = None,
                       year: Optional[int] = None,
                       sleep_sec: float = 0.2):
    hitter_list = []
    pitcher_list = []

    for pid in map(str, player_ids):
        try:
            res = fetch_player_day(
                player_id=pid,
                start_date=start_date,
                end_date=end_date,
                year=year
            )
            if not res["hitter"].empty:
                hitter_list.append(res["hitter"])
            if not res["pitcher"].empty:
                pitcher_list.append(res["pitcher"])
            print(f"[playerDay] {pid}: OK")
        except Exception as e:
            print(f"[playerDay] {pid}: ERROR -> {e}")
        time.sleep(sleep_sec)

    hitter_out = pd.concat(hitter_list, ignore_index=True) if hitter_list else pd.DataFrame()
    pitcher_out = pd.concat(pitcher_list, ignore_index=True) if pitcher_list else pd.DataFrame()

    return hitter_out, pitcher_out

## 실행

In [14]:
# 예시
date_list = ["2023-04-11", "2023-04-22", "2023-04-23"]
games_df = collect_games(date_list)
display(games_df.head())

[games] 2023-04-11: 5 rows
[games] 2023-04-22: 5 rows
[games] 2023-04-23: 5 rows

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,4,1,3,18:30:00,10400,13.0,84,21100,3.1,None
1,20230042,2023-04-11 09:30:00,2023,1001,9002,7003,14113,14581,원태인,오원석,...,5,0,3,18:30:00,10400,20.2,59,20900,1.8,None
2,20230043,2023-04-11 09:30:00,2023,2002,7002,6001,10058,14619,양현종,남지민,...,5,0,3,18:30:00,10400,16.9,92,21300,2.2,None
3,20230044,2023-04-11 09:30:00,2023,3001,5002,8001,15011,15486,반즈,박명근,...,5,1,3,18:30:00,10500,18.4,70,20900,3.4,None
4,20230045,2023-04-11 09:30:00,2023,11001,12001,8005,13085,15542,신민혁,슐서,...,0,1,3,18:30:00,10400,18.3,76,21500,1.0,None

In [15]:
games_df_clean = games_df[
    (games_df["game_state"] == 3) &
    (games_df["home_score"].notna()) &
    (games_df["away_score"].notna())
].copy()

In [16]:
test_lineup = fetch_game_lineup("20230092", verbose=True)
display(test_lineup)
print(test_lineup.shape)

URL: https://api.statiz.co.kr/baseballApi/prediction/gameLineup?s_no=20230092
Payload: GET|prediction/gameLineup|s_no=20230092|1775625956

,game_id,team_code,player_id,player_name,is_starting,lineupState,batting_order,position,is_starting_pitcher,throws,bats,back_number
0,20230092,9002,14888,추신수,1,Y,1.0,10,0,3,2,17
1,20230092,9002,14587,최지훈,1,Y,2.0,8,0,1,2,54
2,20230092,9002,10106,최정,1,Y,3.0,5,0,1,1,14
3,20230092,9002,15530,에레디아,1,Y,4.0,7,0,3,1,27
4,20230092,9002,10815,한유섬,1,Y,5.0,9,0,1,2,35
5,20230092,9002,10182,최주환,1,N,6.0,4,0,1,2,53
6,20230092,9002,10636,김성현,1,Y,7.0,6,0,1,1,6
7,20230092,9002,14699,전의산,1,N,8.0,3,0,1,2,56
8,20230092,9002,10707,김민식,1,Y,9.0,2,0,1,2,24
9,20230092,9002,15528,맥카티,1,N,NaN,1,1,3,2,33
10,20230092,10001,12905,김혜성,1,Y,1.0,4,0,1,2,3
11,20230092,10001,12516,이형종,1,Y,2.0,9,0,1,1,36
12,20230092,10001,12906,이정후,1,Y,3.0,8,0,1,2,51
13,20230092,10001,14742,러셀,1,Y,4.0,6,0,1,1,27
14,20230092,10001,14785,김휘집,1,Y,5.0,5,0,1,1,33
15,20230092,10001,11244,김태진,1,Y,6.0,10,0,1,2,2
16,20230092,10001,11422,전병우,1,Y,7.0,3,0,1,1,13
17,20230092,10001,10035,이용규,1,Y,8.0,7,0,3,2,15
18,20230092,10001,10312,이지영,1,N,9.0,2,0,1,1,56
19,20230092,10001,11379,최원태,1,N,NaN,1,1,1,1,20

(20, 12)

In [17]:
lineup_df = collect_lineups(games_df_clean)
display(lineup_df.head())
print(lineup_df.shape)

[lineup] 20230041: 20 rows
[lineup] 20230042: 20 rows
[lineup] 20230043: 20 rows
[lineup] 20230044: 20 rows
[lineup] 20230045: 20 rows
[lineup] 20230091: 20 rows
[lineup] 20230092: 20 rows
[lineup] 20230093: 20 rows
[lineup] 20230094: 20 rows
[lineup] 20230095: 20 rows
[lineup] 20230096: 20 rows
[lineup] 20230097: 20 rows
[lineup] 20230098: 20 rows
[lineup] 20230099: 20 rows
[lineup] 20230100: 20 rows

,game_id,team_code,player_id,player_name,is_starting,lineupState,batting_order,position,is_starting_pitcher,throws,bats,back_number,game_date
0,20230041,6002,10195,정수빈,1,Y,1.0,8,0,3,2,31,2023-04-11 09:30:00
1,20230041,6002,10184,허경민,1,Y,2.0,5,0,1,1,13,2023-04-11 09:30:00
2,20230041,6002,11213,양석환,1,Y,3.0,3,0,1,1,53,2023-04-11 09:30:00
3,20230041,6002,10643,김재환,1,Y,4.0,7,0,1,2,32,2023-04-11 09:30:00
4,20230041,6002,10165,양의지,1,Y,5.0,2,0,1,1,25,2023-04-11 09:30:00

(300, 13)

In [18]:
display(lineup_df.head(20))

,game_id,team_code,player_id,player_name,is_starting,lineupState,batting_order,position,is_starting_pitcher,throws,bats,back_number,game_date
0,20230041,6002,10195,정수빈,1,Y,1.0,8,0,3,2,31,2023-04-11 09:30:00
1,20230041,6002,10184,허경민,1,Y,2.0,5,0,1,1,13,2023-04-11 09:30:00
2,20230041,6002,11213,양석환,1,Y,3.0,3,0,1,1,53,2023-04-11 09:30:00
3,20230041,6002,10643,김재환,1,Y,4.0,7,0,1,2,32,2023-04-11 09:30:00
4,20230041,6002,10165,양의지,1,Y,5.0,2,0,1,1,25,2023-04-11 09:30:00
5,20230041,6002,15539,로하스,1,Y,6.0,10,0,1,2,11,2023-04-11 09:30:00
6,20230041,6002,11087,강승호,1,Y,7.0,4,0,1,1,23,2023-04-11 09:30:00
7,20230041,6002,14172,송승환,1,N,8.0,9,0,1,1,8,2023-04-11 09:30:00
8,20230041,6002,12894,이유찬,1,Y,9.0,6,0,1,1,7,2023-04-11 09:30:00
9,20230041,6002,14770,최승용,1,N,NaN,1,1,3,2,64,2023-04-11 09:30:00
10,20230041,10001,12905,김혜성,1,Y,1.0,4,0,1,2,3,2023-04-11 09:30:00
11,20230041,10001,12516,이형종,1,Y,2.0,9,0,1,1,36,2023-04-11 09:30:00
12,20230041,10001,12906,이정후,1,Y,3.0,8,0,1,2,51,2023-04-11 09:30:00
13,20230041,10001,14742,러셀,1,Y,4.0,6,0,1,1,27,2023-04-11 09:30:00
14,20230041,10001,14580,박주홍,1,Y,5.0,7,0,3,2,57,2023-04-11 09:30:00
15,20230041,10001,15068,박찬혁,1,Y,6.0,10,0,1,1,48,2023-04-11 09:30:00
16,20230041,10001,10312,이지영,1,N,7.0,2,0,1,1,56,2023-04-11 09:30:00
17,20230041,10001,14785,김휘집,1,Y,8.0,5,0,1,1,33,2023-04-11 09:30:00
18,20230041,10001,13096,김수환,1,N,9.0,3,0,1,1,31,2023-04-11 09:30:00
19,20230041,10001,11379,최원태,1,N,NaN,1,1,1,1,20,2023-04-11 09:30:00

In [19]:
team_codes = ["1001", "2002", "3001", "5002", "6002", "7002", "9002", "10001", "11001", "12001"]
#               삼성,    KIA,   롯데,     LG,   두산,   한화,    SSG,    키움,      NC,     KT

In [20]:
roster_df = collect_rosters(date="2023-04-22", team_codes=team_codes, code="1") # date는 변동할 것. 
display(roster_df.head())

[roster] 2023-04-22 team=1001: 28 rows
[roster] 2023-04-22 team=2002: 28 rows
[roster] 2023-04-22 team=3001: 28 rows
[roster] 2023-04-22 team=5002: 28 rows
[roster] 2023-04-22 team=6002: 28 rows
[roster] 2023-04-22 team=7002: 28 rows
[roster] 2023-04-22 team=9002: 28 rows
[roster] 2023-04-22 team=10001: 28 rows
[roster] 2023-04-22 team=11001: 28 rows
[roster] 2023-04-22 team=12001: 28 rows

  snapshot_date  team_code  player_id player_name   join_date
0    2023-04-22       1001      10892         구자욱  2023-04-01
1    2023-04-22       1001      10363         백정현  2023-04-05
2    2023-04-22       1001      11404         장필준  2023-04-21
3    2023-04-22       1001      12530         최충연  2023-04-01
4    2023-04-22       1001      10685         김대우  2023-04-01

In [ ]:
'''
player_ids = roster_df["player_id"].astype(str).unique().tolist()
season_hit_df, season_pit_df = collect_player_season(player_ids, snapshot_date="2023-04-22")

target_year = pd.to_datetime(date_list[0]).year

season_hit_df["year"] = pd.to_numeric(season_hit_df["year"], errors="coerce")
season_pit_df["year"] = pd.to_numeric(season_pit_df["year"], errors="coerce")

season_hit_df = season_hit_df[season_hit_df["year"] == target_year].copy()
season_pit_df = season_pit_df[season_pit_df["year"] == target_year].copy()

display(season_hit_df.head())
display(season_pit_df.head())'''

[playerSeason] 10892: OK
[playerSeason] 10363: OK
[playerSeason] 11404: OK
[playerSeason] 12530: OK
[playerSeason] 10685: OK
[playerSeason] 10180: OK
[playerSeason] 10523: OK
[playerSeason] 12885: OK
[playerSeason] 10527: OK
[playerSeason] 10232: OK
[playerSeason] 13240: OK
[playerSeason] 13244: OK
[playerSeason] 11200: OK
[playerSeason] 14113: OK
[playerSeason] 10367: OK
[playerSeason] 12562: OK
[playerSeason] 14617: OK
[playerSeason] 14618: OK
[playerSeason] 11169: OK
[playerSeason] 12936: OK
[playerSeason] 10400: OK
[playerSeason] 14757: OK
[playerSeason] 14798: OK
[playerSeason] 14799: OK
[playerSeason] 12988: OK
[playerSeason] 15034: OK
[playerSeason] 14117: OK
[playerSeason] 13164: OK
[playerSeason] 10058: OK
[playerSeason] 10008: OK
[playerSeason] 11119: OK
[playerSeason] 10909: OK
[playerSeason] 10344: OK
[playerSeason] 11233: OK
[playerSeason] 12537: OK
[playerSeason] 11261: OK
[playerSeason] 11303: OK
[playerSeason] 11306: OK
[playerSeason] 11099: OK
[playerSeason] 11298: OK
[playerSeason] 12540: OK
[playerSeason] 14608: OK
[playerSeason] 10894: OK
[playerSeason] 14788: OK
[playerSeason] 12914: OK
[playerSeason] 14996: OK
[playerSeason] 10659: OK
[playerSeason] 15057: OK
[playerSeason] 14176: OK
[playerSeason] 14124: OK
[playerSeason] 12567: OK
[playerSeason] 10706: OK
[playerSeason] 15432: OK
[playerSeason] 15533: OK
[playerSeason] 15534: OK
[playerSeason] 14612: OK
[playerSeason] 10266: OK
[playerSeason] 10253: OK
[playerSeason] 11310: OK
[playerSeason] 10825: OK
[playerSeason] 12930: OK
[playerSeason] 11291: OK
[playerSeason] 13145: OK
[playerSeason] 13154: OK
[playerSeason] 14160: OK
[playerSeason] 14624: OK
[playerSeason] 10014: OK
[playerSeason] 14642: OK
[playerSeason] 13169: OK
[playerSeason] 14792: OK
[playerSeason] 10804: OK
[playerSeason] 14114: OK
[playerSeason] 15011: OK
[playerSeason] 15152: OK
[playerSeason] 14627: OK
[playerSeason] 10516: OK
[playerSeason] 10427: OK
[playerSeason] 10885: OK
[playerSeason] 10753: OK
[playerSeason] 11165: OK
[playerSeason] 10863: OK
[playerSeason] 14571: OK
[playerSeason] 15253: OK
[playerSeason] 15441: OK
[playerSeason] 10475: OK
[playerSeason] 10075: OK
[playerSeason] 10749: OK
[playerSeason] 10652: OK
[playerSeason] 10480: OK
[playerSeason] 12907: OK
[playerSeason] 13056: OK
[playerSeason] 10187: OK
[playerSeason] 13109: OK
[playerSeason] 12546: OK
[playerSeason] 13934: OK
[playerSeason] 14134: OK
[playerSeason] 14136: OK
[playerSeason] 14137: OK
[playerSeason] 10238: OK
[playerSeason] 14588: OK
[playerSeason] 14669: OK
[playerSeason] 13112: OK
[playerSeason] 12549: OK
[playerSeason] 14780: OK
[playerSeason] 11094: OK
[playerSeason] 10855: OK
[playerSeason] 11190: OK
[playerSeason] 11166: OK
[playerSeason] 15003: OK
[playerSeason] 15486: OK
[playerSeason] 15532: OK
[playerSeason] 10387: OK
[playerSeason] 10174: OK
[playerSeason] 10643: OK
[playerSeason] 10184: OK
[playerSeason] 12850: OK
[playerSeason] 12852: OK
[playerSeason] 11492: OK
[playerSeason] 13061: OK
[playerSeason] 13071: OK
[playerSeason] 11097: OK
[playerSeason] 10195: OK
[playerSeason] 12678: OK
[playerSeason] 10696: OK
[playerSeason] 12847: OK
[playerSeason] 12524: OK
[playerSeason] 11087: OK
[playerSeason] 14769: OK
[playerSeason] 14770: OK
[playerSeason] 14771: OK
[playerSeason] 11213: OK
[playerSeason] 15099: OK
[playerSeason] 15127: OK
[playerSeason] 14172: OK
[playerSeason] 14738: OK
[playerSeason] 12894: OK
[playerSeason] 12605: OK
[playerSeason] 10165: OK
[playerSeason] 13941: OK
[playerSeason] 15539: OK
[playerSeason] 11410: OK
[playerSeason] 11411: OK
[playerSeason] 10610: OK
[playerSeason] 10156: OK
[playerSeason] 10170: OK
[playerSeason] 13137: OK
[playerSeason] 14125: OK
[playerSeason] 11110: OK
[playerSeason] 12587: OK
[playerSeason] 14619: OK
[playerSeason] 14621: OK
[playerSeason] 14704: OK
[playerSeason] 14708: OK
[playerSeason] 11268: OK
[playerSeason] 14808: OK
[playerSeason] 12585: OK
[playerSeason] 13138: OK
[playerSeason] 15141: OK
[playerSeason] 12589: OK
[playerSeason] 15146: OK
[playerSeason] 12871: OK
[playerSeason] 10812: OK
[playerSeason] 10557: OK
[playerSeason] 10609: OK
[playerSeason] 11215: OK
[playerSeason] 15421: OK
[playerSeason] 15422: OK
[playerSeason] 15541: OK
[playerSeason] 10108: OK
[playerSeason] 10126: OK
[playerSeason] 10636: OK
[playerSeason] 10784: OK
[playerSeason] 10106: OK
[playerSeason] 10815: OK
[playerSeason] 10783: OK
[playerSeason] 12922: OK
[playerSeason] 13126: OK
[playerSeason] 13195: OK
[playerSeason] 11236: OK
[playerSeason] 14581: OK
[playerSeason] 14587: OK
[playerSeason] 14699: OK
[playerSeason] 10249: OK
[playerSeason] 10182: OK
[playerSeason] 14806: OK
[playerSeason] 14888: OK
[playerSeason] 10203: OK
[playerSeason] 15024: OK
[playerSeason] 14151: OK
[playerSeason] 10707: OK
[playerSeason] 15461: OK
[playerSeason] 15462: OK
[playerSeason] 15528: OK

KeyboardInterrupt:

In [ ]:
'''cols = ["ERA", "FIP", "WHIP", "KBB"]
season_pit_df[cols] = season_pit_df[cols].replace([np.inf, -np.inf], np.nan).fillna(99.99)
season_pit_df.isna().sum()
'''

player_id        0
year             0
team_code        0
GS               0
IP               0
IP_decimal       0
ERA              0
FIP              0
WHIP             0
K9               0
BB9              0
HR9              0
KBB              0
QS               0
snapshot_date    0
dtype: int64

In [ ]:
# 보류
'''
day_hit_df, day_pit_df = collect_player_day(
    player_ids=player_ids,
    start_date="2025-03-28",
    end_date="2025-08-31"
)
display(day_hit_df.head())
display(day_pit_df.head())
'''

[playerDay] 10475: OK
[playerDay] 10749: OK
[playerDay] 10652: OK
[playerDay] 12697: OK
[playerDay] 13009: OK
[playerDay] 13056: OK
[playerDay] 10187: OK
[playerDay] 13109: OK
[playerDay] 12546: OK
[playerDay] 14137: OK
[playerDay] 14143: OK
[playerDay] 13112: OK
[playerDay] 12908: OK
[playerDay] 11190: OK
[playerDay] 11166: OK
[playerDay] 13102: OK
[playerDay] 13103: OK
[playerDay] 15486: OK
[playerDay] 15532: OK
[playerDay] 10387: OK
[playerDay] 15084: OK
[playerDay] 14140: OK
[playerDay] 14783: OK
[playerDay] 15081: OK
[playerDay] 11164: OK
[playerDay] 14846: OK
[playerDay] 16274: OK
[playerDay] 16286: OK
[playerDay] 11137: OK
[playerDay] 11172: OK
[playerDay] 13080: OK
[playerDay] 13081: OK
[playerDay] 13085: OK
[playerDay] 12897: OK
[playerDay] 11355: OK
[playerDay] 12560: OK
[playerDay] 14764: OK
[playerDay] 14765: OK
[playerDay] 10217: OK
[playerDay] 14220: OK
[playerDay] 10261: OK
[playerDay] 13082: OK
[playerDay] 14156: OK
[playerDay] 10891: OK
[playerDay] 14661: OK
[playerDay] 13261: OK
[playerDay] 15451: OK
[playerDay] 11248: OK
[playerDay] 12565: OK
[playerDay] 14659: OK
[playerDay] 14597: OK
[playerDay] 14747: OK
[playerDay] 16057: OK
[playerDay] 14785: OK
[playerDay] 16349: OK
[playerDay] 16350: OK

,game_id,game_date,player_id,team_code,PA,AB,H,HR,RBI,BB,SO,OBP,SLG,OPS,batting_order
0,20260001.0,NaT,10475,5002,3,3,0,0,0,0,0,0.00,0.00,0.00,7
1,20260006.0,NaT,10475,5002,4,4,1,0,1,0,1,0.25,0.50,0.75,7
2,20260011.0,NaT,10475,5002,4,4,0,0,1,0,0,0.00,0.00,0.00,7
3,20260016.0,NaT,10475,5002,5,4,0,0,1,0,1,0.20,0.00,0.20,6
4,NaN,NaT,10749,5002,NaN,4,1,0,NaN,1,2,0.40,0.25,0.65,NaN

,game_id,game_date,player_id,team_code,GS,H,HR,BB,SO,NP,IP,ER,ERA,WHIP
0,20260001.0,NaT,10475,5002,1,0,0,0,0,7,NaN,NaN,NaN,NaN
1,20260006.0,NaT,10475,5002,1,1,0,0,1,19,NaN,NaN,NaN,NaN
2,20260011.0,NaT,10475,5002,1,0,0,0,0,9,NaN,NaN,NaN,NaN
3,20260016.0,NaT,10475,5002,1,0,0,0,1,14,NaN,NaN,NaN,NaN
4,NaN,NaT,10749,5002,0,1,0,1,2,20,1.0,0.0,0.0,2.0

### 경기단위 df 생성

In [ ]:
# 전처리 보조 함수

def prepare_games_for_modeling(games_df: pd.DataFrame) -> pd.DataFrame:
    df = games_df.copy()

    # 정상 경기만
    df = df[
        (df["game_state"] == 3) &
        (df["home_score"].notna()) &
        (df["away_score"].notna())
    ].copy()

    df["game_id"] = df["game_id"].astype(str)
    df["home_team_code"] = df["home_team_code"].astype(str)
    df["away_team_code"] = df["away_team_code"].astype(str)

    if "home_win" not in df.columns:
        df["home_win"] = (df["home_score"] > df["away_score"]).astype(int)

    return df


def prepare_lineup(lineup_df: pd.DataFrame) -> pd.DataFrame:
    df = lineup_df.copy()

    df["game_id"] = df["game_id"].astype(str)
    df["team_code"] = df["team_code"].astype(str)
    df["player_id"] = df["player_id"].astype(str)

    if "batting_order" in df.columns:
        df["batting_order"] = pd.to_numeric(df["batting_order"], errors="coerce")

    if "position" in df.columns:
        df["position"] = pd.to_numeric(df["position"], errors="coerce")

    if "is_starting" in df.columns:
        df["is_starting"] = pd.to_numeric(df["is_starting"], errors="coerce")

    if "is_starting_pitcher" in df.columns:
        df["is_starting_pitcher"] = pd.to_numeric(df["is_starting_pitcher"], errors="coerce")

    return df


def prepare_season_hitters(season_hit_df: pd.DataFrame) -> pd.DataFrame:
    df = season_hit_df.copy()

    df["player_id"] = df["player_id"].astype(str)
    df["team_code"] = df["team_code"].astype(str)

    num_cols = ["PA", "OBP", "SLG", "OPS", "wOBA", "wRCplus", "BBK"]
    for c in num_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    return df


def prepare_season_pitchers(season_pit_df: pd.DataFrame) -> pd.DataFrame:
    df = season_pit_df.copy()

    df["player_id"] = df["player_id"].astype(str)
    df["team_code"] = df["team_code"].astype(str)

    num_cols = ["GS", "IP", "IP_decimal", "ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB", "QS"]
    for c in num_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    return df

In [ ]:
# 타자 feature 생성

def build_hitter_team_features(lineup_df: pd.DataFrame, season_hit_df: pd.DataFrame) -> pd.DataFrame:
    # 타자만: 선발투수 제외, 타순 있는 선수 중심
    hitters = lineup_df.copy()
    if "is_starting_pitcher" in hitters.columns:
        hitters = hitters[hitters["is_starting_pitcher"] != 1].copy()

    hitters = hitters.merge(
        season_hit_df,
        on=["player_id", "team_code"],
        how="left",
        suffixes=("", "_season")
    )

    # lineup 전체 평균
    def weighted_mean(x, value_col, weight_col="PA"):
        tmp = x[[value_col, weight_col]].dropna()
        if tmp.empty:
            return np.nan
        w = tmp[weight_col]
        v = tmp[value_col]
        if w.sum() == 0:
            return v.mean()
        return np.average(v, weights=w)

    team_rows = []

    for (game_id, team_code), g in hitters.groupby(["game_id", "team_code"]):
        row = {
            "game_id": game_id,
            "team_code": team_code,
            "lineup_n_hitters": len(g),
        }

        for stat in ["OPS", "OBP", "SLG"]:
            if stat in g.columns:
                row[f"lineup_{stat}"] = weighted_mean(g, stat, "PA")

        # top5
        if "batting_order" in g.columns:
            top5 = g[g["batting_order"].between(1, 5, inclusive="both")].copy()
        else:
            top5 = pd.DataFrame()

        row["top5_n"] = len(top5)

        for stat in ["OPS", "OBP"]:
            if not top5.empty and stat in top5.columns:
                row[f"top5_{stat}"] = weighted_mean(top5, stat, "PA")
            else:
                row[f"top5_{stat}"] = np.nan

        team_rows.append(row)

    return pd.DataFrame(team_rows)

In [ ]:
# 선발투수 feature 생성

def build_starting_pitcher_features(lineup_df: pd.DataFrame, season_pit_df: pd.DataFrame) -> pd.DataFrame:
    sp = lineup_df.copy()

    # 선발투수만
    if "is_starting_pitcher" in sp.columns:
        sp = sp[sp["is_starting_pitcher"] == 1].copy()
    else:
        sp = sp[sp["position"] == 1].copy()

    sp = sp.merge(
        season_pit_df,
        on=["player_id", "team_code"],
        how="left",
        suffixes=("", "_season")
    )

    keep_cols = [
        "game_id", "team_code", "player_id", "player_name",
        "ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB", "QS", "GS"
    ]
    keep_cols = [c for c in keep_cols if c in sp.columns]
    sp = sp[keep_cols].copy()

    rename_map = {
        "player_id": "sp_player_id",
        "player_name": "sp_player_name",
        "ERA": "sp_ERA",
        "FIP": "sp_FIP",
        "WHIP": "sp_WHIP",
        "K9": "sp_K9",
        "BB9": "sp_BB9",
        "HR9": "sp_HR9",
        "KBB": "sp_KBB",
        "QS": "sp_QS",
        "GS": "sp_GS",
    }
    sp = sp.rename(columns=rename_map)

    return sp

In [ ]:
def make_game_level_dataset(
    games_df_clean: pd.DataFrame,
    hitter_team_features: pd.DataFrame = None,
    sp_features: pd.DataFrame = None
) -> pd.DataFrame:
    """
    수정:
    - hitter_team_features가 None/empty여도 동작
    - 선발투수 feature만으로도 pred_df 생성 가능
    """
    df = games_df_clean.copy()

    # --------------------------------------------------
    # 1) hitter feature merge (있을 때만)
    # --------------------------------------------------
    if hitter_team_features is not None and not hitter_team_features.empty:
        home_hit = hitter_team_features.copy().rename(columns={
            "team_code": "home_team_code",
            "lineup_n_hitters": "home_lineup_n_hitters",
            "lineup_OPS": "home_lineup_OPS",
            "lineup_OBP": "home_lineup_OBP",
            "lineup_SLG": "home_lineup_SLG",
            "top5_n": "home_top5_n",
            "top5_OPS": "home_top5_OPS",
            "top5_OBP": "home_top5_OBP",
        })

        away_hit = hitter_team_features.copy().rename(columns={
            "team_code": "away_team_code",
            "lineup_n_hitters": "away_lineup_n_hitters",
            "lineup_OPS": "away_lineup_OPS",
            "lineup_OBP": "away_lineup_OBP",
            "lineup_SLG": "away_lineup_SLG",
            "top5_n": "away_top5_n",
            "top5_OPS": "away_top5_OPS",
            "top5_OBP": "away_top5_OBP",
        })

        df = df.merge(home_hit, on=["game_id", "home_team_code"], how="left")
        df = df.merge(away_hit, on=["game_id", "away_team_code"], how="left")

        # hitter diff 생성
        diff_pairs_hit = [
            ("lineup_OPS", "home_lineup_OPS", "away_lineup_OPS"),
            ("lineup_OBP", "home_lineup_OBP", "away_lineup_OBP"),
            ("lineup_SLG", "home_lineup_SLG", "away_lineup_SLG"),
            ("top5_OPS", "home_top5_OPS", "away_top5_OPS"),
            ("top5_OBP", "home_top5_OBP", "away_top5_OBP"),
        ]

        for new_name, h_col, a_col in diff_pairs_hit:
            if h_col in df.columns and a_col in df.columns:
                df[f"{new_name}_diff"] = df[h_col] - df[a_col]

    # --------------------------------------------------
    # 2) pitcher feature merge (필수)
    # --------------------------------------------------
    if sp_features is not None and not sp_features.empty:
        home_sp = sp_features.copy().rename(columns={
            "team_code": "home_team_code",
            "sp_player_id": "home_sp_player_id",
            "sp_player_name": "home_sp_player_name",
            "sp_ERA": "home_sp_ERA",
            "sp_FIP": "home_sp_FIP",
            "sp_WHIP": "home_sp_WHIP",
            "sp_K9": "home_sp_K9",
            "sp_BB9": "home_sp_BB9",
            "sp_HR9": "home_sp_HR9",
            "sp_KBB": "home_sp_KBB",
            "sp_QS": "home_sp_QS",
            "sp_GS": "home_sp_GS",
        })

        away_sp = sp_features.copy().rename(columns={
            "team_code": "away_team_code",
            "sp_player_id": "away_sp_player_id",
            "sp_player_name": "away_sp_player_name",
            "sp_ERA": "away_sp_ERA",
            "sp_FIP": "away_sp_FIP",
            "sp_WHIP": "away_sp_WHIP",
            "sp_K9": "away_sp_K9",
            "sp_BB9": "away_sp_BB9",
            "sp_HR9": "away_sp_HR9",
            "sp_KBB": "away_sp_KBB",
            "sp_QS": "away_sp_QS",
            "sp_GS": "away_sp_GS",
        })

        df = df.merge(home_sp, on=["game_id", "home_team_code"], how="left")
        df = df.merge(away_sp, on=["game_id", "away_team_code"], how="left")

        # pitcher diff 생성
        diff_pairs_pit = [
            ("sp_ERA", "home_sp_ERA", "away_sp_ERA"),
            ("sp_FIP", "home_sp_FIP", "away_sp_FIP"),
            ("sp_WHIP", "home_sp_WHIP", "away_sp_WHIP"),
            ("sp_K9", "home_sp_K9", "away_sp_K9"),
            ("sp_BB9", "home_sp_BB9", "away_sp_BB9"),
            ("sp_HR9", "home_sp_HR9", "away_sp_HR9"),
            ("sp_KBB", "home_sp_KBB", "away_sp_KBB"),
        ]

        for new_name, h_col, a_col in diff_pairs_pit:
            if h_col in df.columns and a_col in df.columns:
                df[f"{new_name}_diff"] = df[h_col] - df[a_col]

    return df

NameError: name 'pd' is not defined

In [ ]:
model_df

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,-0.013535,-0.012362,0.72,0.24084,0.19,-0.211,0.207,0.114,-0.2779,1
1,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,-0.013535,-0.012362,0.72,0.24084,0.19,-1.471,-0.694,-0.285,0.0589,1
2,20230042,2023-04-11 09:30:00,2023,1001,9002,7003,14113,14581,원태인,오원석,...,-0.000441,0.004849,-1.99,-0.73886,-0.30,0.645,-2.253,0.216,1.7246,0
3,20230043,2023-04-11 09:30:00,2023,2002,7002,6001,10058,14619,양현종,남지민,...,0.036835,0.011606,-2.87,-0.10633,-0.44,1.504,-0.580,0.684,1.0016,0
4,20230044,2023-04-11 09:30:00,2023,3001,5002,8001,15011,15486,반즈,박명근,...,-0.105756,-0.048248,-1.80,-1.41826,-0.17,0.754,-1.950,-0.384,1.1964,1
5,20230045,2023-04-11 09:30:00,2023,11001,12001,8005,13085,15542,신민혁,슐서,...,0.052905,0.036511,-1.64,-0.32167,-0.41,0.814,-0.693,-0.054,1.3800,1
6,20230091,2023-04-22 08:00:00,2023,6002,12001,1001,14770,15542,최승용,슐서,...,-0.010307,0.003771,-1.65,-0.30797,-0.26,0.307,0.220,-0.357,-0.0882,1
7,20230092,2023-04-22 08:00:00,2023,9002,10001,2001,15528,11379,맥카티,최원태,...,0.031180,-0.001007,0.14,-0.15690,0.14,1.171,0.565,0.076,-0.1119,1
8,20230092,2023-04-22 08:00:00,2023,9002,10001,2001,15528,11379,맥카티,최원태,...,0.031180,-0.001007,0.14,-0.15690,0.14,-0.089,-0.336,-0.323,0.2249,1
9,20230093,2023-04-22 08:00:00,2023,7002,5002,4001,14619,10652,남지민,임찬규,...,-0.046549,-0.042822,3.03,-0.35205,0.43,-0.912,-0.253,-0.622,-0.1382,0
10,20230094,2023-04-22 08:00:00,2023,2002,1001,6001,10058,14113,양현종,원태인,...,-0.030571,-0.014989,0.34,-0.46813,0.07,0.880,0.486,-0.216,-0.2292,1
11,20230095,2023-04-22 08:00:00,2023,11001,3001,8005,13085,15011,신민혁,반즈,...,0.108906,0.041400,0.70,0.61176,-0.13,-0.611,-1.115,0.716,1.2550,0
12,20230096,2023-04-23 05:00:00,2023,6002,12001,1001,12852,11308,최원준,고영표,...,-0.023476,-0.006359,2.15,1.37671,0.22,0.061,1.362,0.559,-3.4643,0
13,20230097,2023-04-23 05:00:00,2023,9002,10001,2001,14581,12865,오원석,이승호,...,0.019617,-0.013489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
14,20230098,2023-04-23 05:00:00,2023,7002,5002,4001,10609,14780,이태양,강효종,...,-0.012249,-0.030427,-3.00,-1.19008,-0.50,0.643,-3.101,0.213,2.2619,1
15,20230099,2023-04-23 05:00:00,2023,2002,1001,6001,15533,10363,앤더슨,백정현,...,-0.026641,-0.010547,0.09,-0.07941,0.00,1.837,0.280,0.148,0.4282,1
16,20230100,2023-04-23 05:00:00,2023,11001,3001,8005,14763,11310,이용준,박세웅,...,0.100841,0.029308,0.85,1.37867,0.23,-0.823,2.462,0.204,-1.0500,0

In [ ]:
'''# 실행하여 경기단위 df 만들기 

# 1. 전처리
games_model = prepare_games_for_modeling(games_df_clean if "games_df_clean" in globals() else games_df)
lineup_model = prepare_lineup(lineup_df)
season_hit_model = prepare_season_hitters(season_hit_df)
season_pit_model = prepare_season_pitchers(season_pit_df)

# 2. 팀 타자 feature
hitter_team_features = build_hitter_team_features(lineup_model, season_hit_model)

# 3. 선발투수 feature
sp_features = build_starting_pitcher_features(lineup_model, season_pit_model)

# 4. 최종 경기 단위 데이터셋
model_df = make_game_level_dataset(
    games_df_clean=games_model,
    hitter_team_features=hitter_team_features,
    sp_features=sp_features
)

display(model_df.head())
print(model_df.shape)'''

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,-0.013535,-0.012362,0.72,0.24084,0.19,-0.211,0.207,0.114,-0.2779,1
1,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,-0.013535,-0.012362,0.72,0.24084,0.19,-1.471,-0.694,-0.285,0.0589,1
2,20230042,2023-04-11 09:30:00,2023,1001,9002,7003,14113,14581,원태인,오원석,...,-0.000441,0.004849,-1.99,-0.73886,-0.30,0.645,-2.253,0.216,1.7246,0
3,20230043,2023-04-11 09:30:00,2023,2002,7002,6001,10058,14619,양현종,남지민,...,0.036835,0.011606,-2.87,-0.10633,-0.44,1.504,-0.580,0.684,1.0016,0
4,20230044,2023-04-11 09:30:00,2023,3001,5002,8001,15011,15486,반즈,박명근,...,-0.105756,-0.048248,-1.80,-1.41826,-0.17,0.754,-1.950,-0.384,1.1964,1

(17, 70)

In [ ]:
problem_pitchers = [12930,
 10126,
 12944,
 10131,
 16148,
 11284,
 14613,
 14617,
 15001,
 16153,
 10652,
 15643,
 15646,
 16160,
 14113,
 15011,
 13091,
 15143,
 15528,
 15146,
 15531,
 15147,
 15533,
 11310,
 11311,
 15536,
 15153,
 14770,
 15535,
 14769,
 14132,
 14128,
 12852,
 11318,
 16065,
 15045,
 15432,
 10058,
 15485,
 14808,
 16088,
 16123,
 11232,
 10609,
 11379,
 13941,
 13942,
 14581,
 10363,
 14588,
 14589]

summary_rows = []

for pid in problem_pitchers:
    res = api_get("prediction/playerSeason", {"p_no": str(pid)})
    time.sleep(0.2)
    

    basic_df = pd.DataFrame(res.get("basic", {}).get("list", []))
    deepen_df = pd.DataFrame(res.get("deepen", {}).get("list", []))

    if not basic_df.empty and "year" in basic_df.columns:
        basic_df["year"] = pd.to_numeric(basic_df["year"], errors="coerce")

    if not deepen_df.empty and "year" in deepen_df.columns:
        deepen_df["year"] = pd.to_numeric(deepen_df["year"], errors="coerce")

    basic_n_2023 = ((basic_df["year"] == 2023).sum() if "year" in basic_df.columns else 0)
    deepen_n_2023 = ((deepen_df["year"] == 2023).sum() if "year" in deepen_df.columns else 0)

    summary_rows.append({
        "player_id": pid,
        "basic_n_2023": int(basic_n_2023),
        "deepen_n_2023": int(deepen_n_2023),
    })

summary_df = pd.DataFrame(summary_rows)
display(summary_df)

KeyboardInterrupt:

In [ ]:
games_model

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20230041,2023-04-11 09:30:00,2023,6002,10001,1001,14770,11379,최승용,최원태,...,4,1,3,18:30:00,10400,13.0,84,21100,3.1,None
1,20230042,2023-04-11 09:30:00,2023,1001,9002,7003,14113,14581,원태인,오원석,...,5,0,3,18:30:00,10400,20.2,59,20900,1.8,None
2,20230043,2023-04-11 09:30:00,2023,2002,7002,6001,10058,14619,양현종,남지민,...,5,0,3,18:30:00,10400,16.9,92,21300,2.2,None
3,20230044,2023-04-11 09:30:00,2023,3001,5002,8001,15011,15486,반즈,박명근,...,5,1,3,18:30:00,10500,18.4,70,20900,3.4,None
4,20230045,2023-04-11 09:30:00,2023,11001,12001,8005,13085,15542,신민혁,슐서,...,0,1,3,18:30:00,10400,18.3,76,21500,1.0,None
5,20230091,2023-04-22 08:00:00,2023,6002,12001,1001,14770,15542,최승용,슐서,...,1,1,3,17:00:00,10100,21.7,13,20500,2.0,None
6,20230092,2023-04-22 08:00:00,2023,9002,10001,2001,15528,11379,맥카티,최원태,...,2,1,3,17:00:00,10400,21.2,11,20100,2.5,None
7,20230093,2023-04-22 08:00:00,2023,7002,5002,4001,14619,10652,남지민,임찬규,...,3,0,3,17:00:00,10400,20.0,21,20700,4.6,None
8,20230094,2023-04-22 08:00:00,2023,2002,1001,6001,10058,14113,양현종,원태인,...,2,1,3,17:00:00,10100,21.3,34,21500,2.6,None
9,20230095,2023-04-22 08:00:00,2023,11001,3001,8005,13085,15011,신민혁,반즈,...,10,0,3,17:00:00,10100,17.3,27,20300,2.4,None
10,20230096,2023-04-23 05:00:00,2023,6002,12001,1001,12852,11308,최원준,고영표,...,1,0,3,14:00:00,10100,22.0,20,20300,2.4,None
11,20230097,2023-04-23 05:00:00,2023,9002,10001,2001,14581,12865,오원석,이승호,...,7,1,3,14:00:00,10100,20.5,27,21300,1.6,None
12,20230098,2023-04-23 05:00:00,2023,7002,5002,4001,10609,14780,이태양,강효종,...,6,1,3,14:00:00,10400,20.2,23,20700,1.3,None
13,20230099,2023-04-23 05:00:00,2023,2002,1001,6001,15533,10363,앤더슨,백정현,...,3,1,3,14:00:00,10400,19.0,32,21500,1.8,None
14,20230100,2023-04-23 05:00:00,2023,11001,3001,8005,14763,11310,이용준,박세웅,...,5,0,3,14:00:00,10400,17.5,37,20900,1.1,None

In [ ]:
season_pit_df

,player_id,year,team_code,GS,IP,IP_decimal,ERA,FIP,WHIP,K9,BB9,HR9,KBB,QS,snapshot_date
0,10363,2023,1001,18,100.2,100.666667,3.67,3.90591,1.29,5.454,2.682,0.536,2.0333,8,2023-04-22
4,11404,2023,1001,3,19.1,19.333333,7.91,5.90273,2.07,5.121,5.586,0.931,0.9167,0,2023-04-22
6,12530,2023,1001,0,9.1,9.333333,4.82,8.85286,1.82,7.714,6.750,2.893,1.1429,0,2023-04-22
8,10685,2023,1001,5,64.0,64.000000,4.50,4.39928,1.38,6.891,3.094,0.984,2.2273,0,2023-04-22
11,10523,2023,1001,0,43.0,43.000000,4.81,3.62835,1.40,5.860,1.047,0.628,5.6000,0,2023-04-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,13130,2023,12001,0,24.2,24.666667,6.93,7.44118,1.42,2.919,3.284,2.189,0.8889,0,2023-04-22
388,15143,2023,12001,29,160.0,160.000000,3.54,3.14428,1.21,8.831,2.531,0.675,3.4889,11,2023-04-22
390,11284,2023,12001,4,35.0,35.000000,6.69,4.36357,1.91,4.371,1.543,0.771,2.8333,0,2023-04-22
393,14108,2023,12001,0,73.2,73.666667,3.42,4.22530,1.19,4.887,2.443,0.611,2.0000,0,2023-04-22
397,15542,2023,12001,9,49.2,49.666667,5.62,4.33653,1.61,6.342,2.537,1.087,2.5000,3,2023-04-22

In [ ]:
season_hit_model['team_code'].unique()

array(['1001', '10001', '2002', '3001', '5002', '6002', '7002', '9002',
       '11001', '12001'], dtype=object)

In [ ]:
hitter_team_features

,game_id,team_code,lineup_n_hitters,lineup_OPS,lineup_OBP,lineup_SLG,top5_n,top5_OPS,top5_OBP
0,20230041,10001,9,0.741863,0.354533,0.387331,5,0.771619,0.367792
1,20230041,6002,9,0.747009,0.345395,0.401614,5,0.758084,0.355430
2,20230042,1001,9,0.767009,0.349069,0.417940,5,0.798128,0.361185
3,20230042,9002,9,0.760653,0.348073,0.412580,5,0.798569,0.356336
4,20230043,2002,9,0.735926,0.345530,0.390396,5,0.779967,0.358466
5,20230043,7002,9,0.704245,0.329925,0.374320,5,0.743132,0.346860
6,20230044,3001,9,0.695640,0.333647,0.361993,5,0.713518,0.343895
7,20230044,5002,9,0.783629,0.371367,0.412263,5,0.819274,0.392143
8,20230045,11001,9,0.773582,0.366171,0.407411,5,0.833821,0.390592
9,20230045,12001,9,0.752064,0.350972,0.401092,5,0.780916,0.354081
10,20230091,12001,9,0.730899,0.339073,0.391826,5,0.765309,0.344399
11,20230091,6002,9,0.750830,0.345688,0.405142,5,0.755002,0.348170
12,20230092,10001,9,0.722378,0.348455,0.373923,5,0.770445,0.366251
13,20230092,9002,9,0.757006,0.346321,0.410685,5,0.801624,0.365245
14,20230093,5002,9,0.786951,0.374001,0.412950,5,0.819274,0.392143
15,20230093,7002,9,0.722569,0.340899,0.381670,5,0.772725,0.349322
16,20230094,1001,9,0.761258,0.354608,0.406650,5,0.812653,0.379874
17,20230094,2002,9,0.751354,0.355869,0.395485,5,0.782082,0.364884
18,20230095,11001,9,0.748283,0.356185,0.392098,5,0.799790,0.372778
19,20230095,3001,9,0.698039,0.335466,0.362573,5,0.690884,0.331378
20,20230096,12001,9,0.743986,0.347551,0.396435,5,0.783404,0.355064
21,20230096,6002,9,0.750830,0.345688,0.405142,5,0.759928,0.348705
22,20230097,10001,9,0.716912,0.346584,0.370327,5,0.763676,0.364368
23,20230097,9002,9,0.741834,0.341506,0.400328,5,0.783293,0.350879
24,20230098,5002,9,0.786951,0.374001,0.412950,5,0.819274,0.392143
25,20230098,7002,9,0.726802,0.346280,0.380521,5,0.807025,0.361716
26,20230099,1001,9,0.766017,0.357823,0.408193,5,0.812653,0.379874
27,20230099,2002,9,0.745433,0.354682,0.390750,5,0.786013,0.369326
28,20230100,11001,9,0.752443,0.357400,0.395043,5,0.799790,0.372778
29,20230100,3001,9,0.686367,0.334061,0.352306,5,0.698949,0.343470

In [ ]:
sp_features.head(10)

,game_id,team_code,sp_player_id,sp_player_name,sp_ERA,sp_FIP,sp_WHIP,sp_K9,sp_BB9,sp_HR9,sp_KBB,sp_QS,sp_GS
0,20230041,6002,14770,최승용,3.97,4.02856,1.35,6.649,2.757,0.730,2.4118,4.0,20.0
1,20230041,10001,11379,최원태,3.25,3.78772,1.16,6.860,2.550,0.616,2.6897,11.0,17.0
2,20230041,10001,11379,최원태,3.25,3.78772,1.16,8.120,3.451,1.015,2.3529,11.0,17.0
3,20230042,1001,14113,원태인,3.24,4.16595,1.27,6.120,2.040,0.900,3.0000,17.0,26.0
4,20230042,9002,14581,오원석,5.23,4.90481,1.57,5.475,4.293,0.684,1.2754,7.0,27.0
5,20230043,2002,10058,양현종,3.58,3.69782,1.34,7.000,2.526,0.684,2.7708,14.0,29.0
6,20230043,7002,14619,남지민,6.45,3.80415,1.78,5.496,3.106,0.000,1.7692,1.0,7.0
7,20230044,3001,15011,반즈,3.28,3.40310,1.33,7.767,2.959,0.317,2.6250,18.0,30.0
8,20230044,5002,15486,박명근,5.08,4.82136,1.50,7.013,4.909,0.701,1.4286,0.0,1.0
9,20230045,11001,13085,신민혁,3.98,4.01486,1.20,7.156,1.844,1.033,3.8800,5.0,24.0

In [ ]:
def _get_last_team_code(group: pd.DataFrame):
    """
    같은 player_id, year 그룹 내에서 마지막 team_code 반환
    - API에서 들어온 행 순서를 그대로 믿고 마지막 팀으로 간주
    """
    if "team_code" not in group.columns:
        return np.nan

    vals = group["team_code"].dropna().astype(str)
    if len(vals) == 0:
        return np.nan

    return vals.iloc[-1]

In [ ]:
def deduplicate_hitter_season_last_team(df: pd.DataFrame) -> pd.DataFrame:
    """
    같은 선수의 같은 시즌 여러 행(팀 이동 등)을 1행으로 통합
    - team_code: 마지막 팀으로 통일
    - counting stat: 합산
    - rate stat: PA 가중평균 (불가능하면 평균)
    """
    df = df.copy()

    # year 숫자화
    df["year"] = pd.to_numeric(df["year"], errors="coerce")

    # 숫자 컬럼 변환
    numeric_cols = [
        "PA", "AB", "H", "HR", "RBI", "BB", "SO",
        "AVG", "OBP", "SLG", "OPS", "wOBA", "wRCplus", "BBK"
    ]
    for c in numeric_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    out_rows = []

    for (player_id, year), g in df.groupby(["player_id", "year"], sort=False):
        row = {
            "player_id": str(player_id),
            "year": year,
            # 마지막 팀으로 통일
            "team_code": _get_last_team_code(g),
        }

        # 이름은 마지막 값 사용
        if "player_name" in g.columns:
            name_vals = g["player_name"].dropna()
            row["player_name"] = name_vals.iloc[-1] if len(name_vals) > 0 else np.nan

        # -------------------------
        # counting stat 합산
        # -------------------------
        count_cols = ["PA", "AB", "H", "HR", "RBI", "BB", "SO"]
        for c in count_cols:
            if c in g.columns:
                row[c] = g[c].sum(min_count=1)

        # -------------------------
        # 재계산/가중평균용 기반 값
        # -------------------------
        PA = row.get("PA", np.nan)
        AB = row.get("AB", np.nan)
        H  = row.get("H", np.nan)

        # AVG = H / AB
        if "AVG" in df.columns:
            row["AVG"] = (H / AB) if pd.notna(H) and pd.notna(AB) and AB != 0 else np.nan

        # 단순 재계산이 어려운 rate stat
        weighted_rate_cols = ["OBP", "SLG", "OPS", "wOBA", "wRCplus", "BBK"]

        for c in weighted_rate_cols:
            if c in g.columns:
                tmp = g[[c]].copy()

                # PA가 있으면 PA 가중평균
                if "PA" in g.columns:
                    tmp["PA"] = pd.to_numeric(g["PA"], errors="coerce")
                    tmp = tmp.dropna(subset=[c])

                    if not tmp.empty and tmp["PA"].fillna(0).sum() > 0:
                        row[c] = np.average(tmp[c], weights=tmp["PA"].fillna(0))
                    else:
                        row[c] = tmp[c].mean() if not tmp.empty else np.nan
                else:
                    row[c] = pd.to_numeric(g[c], errors="coerce").mean()

        out_rows.append(row)

    out = pd.DataFrame(out_rows)

    ordered_cols = [
        "player_id", "player_name", "team_code", "year",
        "PA", "AB", "H", "HR", "RBI", "BB", "SO",
        "AVG", "OBP", "SLG", "OPS", "wOBA", "wRCplus", "BBK"
    ]
    ordered_cols = [c for c in ordered_cols if c in out.columns]

    return out[ordered_cols].copy()

In [ ]:
def deduplicate_pitcher_season_last_team(df: pd.DataFrame) -> pd.DataFrame:
    """
    같은 선수의 같은 시즌 여러 행(팀 이동 등)을 1행으로 통합
    - team_code: 마지막 팀으로 통일
    - counting stat: 합산
    - rate stat: IP 가중평균
    """
    df = df.copy()

    # year 숫자화
    df["year"] = pd.to_numeric(df["year"], errors="coerce")

    # 숫자 컬럼 변환
    numeric_cols = [
        "GS", "IP", "IP_decimal", "ERA", "FIP", "WHIP",
        "K9", "BB9", "HR9", "KBB", "QS"
    ]
    for c in numeric_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    out_rows = []

    for (player_id, year), g in df.groupby(["player_id", "year"], sort=False):
        row = {
            "player_id": str(player_id),
            "year": year,
            # 마지막 팀으로 통일
            "team_code": _get_last_team_code(g),
        }

        # 이름은 마지막 값 사용
        if "player_name" in g.columns:
            name_vals = g["player_name"].dropna()
            row["player_name"] = name_vals.iloc[-1] if len(name_vals) > 0 else np.nan

        # -------------------------
        # counting stat 합산
        # -------------------------
        count_cols = ["GS", "QS"]
        for c in count_cols:
            if c in g.columns:
                row[c] = g[c].sum(min_count=1)

        # -------------------------
        # IP는 decimal 기준으로 합산
        # -------------------------
        if "IP_decimal" in g.columns:
            row["IP_decimal"] = g["IP_decimal"].sum(min_count=1)
        elif "IP" in g.columns:
            row["IP"] = g["IP"].sum(min_count=1)

        # -------------------------
        # rate stat은 IP 가중평균
        # -------------------------
        weight_col = "IP_decimal" if "IP_decimal" in g.columns else ("IP" if "IP" in g.columns else None)
        weighted_rate_cols = ["ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB"]

        for c in weighted_rate_cols:
            if c in g.columns:
                tmp = g[[c]].copy()

                if weight_col is not None:
                    tmp[weight_col] = pd.to_numeric(g[weight_col], errors="coerce")
                    tmp = tmp.dropna(subset=[c])

                    if not tmp.empty and tmp[weight_col].fillna(0).sum() > 0:
                        row[c] = np.average(tmp[c], weights=tmp[weight_col].fillna(0))
                    else:
                        row[c] = tmp[c].mean() if not tmp.empty else np.nan
                else:
                    row[c] = pd.to_numeric(g[c], errors="coerce").mean()

        out_rows.append(row)

    out = pd.DataFrame(out_rows)

    ordered_cols = [
        "player_id", "player_name", "team_code", "year",
        "GS", "IP_decimal", "ERA", "FIP", "WHIP",
        "K9", "BB9", "HR9", "KBB", "QS"
    ]
    ordered_cols = [c for c in ordered_cols if c in out.columns]

    return out[ordered_cols].copy()

In [ ]:
def deduplicate_pitcher_season_last_team(df: pd.DataFrame) -> pd.DataFrame:
    """
    같은 선수의 같은 시즌 여러 행(팀 이동 등)을 1행으로 통합
    - team_code: 마지막 팀으로 통일
    - counting stat: 합산
    - rate stat: IP 가중평균
    """
    df = df.copy()

    # year 숫자화
    df["year"] = pd.to_numeric(df["year"], errors="coerce")

    # 숫자 컬럼 변환
    numeric_cols = [
        "GS", "IP", "IP_decimal", "ERA", "FIP", "WHIP",
        "K9", "BB9", "HR9", "KBB", "QS"
    ]
    for c in numeric_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    out_rows = []

    for (player_id, year), g in df.groupby(["player_id", "year"], sort=False):
        row = {
            "player_id": str(player_id),
            "year": year,
            # 마지막 팀으로 통일
            "team_code": _get_last_team_code(g),
        }

        # 이름은 마지막 값 사용
        if "player_name" in g.columns:
            name_vals = g["player_name"].dropna()
            row["player_name"] = name_vals.iloc[-1] if len(name_vals) > 0 else np.nan

        # -------------------------
        # counting stat 합산
        # -------------------------
        count_cols = ["GS", "QS"]
        for c in count_cols:
            if c in g.columns:
                row[c] = g[c].sum(min_count=1)

        # -------------------------
        # IP는 decimal 기준으로 합산
        # -------------------------
        if "IP_decimal" in g.columns:
            row["IP_decimal"] = g["IP_decimal"].sum(min_count=1)
        elif "IP" in g.columns:
            row["IP"] = g["IP"].sum(min_count=1)

        # -------------------------
        # rate stat은 IP 가중평균
        # -------------------------
        weight_col = "IP_decimal" if "IP_decimal" in g.columns else ("IP" if "IP" in g.columns else None)
        weighted_rate_cols = ["ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB"]

        for c in weighted_rate_cols:
            if c in g.columns:
                tmp = g[[c]].copy()

                if weight_col is not None:
                    tmp[weight_col] = pd.to_numeric(g[weight_col], errors="coerce")
                    tmp = tmp.dropna(subset=[c])

                    if not tmp.empty and tmp[weight_col].fillna(0).sum() > 0:
                        row[c] = np.average(tmp[c], weights=tmp[weight_col].fillna(0))
                    else:
                        row[c] = tmp[c].mean() if not tmp.empty else np.nan
                else:
                    row[c] = pd.to_numeric(g[c], errors="coerce").mean()

        out_rows.append(row)

    out = pd.DataFrame(out_rows)

    ordered_cols = [
        "player_id", "player_name", "team_code", "year",
        "GS", "IP_decimal", "ERA", "FIP", "WHIP",
        "K9", "BB9", "HR9", "KBB", "QS"
    ]
    ordered_cols = [c for c in ordered_cols if c in out.columns]

    return out[ordered_cols].copy()

In [ ]:
def prepare_season_pitchers(season_pit_df: pd.DataFrame) -> pd.DataFrame:
    df = season_pit_df.copy()

    df["player_id"] = df["player_id"].astype(str)

    if "team_code" in df.columns:
        df["team_code"] = df["team_code"].astype(str)

    # year -> season 맞춤
    if "year" in df.columns:
        df["year"] = pd.to_numeric(df["year"], errors="coerce")
        df["season"] = df["year"]

    num_cols = ["GS", "IP", "IP_decimal", "ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB", "QS"]
    for c in num_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    return df

In [ ]:
def build_modeling_data_pipeline(
    date_list,
    team_codes=None,
    roster_code="1",
    sleep_sec=0.2,
    verbose=True
):
    """
    date_list를 입력받아
    1) games 수집
    2) 정상 경기만 필터
    3) lineup 수집
    4) roster 수집 (date_list 전체 기준)
    5) player season 수집
    6) 시즌 중 팀 이동 선수 처리 (마지막 팀으로 통일 + 시즌 성적 통합)
    7) pitcher 결측/무한대 처리
    8) 경기 단위 model_df 생성
    까지를 한 번에 수행

    Parameters
    ----------
    date_list : list[str]
        예: ["2025-04-22", "2025-04-23", "2025-04-24"]

    team_codes : list[str], optional
        팀코드 리스트. None이면 KBO 10개 구단 기본값 사용.

    roster_code : str, default "1"
        playerRoster 호출용 code 파라미터

    sleep_sec : float, default 0.2
        반복 API 호출 간 텀 (429 방지)

    verbose : bool, default True
        진행 로그 출력 여부

    Returns
    -------
    result : dict
        {
            "games_df": ...,
            "games_df_clean": ...,
            "lineup_df": ...,
            "roster_df": ...,
            "season_hit_df": ...,
            "season_pit_df": ...,
            "games_model": ...,
            "lineup_model": ...,
            "season_hit_model": ...,
            "season_pit_model": ...,
            "hitter_team_features": ...,
            "sp_features": ...,
            "model_df": ...
        }
    """

    # --------------------------------------------------
    # 0) 기본 팀코드 설정
    # --------------------------------------------------
    if team_codes is None:
        team_codes = ["1001", "2002", "3001", "5002", "6002", "7002", "9002", "10001", "11001", "12001"]
        # 삼성, KIA, 롯데, LG, 두산, 한화, SSG, 키움, NC, KT

    # --------------------------------------------------
    # 1) games 수집
    # --------------------------------------------------
    if verbose:
        print("=== 1. collect_games ===")
    games_df = collect_games(date_list, sleep_sec=sleep_sec)

    # --------------------------------------------------
    # 2) 정상 경기만 필터
    # game_state == 3 이고 점수가 존재하는 경기만 사용
    # --------------------------------------------------
    if verbose:
        print("=== 2. filter normal games ===")

    games_df_clean = games_df[
        (games_df["game_state"] == 3) &
        (games_df["home_score"].notna()) &
        (games_df["away_score"].notna())
    ].copy()

    if verbose:
        print(f"games_df.shape       = {games_df.shape}")
        print(f"games_df_clean.shape = {games_df_clean.shape}")

    # --------------------------------------------------
    # 3) lineup 수집
    # 정상 경기만 대상으로 호출
    # --------------------------------------------------
    if verbose:
        print("=== 3. collect_lineups ===")

    lineup_df = collect_lineups(games_df_clean, sleep_sec=sleep_sec)

    if verbose:
        print(f"lineup_df.shape = {lineup_df.shape}")

    # --------------------------------------------------
    # 4) roster 수집
    # 특정 하루만 수집하면 선수 누락 가능하므로
    # date_list 전체 기준으로 roster를 합침
    # --------------------------------------------------
    if verbose:
        print("=== 4. collect_rosters (all dates) ===")

    roster_dfs = []

    for dt in date_list:
        if verbose:
            print(f"roster date: {dt}")

        tmp_roster = collect_rosters(
            date=dt,
            team_codes=team_codes,
            code=roster_code,
            sleep_sec=sleep_sec
        )

        if not tmp_roster.empty:
            roster_dfs.append(tmp_roster)

    if roster_dfs:
        roster_df = pd.concat(roster_dfs, ignore_index=True).drop_duplicates()
    else:
        roster_df = pd.DataFrame(columns=["snapshot_date", "team_code", "player_id", "player_name", "join_date"])

    if verbose:
        print(f"roster_df.shape = {roster_df.shape}")

    # --------------------------------------------------
    # 5) player_ids 추출
    # --------------------------------------------------
    if roster_df.empty:
        raise ValueError("roster_df가 비어 있습니다. playerSeason 수집을 진행할 수 없습니다.")

    player_ids = roster_df["player_id"].astype(str).unique().tolist()

    if verbose:
        print(f"n_unique_player_ids = {len(player_ids)}")

    # --------------------------------------------------
    # 6) playerSeason 수집
    # --------------------------------------------------
    snapshot_date = date_list[0]

    if verbose:
        print("=== 5. collect_player_season ===")

    season_hit_df, season_pit_df = collect_player_season(
        player_ids,
        snapshot_date=snapshot_date,
        sleep_sec=sleep_sec
    )

    # --------------------------------------------------
    # 7) target season 필터
    # 현재 pipeline은 date_list가 한 시즌이라고 가정
    # --------------------------------------------------
    target_year = pd.to_datetime(date_list[0]).year

    season_hit_df["year"] = pd.to_numeric(season_hit_df["year"], errors="coerce")
    season_pit_df["year"] = pd.to_numeric(season_pit_df["year"], errors="coerce")

    season_hit_df = season_hit_df[season_hit_df["year"] == target_year].copy()
    season_pit_df = season_pit_df[season_pit_df["year"] == target_year].copy()

    # --------------------------------------------------
    # 8) 시즌 중 팀 이동 선수 처리
    # 핵심:
    # - player_id + year 기준 1행으로 압축
    # - team_code는 마지막 팀으로 통일
    # - season 성적은 통합
    # --------------------------------------------------
    if verbose:
        print("=== 6. deduplicate season stats (last team + aggregate season) ===")

    season_hit_df = deduplicate_hitter_season_last_team(season_hit_df)
    season_pit_df = deduplicate_pitcher_season_last_team(season_pit_df)

    if verbose:
        print(f"season_hit_df.shape after dedup = {season_hit_df.shape}")
        print(f"season_pit_df.shape after dedup = {season_pit_df.shape}")

    # --------------------------------------------------
    # 9) pitcher 특수값 처리
    # ERA/FIP/WHIP/KBB의 inf, 결측 등을 99.99로 치환
    # --------------------------------------------------
    if verbose:
        print("=== 7. clean pitcher season stats ===")

    pit_fill_cols = [c for c in ["ERA", "FIP", "WHIP", "KBB"] if c in season_pit_df.columns]
    if pit_fill_cols:
        season_pit_df[pit_fill_cols] = (
            season_pit_df[pit_fill_cols]
            .replace([np.inf, -np.inf], np.nan)
            .fillna(99.99)
        )

    # --------------------------------------------------
    # 10) 모델링용 전처리
    # --------------------------------------------------
    if verbose:
        print("=== 8. prepare modeling tables ===")

    games_model = prepare_games_for_modeling(games_df_clean)
    lineup_model = prepare_lineup(lineup_df)
    season_hit_model = prepare_season_hitters(season_hit_df)
    season_pit_model = prepare_season_pitchers(season_pit_df)

    # --------------------------------------------------
    # 11) lineup에 season 붙이기
    # season stats를 player_id + season 기준으로 merge할 수 있게 준비
    # --------------------------------------------------
    lineup_model = lineup_model.merge(
        games_model[["game_id", "season"]],
        on="game_id",
        how="left"
    )

    # --------------------------------------------------
    # 12) 팀 타자 feature 생성
    # 주의:
    # build_hitter_team_features 내부에서
    # season_hit_model과 merge할 때 on=["player_id", "season"] 기준이 되도록
    # 함수도 같이 수정해서 쓰는 것을 권장
    # --------------------------------------------------
    if verbose:
        print("=== 9. build hitter team features ===")

    hitter_team_features = build_hitter_team_features(lineup_model, season_hit_model)

    if verbose:
        print(f"hitter_team_features.shape = {hitter_team_features.shape}")

    # --------------------------------------------------
    # 13) 선발투수 feature 생성
    # 주의:
    # build_starting_pitcher_features 내부에서
    # season_pit_model과 merge할 때 on=["player_id", "season"] 기준이 되도록
    # 함수도 같이 수정해서 쓰는 것을 권장
    # --------------------------------------------------
    if verbose:
        print("=== 10. build starting pitcher features ===")

    sp_features = build_starting_pitcher_features(lineup_model, season_pit_model)

    if verbose:
        print(f"sp_features.shape = {sp_features.shape}")

        # 경기-팀당 1행인지 확인
        if not sp_features.empty:
            print("sp_features rows per (game_id, team_code):")
            print(sp_features.groupby(["game_id", "team_code"]).size().value_counts().head())

    # --------------------------------------------------
    # 14) 최종 경기 단위 데이터셋 생성
    # --------------------------------------------------
    if verbose:
        print("=== 11. make game-level dataset ===")

    model_df = make_game_level_dataset(
        games_df_clean=games_model,
        hitter_team_features=hitter_team_features,
        sp_features=sp_features
    )

    if verbose:
        print(f"model_df.shape = {model_df.shape}")

        # 같은 경기 중복 여부 확인
        print("game_id duplication check:")
        print(model_df["game_id"].value_counts().value_counts().head())

    # --------------------------------------------------
    # 15) diff feature 결측 확인
    # --------------------------------------------------
    if verbose:
        diff_cols = [c for c in model_df.columns if c.endswith("_diff")]
        if diff_cols:
            na_summary = model_df[diff_cols].isna().sum().sort_values(ascending=False)
            print("Top NA counts in diff features:")
            print(na_summary.head(10))

    return {
        "games_df": games_df,
        "games_df_clean": games_df_clean,
        "lineup_df": lineup_df,
        "roster_df": roster_df,
        "season_hit_df": season_hit_df,
        "season_pit_df": season_pit_df,
        "games_model": games_model,
        "lineup_model": lineup_model,
        "season_hit_model": season_hit_model,
        "season_pit_model": season_pit_model,
        "hitter_team_features": hitter_team_features,
        "sp_features": sp_features,
        "model_df": model_df,
    }

In [ ]:
result = build_modeling_data_pipeline(
    date_list=["2025-04-22", "2025-04-23", "2025-04-24"],
    sleep_sec=0.2,
    verbose=True
)

model_df = result["model_df"]
display(model_df.head())
print(model_df.shape)

=== 1. collect_games ===
[games] 2025-04-22: 5 rows
[games] 2025-04-23: 5 rows
[games] 2025-04-24: 5 rows

C:\Users\User\AppData\Local\Temp\ipykernel_16088\1047996336.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()

=== 2. filter normal games ===
games_df.shape       = (15, 21)
games_df_clean.shape = (13, 21)
=== 3. collect_lineups ===
[lineup] 20250131: 20 rows
[lineup] 20250134: 20 rows
[lineup] 20250135: 20 rows
[lineup] 20250136: 20 rows
[lineup] 20250137: 20 rows
[lineup] 20250138: 20 rows
[lineup] 20250139: 20 rows
[lineup] 20250140: 20 rows
[lineup] 20250141: 20 rows
[lineup] 20250142: 20 rows
[lineup] 20250143: 20 rows
[lineup] 20250144: 20 rows
[lineup] 20250145: 20 rows
lineup_df.shape = (260, 13)
=== 4. collect_rosters (all dates) ===
roster date: 2025-04-22
[roster] 2025-04-22 team=1001: 28 rows
[roster] 2025-04-22 team=2002: 28 rows
[roster] 2025-04-22 team=3001: 28 rows
[roster] 2025-04-22 team=5002: 28 rows
[roster] 2025-04-22 team=6002: 28 rows
[roster] 2025-04-22 team=7002: 28 rows
[roster] 2025-04-22 team=9002: 28 rows
[roster] 2025-04-22 team=10001: 28 rows
[roster] 2025-04-22 team=11001: 28 rows
[roster] 2025-04-22 team=12001: 28 rows
roster date: 2025-04-23
[roster] 2025-04-23 team=1001: 28 rows
[roster] 2025-04-23 team=2002: 28 rows
[roster] 2025-04-23 team=3001: 28 rows
[roster] 2025-04-23 team=5002: 28 rows
[roster] 2025-04-23 team=6002: 28 rows
[roster] 2025-04-23 team=7002: 28 rows
[roster] 2025-04-23 team=9002: 28 rows
[roster] 2025-04-23 team=10001: 28 rows
[roster] 2025-04-23 team=11001: 28 rows
[roster] 2025-04-23 team=12001: 28 rows
roster date: 2025-04-24
[roster] 2025-04-24 team=1001: 28 rows
[roster] 2025-04-24 team=2002: 28 rows
[roster] 2025-04-24 team=3001: 28 rows
[roster] 2025-04-24 team=5002: 28 rows
[roster] 2025-04-24 team=6002: 28 rows
[roster] 2025-04-24 team=7002: 28 rows
[roster] 2025-04-24 team=9002: 28 rows
[roster] 2025-04-24 team=10001: 27 rows
[roster] 2025-04-24 team=11001: 28 rows
[roster] 2025-04-24 team=12001: 28 rows
roster_df.shape = (839, 5)
n_unique_player_ids = 287
=== 5. collect_player_season ===
[playerSeason] 10892: OK
[playerSeason] 10363: OK
[playerSeason] 10640: OK
[playerSeason] 10232: OK
[playerSeason] 14113: OK
[playerSeason] 14618: OK
[playerSeason] 12936: OK
[playerSeason] 15034: OK
[playerSeason] 15035: OK
[playerSeason] 14117: OK
[playerSeason] 15496: OK
[playerSeason] 10871: OK
[playerSeason] 10894: OK
[playerSeason] 11489: OK
[playerSeason] 15864: OK
[playerSeason] 15875: OK
[playerSeason] 14616: OK
[playerSeason] 14866: OK
[playerSeason] 15036: OK
[playerSeason] 15882: OK
[playerSeason] 10470: OK
[playerSeason] 16162: OK
[playerSeason] 11379: OK
[playerSeason] 13157: OK
[playerSeason] 14799: OK
[playerSeason] 15531: OK
[playerSeason] 16239: OK
[playerSeason] 16240: OK
[playerSeason] 10058: OK
[playerSeason] 10008: OK
[playerSeason] 11119: OK
[playerSeason] 10909: OK
[playerSeason] 10344: OK
[playerSeason] 12537: OK
[playerSeason] 14181: OK
[playerSeason] 11261: OK
[playerSeason] 11303: OK
[playerSeason] 11099: OK
[playerSeason] 12540: OK
[playerSeason] 14608: OK
[playerSeason] 15057: OK
[playerSeason] 15063: OK
[playerSeason] 11162: OK
[playerSeason] 14124: OK
[playerSeason] 10706: OK
[playerSeason] 12944: OK
[playerSeason] 14612: OK
[playerSeason] 12534: OK
[playerSeason] 10459: OK
[playerSeason] 11159: OK
[playerSeason] 16088: OK
[playerSeason] 14128: OK
[playerSeason] 11126: OK
[playerSeason] 16252: OK
[playerSeason] 16261: OK
[playerSeason] 16262: OK
[playerSeason] 10266: OK
[playerSeason] 10253: OK
[playerSeason] 11310: OK
[playerSeason] 10825: OK
[playerSeason] 12930: OK
[playerSeason] 13154: OK
[playerSeason] 13155: OK
[playerSeason] 14160: OK
[playerSeason] 14163: OK
[playerSeason] 14642: OK
[playerSeason] 12699: OK
[playerSeason] 15011: OK
[playerSeason] 15048: OK
[playerSeason] 10427: OK
[playerSeason] 10753: OK
[playerSeason] 10238: OK
[playerSeason] 14797: OK
[playerSeason] 14794: OK
[playerSeason] 11425: OK
[playerSeason] 16090: OK
[playerSeason] 16091: OK
[playerSeason] 16106: OK
[playerSeason] 14590: OK
[playerSeason] 13071: OK
[playerSeason] 13073: OK
[playerSeason] 10737: OK
[playerSeason] 15051: OK
[playerSeason] 16273: OK
[playerSeason] 10475: OK
[playerSeason] 10749: OK
[playerSeason] 10652: OK
[playerSeason] 12697: OK
[playerSeason] 13009: OK
[playerSeason] 13056: OK
[playerSeason] 10187: OK
[playerSeason] 13109: OK
[playerSeason] 12546: OK
[playerSeason] 14137: OK
[playerSeason] 14143: OK
[playerSeason] 13112: OK
[playerSeason] 12908: OK
[playerSeason] 11190: OK
[playerSeason] 11166: OK
[playerSeason] 13102: OK
[playerSeason] 13103: OK
[playerSeason] 15486: OK
[playerSeason] 15532: OK
[playerSeason] 10387: OK
[playerSeason] 15084: OK
[playerSeason] 14140: OK
[playerSeason] 14783: OK
[playerSeason] 15081: OK
[playerSeason] 11164: OK
[playerSeason] 14846: OK
[playerSeason] 16274: OK
[playerSeason] 16286: OK
[playerSeason] 10643: OK
[playerSeason] 11098: OK
[playerSeason] 12568: OK
[playerSeason] 12850: OK
[playerSeason] 12852: OK
[playerSeason] 10195: OK
[playerSeason] 14733: OK
[playerSeason] 12524: OK
[playerSeason] 11087: OK
[playerSeason] 11198: OK
[playerSeason] 14770: OK
[playerSeason] 11213: OK
[playerSeason] 13070: OK
[playerSeason] 15127: OK
[playerSeason] 10165: OK
[playerSeason] 12522: OK
[playerSeason] 15508: OK
[playerSeason] 13268: OK
[playerSeason] 14736: OK
[playerSeason] 12549: OK
[playerSeason] 16067: OK
[playerSeason] 16068: OK
[playerSeason] 15253: OK
[playerSeason] 16287: OK
[playerSeason] 16289: OK
[playerSeason] 16298: OK
[playerSeason] 16299: OK
[playerSeason] 16300: OK
[playerSeason] 11411: OK
[playerSeason] 11117: OK
[playerSeason] 10913: OK
[playerSeason] 10170: OK
[playerSeason] 14125: OK
[playerSeason] 11414: OK
[playerSeason] 12585: OK
[playerSeason] 13138: OK
[playerSeason] 15013: OK
[playerSeason] 15139: OK
[playerSeason] 12539: OK
[playerSeason] 12871: OK
[playerSeason] 10812: OK
[playerSeason] 11215: OK
[playerSeason] 15421: OK
[playerSeason] 15422: OK
[playerSeason] 10082: OK
[playerSeason] 14706: OK
[playerSeason] 14711: OK
[playerSeason] 16108: OK
[playerSeason] 16110: OK
[playerSeason] 10590: OK
[playerSeason] 16153: OK
[playerSeason] 11334: OK
[playerSeason] 11318: OK
[playerSeason] 16301: OK
[playerSeason] 16312: OK
[playerSeason] 16313: OK
[playerSeason] 10126: OK
[playerSeason] 10636: OK
[playerSeason] 10815: OK
[playerSeason] 10783: OK
[playerSeason] 10131: OK
[playerSeason] 12613: OK
[playerSeason] 12922: OK
[playerSeason] 13126: OK
[playerSeason] 13195: OK
[playerSeason] 14587: OK
[playerSeason] 14687: OK
[playerSeason] 10249: OK
[playerSeason] 14806: OK
[playerSeason] 14807: OK
[playerSeason] 13228: OK
[playerSeason] 10203: OK
[playerSeason] 13128: OK
[playerSeason] 15461: OK
[playerSeason] 15462: OK
[playerSeason] 12541: OK
[playerSeason] 14805: OK
[playerSeason] 16042: OK
[playerSeason] 16146: OK
[playerSeason] 14803: OK
[playerSeason] 15121: OK
[playerSeason] 13167: OK
[playerSeason] 16314: OK
[playerSeason] 16324: OK
[playerSeason] 11222: OK
[playerSeason] 12854: OK
[playerSeason] 13092: OK
[playerSeason] 11225: OK
[playerSeason] 14580: OK
[playerSeason] 10870: OK
[playerSeason] 11376: OK
[playerSeason] 15067: OK
[playerSeason] 11244: OK
[playerSeason] 11161: OK
[playerSeason] 15472: OK
[playerSeason] 15475: OK
[playerSeason] 14591: OK
[playerSeason] 10182: OK
[playerSeason] 12860: OK
[playerSeason] 12918: OK
[playerSeason] 13223: OK
[playerSeason] 16123: OK
[playerSeason] 16127: OK
[playerSeason] 14130: OK
[playerSeason] 14601: OK
[playerSeason] 10557: OK
[playerSeason] 15004: OK
[playerSeason] 16156: OK
[playerSeason] 16328: OK
[playerSeason] 16331: OK
[playerSeason] 16332: OK
[playerSeason] 16339: OK
[playerSeason] 11137: OK
[playerSeason] 11172: OK
[playerSeason] 13080: OK
[playerSeason] 13081: OK
[playerSeason] 13085: OK
[playerSeason] 12897: OK
[playerSeason] 11355: OK
[playerSeason] 12560: OK
[playerSeason] 14764: OK
[playerSeason] 14765: OK
[playerSeason] 10217: OK
[playerSeason] 14220: OK
[playerSeason] 10261: OK
[playerSeason] 13082: OK
[playerSeason] 14156: OK
[playerSeason] 10891: OK
[playerSeason] 14661: OK
[playerSeason] 13261: OK
[playerSeason] 15451: OK
[playerSeason] 11248: OK
[playerSeason] 12565: OK
[playerSeason] 14659: OK
[playerSeason] 14597: OK
[playerSeason] 14747: OK
[playerSeason] 16057: OK
[playerSeason] 14785: OK
[playerSeason] 16349: OK
[playerSeason] 16350: OK
[playerSeason] 11317: OK
[playerSeason] 11323: OK
[playerSeason] 10235: OK
[playerSeason] 13006: OK
[playerSeason] 10407: OK
[playerSeason] 11212: OK
[playerSeason] 11339: OK
[playerSeason] 11333: OK
[playerSeason] 14600: OK
[playerSeason] 14603: OK
[playerSeason] 11308: OK
[playerSeason] 14870: OK
[playerSeason] 11397: OK
[playerSeason] 15089: OK
[playerSeason] 11214: OK
[playerSeason] 15527: OK
[playerSeason] 14108: OK
[playerSeason] 13942: OK
[playerSeason] 10523: OK
[playerSeason] 12885: OK
[playerSeason] 14605: OK
[playerSeason] 12995: OK
[playerSeason] 16027: OK
[playerSeason] 14777: OK
[playerSeason] 14778: OK
[playerSeason] 14581: OK
[playerSeason] 10184: OK
[playerSeason] 10535: OK
[playerSeason] 15509: OK
[playerSeason] 14737: OK
[playerSeason] 10014: OK
[playerSeason] 16076: OK
[playerSeason] 14153: OK
[playerSeason] 14132: OK
[playerSeason] 13250: OK
=== 6. deduplicate season stats (last team + aggregate season) ===
season_hit_df.shape after dedup = (151, 15)
season_pit_df.shape after dedup = (135, 13)
=== 7. clean pitcher season stats ===
=== 8. prepare modeling tables ===
=== 9. build hitter team features ===
hitter_team_features.shape = (26, 9)
=== 10. build starting pitcher features ===
sp_features.shape = (26, 13)
sp_features rows per (game_id, team_code):
1    26
Name: count, dtype: int64
=== 11. make game-level dataset ===
model_df.shape = (13, 70)
game_id duplication check:
count
1    13
Name: count, dtype: int64
Top NA counts in diff features:
lineup_OPS_diff    0
lineup_OBP_diff    0
lineup_SLG_diff    0
top5_OPS_diff      0
top5_OBP_diff      0
sp_ERA_diff        0
sp_FIP_diff        0
sp_WHIP_diff       0
sp_K9_diff         0
sp_BB9_diff        0
dtype: int64

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20250131,2025-04-22 09:30:00,2025,5002,11001,1001,10652,13085,임찬규,신민혁,...,0.043075,0.002417,-1.74,-1.36062,-0.05,0.279,0.472,-1.063,-0.5558,0
1,20250134,2025-04-22 09:30:00,2025,12001,9002,2002,14581,10126,오원석,김광현,...,-0.012903,-0.008249,-1.33,0.26239,-0.11,-0.940,0.412,-0.132,-0.5869,1
2,20250135,2025-04-22 09:30:00,2025,10001,6002,1003,11222,14770,하영민,최승용,...,-0.022400,-0.015781,0.58,-0.58024,0.02,2.372,-0.378,0.144,1.2961,1
3,20250136,2025-04-23 09:30:00,2025,5002,11001,1001,14846,16350,송승기,로건,...,0.023721,-0.018078,-1.03,-0.29169,-0.05,0.061,-0.424,0.002,0.3271,1
4,20250137,2025-04-23 09:30:00,2025,3001,7002,8001,15011,16153,반즈,와이스,...,-0.050807,0.008403,2.45,1.08821,0.38,-2.938,0.529,0.133,-1.4611,0

(13, 70)

In [ ]:
model_df["game_id"].value_counts().value_counts()

count
1    13
Name: count, dtype: int64

In [ ]:
from datetime import datetime, timedelta

def generate_date_list(start_date: str, end_date: str):
    start = datetime.strptime(start_date, "%Y-%m-%d")
    end   = datetime.strptime(end_date, "%Y-%m-%d")

    date_list = []
    cur = start

    while cur <= end:
        date_list.append(cur.strftime("%Y-%m-%d"))
        cur += timedelta(days=1)

    return date_list

In [ ]:
date_list_23 = generate_date_list("2023-03-22", "2023-10-01")

In [ ]:
date_list_24 = generate_date_list("2024-03-22", "2024-10-01")

In [ ]:
date_list_25 = generate_date_list("2025-03-22", "2025-10-01")

In [ ]:
result_23 = build_modeling_data_pipeline(
    date_list=date_list_23,
    sleep_sec=0.2,
    verbose=True
)

model_df_23 = result_23["model_df"]

display(model_df_23.head())
print(model_df_23.shape)

=== 1. collect_games ===
[games] 2023-03-22: 0 rows
[games] 2023-03-23: 5 rows
[games] 2023-03-24: 5 rows
[games] 2023-03-25: 5 rows
[games] 2023-03-26: 5 rows
[games] 2023-03-27: 5 rows
[games] 2023-03-28: 5 rows
[games] 2023-03-29: 0 rows
[games] 2023-03-30: 0 rows
[games] 2023-03-31: 0 rows
[games] 2023-04-01: 5 rows
[games] 2023-04-02: 5 rows
[games] 2023-04-03: 0 rows
[games] 2023-04-04: 5 rows
[games] 2023-04-05: 5 rows
[games] 2023-04-06: 5 rows
[games] 2023-04-07: 5 rows
[games] 2023-04-08: 5 rows
[games] 2023-04-09: 5 rows
[games] 2023-04-10: 0 rows
[games] 2023-04-11: 5 rows
[games] 2023-04-12: 5 rows
[games] 2023-04-13: 5 rows
[games] 2023-04-14: 5 rows
[games] 2023-04-15: 5 rows
[games] 2023-04-16: 5 rows
[games] 2023-04-17: 0 rows
[games] 2023-04-18: 5 rows
[games] 2023-04-19: 5 rows
[games] 2023-04-20: 5 rows
[games] 2023-04-21: 5 rows
[games] 2023-04-22: 5 rows
[games] 2023-04-23: 5 rows
[games] 2023-04-24: 0 rows
[games] 2023-04-25: 5 rows
[games] 2023-04-26: 5 rows
[games] 2023-04-27: 5 rows
[games] 2023-04-28: 5 rows
[games] 2023-04-29: 5 rows
[games] 2023-04-30: 5 rows
[games] 2023-05-01: 0 rows
[games] 2023-05-02: 5 rows
[games] 2023-05-03: 5 rows
[games] 2023-05-04: 5 rows
[games] 2023-05-05: 5 rows
[games] 2023-05-06: 5 rows
[games] 2023-05-07: 5 rows
[games] 2023-05-08: 0 rows
[games] 2023-05-09: 5 rows
[games] 2023-05-10: 5 rows
[games] 2023-05-11: 5 rows
[games] 2023-05-12: 5 rows
[games] 2023-05-13: 5 rows
[games] 2023-05-14: 5 rows
[games] 2023-05-15: 0 rows
[games] 2023-05-16: 5 rows
[games] 2023-05-17: 5 rows
[games] 2023-05-18: 5 rows
[games] 2023-05-19: 5 rows
[games] 2023-05-20: 5 rows
[games] 2023-05-21: 5 rows
[games] 2023-05-22: 0 rows
[games] 2023-05-23: 5 rows
[games] 2023-05-24: 5 rows
[games] 2023-05-25: 5 rows
[games] 2023-05-26: 5 rows
[games] 2023-05-27: 5 rows
[games] 2023-05-28: 5 rows
[games] 2023-05-29: 0 rows
[games] 2023-05-30: 5 rows
[games] 2023-05-31: 5 rows
[games] 2023-06-01: 5 rows
[games] 2023-06-02: 5 rows
[games] 2023-06-03: 5 rows
[games] 2023-06-04: 5 rows
[games] 2023-06-05: 0 rows
[games] 2023-06-06: 5 rows
[games] 2023-06-07: 5 rows
[games] 2023-06-08: 5 rows
[games] 2023-06-09: 5 rows
[games] 2023-06-10: 5 rows
[games] 2023-06-11: 5 rows
[games] 2023-06-12: 0 rows
[games] 2023-06-13: 5 rows
[games] 2023-06-14: 5 rows
[games] 2023-06-15: 5 rows
[games] 2023-06-16: 5 rows
[games] 2023-06-17: 5 rows
[games] 2023-06-18: 5 rows
[games] 2023-06-19: 0 rows
[games] 2023-06-20: 5 rows
[games] 2023-06-21: 5 rows
[games] 2023-06-22: 5 rows
[games] 2023-06-23: 5 rows
[games] 2023-06-24: 5 rows
[games] 2023-06-25: 5 rows
[games] 2023-06-26: 0 rows
[games] 2023-06-27: 5 rows
[games] 2023-06-28: 5 rows
[games] 2023-06-29: 5 rows
[games] 2023-06-30: 5 rows
[games] 2023-07-01: 5 rows
[games] 2023-07-02: 5 rows
[games] 2023-07-03: 0 rows
[games] 2023-07-04: 5 rows
[games] 2023-07-05: 5 rows
[games] 2023-07-06: 5 rows
[games] 2023-07-07: 5 rows
[games] 2023-07-08: 5 rows
[games] 2023-07-09: 5 rows
[games] 2023-07-10: 0 rows
[games] 2023-07-11: 5 rows
[games] 2023-07-12: 5 rows
[games] 2023-07-13: 5 rows
[games] 2023-07-14: 0 rows
[games] 2023-07-15: 0 rows
[games] 2023-07-16: 0 rows
[games] 2023-07-17: 0 rows
[games] 2023-07-18: 0 rows
[games] 2023-07-19: 0 rows
[games] 2023-07-20: 0 rows
[games] 2023-07-21: 5 rows
[games] 2023-07-22: 5 rows
[games] 2023-07-23: 5 rows
[games] 2023-07-24: 0 rows
[games] 2023-07-25: 5 rows
[games] 2023-07-26: 5 rows
[games] 2023-07-27: 5 rows
[games] 2023-07-28: 5 rows
[games] 2023-07-29: 5 rows
[games] 2023-07-30: 5 rows
[games] 2023-07-31: 0 rows
[games] 2023-08-01: 5 rows
[games] 2023-08-02: 5 rows
[games] 2023-08-03: 5 rows
[games] 2023-08-04: 5 rows
[games] 2023-08-05: 5 rows
[games] 2023-08-06: 5 rows
[games] 2023-08-07: 0 rows
[games] 2023-08-08: 5 rows
[games] 2023-08-09: 5 rows
[games] 2023-08-10: 5 rows
[games] 2023-08-11: 5 rows
[games] 2023-08-12: 5 rows
[games] 2023-08-13: 5 rows
[games] 2023-08-14: 0 rows
[games] 2023-08-15: 5 rows
[games] 2023-08-16: 5 rows
[games] 2023-08-17: 5 rows
[games] 2023-08-18: 5 rows
[games] 2023-08-19: 5 rows
[games] 2023-08-20: 5 rows
[games] 2023-08-21: 0 rows
[games] 2023-08-22: 5 rows
[games] 2023-08-23: 5 rows
[games] 2023-08-24: 5 rows
[games] 2023-08-25: 5 rows
[games] 2023-08-26: 5 rows
[games] 2023-08-27: 5 rows
[games] 2023-08-28: 0 rows
[games] 2023-08-29: 5 rows
[games] 2023-08-30: 5 rows
[games] 2023-08-31: 5 rows
[games] 2023-09-01: 5 rows
[games] 2023-09-02: 5 rows
[games] 2023-09-03: 5 rows
[games] 2023-09-04: 1 rows
[games] 2023-09-05: 5 rows
[games] 2023-09-06: 5 rows
[games] 2023-09-07: 5 rows
[games] 2023-09-08: 5 rows
[games] 2023-09-09: 9 rows
[games] 2023-09-10: 5 rows
[games] 2023-09-11: 0 rows
[games] 2023-09-12: 4 rows
[games] 2023-09-13: 3 rows
[games] 2023-09-14: 4 rows
[games] 2023-09-15: 4 rows
[games] 2023-09-16: 5 rows
[games] 2023-09-17: 6 rows
[games] 2023-09-18: 2 rows
[games] 2023-09-19: 5 rows
[games] 2023-09-20: 5 rows
[games] 2023-09-21: 5 rows
[games] 2023-09-22: 5 rows
[games] 2023-09-23: 4 rows
[games] 2023-09-24: 4 rows
[games] 2023-09-25: 0 rows
[games] 2023-09-26: 4 rows
[games] 2023-09-27: 8 rows
[games] 2023-09-28: 4 rows
[games] 2023-09-29: 3 rows
[games] 2023-09-30: 3 rows
[games] 2023-10-01: 5 rows

C:\Users\User\AppData\Local\Temp\ipykernel_27996\1047996336.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()

=== 2. filter normal games ===
games_df.shape       = (788, 21)
games_df_clean.shape = (688, 21)
=== 3. collect_lineups ===
[lineup] 20230711: 20 rows
[lineup] 20230712: 20 rows
[lineup] 20230716: 20 rows
[lineup] 20230717: 20 rows
[lineup] 20230718: 20 rows
[lineup] 20230719: 20 rows
[lineup] 20230720: 20 rows
[lineup] 20230721: 20 rows
[lineup] 20230722: 20 rows
[lineup] 20230723: 20 rows
[lineup] 20230724: 20 rows
[lineup] 20230725: 20 rows
[lineup] 20230726: 20 rows
[lineup] 20230727: 20 rows
[lineup] 20230728: 20 rows
[lineup] 20230729: 20 rows
[lineup] 20230730: 20 rows
[lineup] 20230731: 20 rows
[lineup] 20230732: 20 rows
[lineup] 20230733: 20 rows
[lineup] 20230734: 20 rows
[lineup] 20230735: 20 rows
[lineup] 20230736: 20 rows
[lineup] 20230737: 20 rows
[lineup] 20230738: 20 rows
[lineup] 20230739: 20 rows
[lineup] 20230740: 20 rows
[lineup] 20230001: 20 rows
[lineup] 20230002: 20 rows
[lineup] 20230003: 20 rows
[lineup] 20230004: 20 rows
[lineup] 20230005: 20 rows
[lineup] 20230006: 20 rows
[lineup] 20230007: 20 rows
[lineup] 20230008: 20 rows
[lineup] 20230009: 20 rows
[lineup] 20230010: 20 rows
[lineup] 20230011: 20 rows
[lineup] 20230012: 20 rows
[lineup] 20230015: 20 rows
[lineup] 20230016: 20 rows
[lineup] 20230017: 20 rows
[lineup] 20230021: 20 rows
[lineup] 20230022: 20 rows
[lineup] 20230025: 20 rows
[lineup] 20230026: 20 rows
[lineup] 20230027: 20 rows
[lineup] 20230028: 20 rows
[lineup] 20230029: 20 rows
[lineup] 20230030: 20 rows
[lineup] 20230031: 20 rows
[lineup] 20230032: 20 rows
[lineup] 20230033: 20 rows
[lineup] 20230034: 20 rows
[lineup] 20230035: 20 rows
[lineup] 20230036: 20 rows
[lineup] 20230037: 20 rows
[lineup] 20230038: 20 rows
[lineup] 20230039: 20 rows
[lineup] 20230040: 20 rows
[lineup] 20230041: 20 rows
[lineup] 20230042: 20 rows
[lineup] 20230043: 20 rows
[lineup] 20230044: 20 rows
[lineup] 20230045: 20 rows
[lineup] 20230047: 20 rows
[lineup] 20230048: 20 rows
[lineup] 20230049: 20 rows
[lineup] 20230050: 20 rows
[lineup] 20230051: 20 rows
[lineup] 20230052: 20 rows
[lineup] 20230053: 20 rows
[lineup] 20230054: 20 rows
[lineup] 20230055: 20 rows
[lineup] 20230056: 20 rows
[lineup] 20230057: 20 rows
[lineup] 20230058: 20 rows
[lineup] 20230059: 20 rows
[lineup] 20230060: 20 rows
[lineup] 20230061: 20 rows
[lineup] 20230062: 20 rows
[lineup] 20230063: 20 rows
[lineup] 20230064: 20 rows
[lineup] 20230065: 20 rows
[lineup] 20230066: 20 rows
[lineup] 20230067: 20 rows
[lineup] 20230068: 20 rows
[lineup] 20230069: 20 rows
[lineup] 20230070: 20 rows
[lineup] 20230071: 20 rows
[lineup] 20230072: 20 rows
[lineup] 20230073: 20 rows
[lineup] 20230074: 20 rows
[lineup] 20230075: 20 rows
[lineup] 20230076: 20 rows
[lineup] 20230077: 20 rows
[lineup] 20230078: 20 rows
[lineup] 20230079: 20 rows
[lineup] 20230080: 20 rows
[lineup] 20230081: 20 rows
[lineup] 20230082: 20 rows
[lineup] 20230083: 20 rows
[lineup] 20230084: 20 rows
[lineup] 20230085: 20 rows
[lineup] 20230086: 20 rows
[lineup] 20230087: 20 rows
[lineup] 20230088: 20 rows
[lineup] 20230089: 20 rows
[lineup] 20230090: 20 rows
[lineup] 20230091: 20 rows
[lineup] 20230092: 20 rows
[lineup] 20230093: 20 rows
[lineup] 20230094: 20 rows
[lineup] 20230095: 20 rows
[lineup] 20230096: 20 rows
[lineup] 20230097: 20 rows
[lineup] 20230098: 20 rows
[lineup] 20230099: 20 rows
[lineup] 20230100: 20 rows
[lineup] 20230101: 20 rows
[lineup] 20230102: 20 rows
[lineup] 20230104: 20 rows
[lineup] 20230106: 20 rows
[lineup] 20230107: 20 rows
[lineup] 20230108: 20 rows
[lineup] 20230109: 20 rows
[lineup] 20230110: 20 rows
[lineup] 20230111: 20 rows
[lineup] 20230112: 20 rows
[lineup] 20230113: 20 rows
[lineup] 20230114: 20 rows
[lineup] 20230115: 20 rows
[lineup] 20230116: 20 rows
[lineup] 20230117: 20 rows
[lineup] 20230118: 20 rows
[lineup] 20230119: 20 rows
[lineup] 20230120: 20 rows
[lineup] 20230121: 20 rows
[lineup] 20230122: 20 rows
[lineup] 20230123: 20 rows
[lineup] 20230124: 20 rows
[lineup] 20230126: 20 rows
[lineup] 20230127: 20 rows
[lineup] 20230128: 20 rows
[lineup] 20230129: 20 rows
[lineup] 20230130: 20 rows
[lineup] 20230131: 20 rows
[lineup] 20230132: 20 rows
[lineup] 20230133: 20 rows
[lineup] 20230134: 20 rows
[lineup] 20230135: 20 rows
[lineup] 20230136: 20 rows
[lineup] 20230137: 20 rows
[lineup] 20230138: 20 rows
[lineup] 20230139: 20 rows
[lineup] 20230140: 20 rows
[lineup] 20230141: 20 rows
[lineup] 20230142: 20 rows
[lineup] 20230143: 20 rows
[lineup] 20230147: 20 rows
[lineup] 20230152: 20 rows
[lineup] 20230156: 20 rows
[lineup] 20230157: 20 rows
[lineup] 20230158: 20 rows
[lineup] 20230161: 20 rows
[lineup] 20230162: 20 rows
[lineup] 20230163: 20 rows
[lineup] 20230164: 20 rows
[lineup] 20230165: 20 rows
[lineup] 20230166: 20 rows
[lineup] 20230167: 20 rows
[lineup] 20230168: 20 rows
[lineup] 20230169: 20 rows
[lineup] 20230170: 20 rows
[lineup] 20230171: 20 rows
[lineup] 20230172: 20 rows
[lineup] 20230173: 20 rows
[lineup] 20230174: 20 rows
[lineup] 20230175: 20 rows
[lineup] 20230176: 20 rows
[lineup] 20230177: 20 rows
[lineup] 20230178: 20 rows
[lineup] 20230179: 20 rows
[lineup] 20230180: 20 rows
[lineup] 20230181: 20 rows
[lineup] 20230182: 20 rows
[lineup] 20230183: 20 rows
[lineup] 20230184: 20 rows
[lineup] 20230185: 20 rows
[lineup] 20230186: 20 rows
[lineup] 20230187: 20 rows
[lineup] 20230188: 20 rows
[lineup] 20230189: 20 rows
[lineup] 20230190: 20 rows
[lineup] 20230191: 20 rows
[lineup] 20230192: 20 rows
[lineup] 20230193: 20 rows
[lineup] 20230194: 20 rows
[lineup] 20230195: 20 rows
[lineup] 20230196: 20 rows
[lineup] 20230197: 20 rows
[lineup] 20230198: 20 rows
[lineup] 20230199: 20 rows
[lineup] 20230200: 20 rows
[lineup] 20230201: 20 rows
[lineup] 20230202: 20 rows
[lineup] 20230203: 20 rows
[lineup] 20230206: 20 rows
[lineup] 20230207: 20 rows
[lineup] 20230208: 20 rows
[lineup] 20230209: 20 rows
[lineup] 20230210: 20 rows
[lineup] 20230211: 20 rows
[lineup] 20230212: 20 rows
[lineup] 20230213: 20 rows
[lineup] 20230214: 20 rows
[lineup] 20230215: 20 rows
[lineup] 20230216: 20 rows
[lineup] 20230217: 20 rows
[lineup] 20230218: 20 rows
[lineup] 20230219: 20 rows
[lineup] 20230220: 20 rows
[lineup] 20230221: 20 rows
[lineup] 20230222: 20 rows
[lineup] 20230223: 20 rows
[lineup] 20230224: 20 rows
[lineup] 20230225: 20 rows
[lineup] 20230226: 20 rows
[lineup] 20230227: 20 rows
[lineup] 20230228: 20 rows
[lineup] 20230229: 20 rows
[lineup] 20230230: 20 rows
[lineup] 20230231: 20 rows
[lineup] 20230232: 20 rows
[lineup] 20230233: 20 rows
[lineup] 20230234: 20 rows
[lineup] 20230235: 20 rows
[lineup] 20230236: 20 rows
[lineup] 20230237: 20 rows
[lineup] 20230238: 20 rows
[lineup] 20230239: 20 rows
[lineup] 20230240: 20 rows
[lineup] 20230242: 20 rows
[lineup] 20230243: 20 rows
[lineup] 20230244: 20 rows
[lineup] 20230245: 20 rows
[lineup] 20230247: 20 rows
[lineup] 20230248: 20 rows
[lineup] 20230249: 20 rows
[lineup] 20230251: 20 rows
[lineup] 20230252: 20 rows
[lineup] 20230253: 20 rows
[lineup] 20230254: 20 rows
[lineup] 20230255: 20 rows
[lineup] 20230256: 20 rows
[lineup] 20230257: 20 rows
[lineup] 20230258: 20 rows
[lineup] 20230259: 20 rows
[lineup] 20230260: 20 rows
[lineup] 20230261: 20 rows
[lineup] 20230262: 20 rows
[lineup] 20230263: 20 rows
[lineup] 20230266: 20 rows
[lineup] 20230267: 20 rows
[lineup] 20230268: 20 rows
[lineup] 20230269: 20 rows
[lineup] 20230270: 20 rows
[lineup] 20230271: 20 rows
[lineup] 20230272: 20 rows
[lineup] 20230273: 20 rows
[lineup] 20230274: 20 rows
[lineup] 20230275: 20 rows
[lineup] 20230280: 20 rows
[lineup] 20230276: 20 rows
[lineup] 20230277: 20 rows
[lineup] 20230278: 20 rows
[lineup] 20230279: 20 rows
[lineup] 20230281: 20 rows
[lineup] 20230282: 20 rows
[lineup] 20230284: 20 rows
[lineup] 20230283: 20 rows
[lineup] 20230285: 20 rows
[lineup] 20230286: 20 rows
[lineup] 20230287: 20 rows
[lineup] 20230288: 20 rows
[lineup] 20230289: 20 rows
[lineup] 20230290: 20 rows
[lineup] 20230291: 20 rows
[lineup] 20230292: 20 rows
[lineup] 20230293: 20 rows
[lineup] 20230294: 20 rows
[lineup] 20230295: 20 rows
[lineup] 20230296: 20 rows
[lineup] 20230297: 20 rows
[lineup] 20230298: 20 rows
[lineup] 20230299: 20 rows
[lineup] 20230300: 20 rows
[lineup] 20230301: 20 rows
[lineup] 20230302: 20 rows
[lineup] 20230303: 20 rows
[lineup] 20230304: 20 rows
[lineup] 20230305: 20 rows
[lineup] 20230306: 20 rows
[lineup] 20230307: 20 rows
[lineup] 20230308: 20 rows
[lineup] 20230309: 20 rows
[lineup] 20230310: 20 rows
[lineup] 20230311: 20 rows
[lineup] 20230312: 20 rows
[lineup] 20230313: 20 rows
[lineup] 20230314: 20 rows
[lineup] 20230315: 20 rows
[lineup] 20230316: 20 rows
[lineup] 20230317: 20 rows
[lineup] 20230318: 20 rows
[lineup] 20230319: 20 rows
[lineup] 20230320: 20 rows
[lineup] 20230321: 20 rows
[lineup] 20230322: 20 rows
[lineup] 20230323: 20 rows
[lineup] 20230324: 20 rows
[lineup] 20230325: 20 rows
[lineup] 20230326: 20 rows
[lineup] 20230327: 20 rows
[lineup] 20230328: 20 rows
[lineup] 20230329: 20 rows
[lineup] 20230330: 20 rows
[lineup] 20230331: 20 rows
[lineup] 20230332: 20 rows
[lineup] 20230333: 20 rows
[lineup] 20230334: 20 rows
[lineup] 20230335: 20 rows
[lineup] 20230336: 20 rows
[lineup] 20230337: 20 rows
[lineup] 20230338: 20 rows
[lineup] 20230339: 20 rows
[lineup] 20230340: 20 rows
[lineup] 20230341: 20 rows
[lineup] 20230342: 20 rows
[lineup] 20230343: 20 rows
[lineup] 20230344: 20 rows
[lineup] 20230345: 20 rows
[lineup] 20230346: 20 rows
[lineup] 20230347: 20 rows
[lineup] 20230348: 20 rows
[lineup] 20230349: 20 rows
[lineup] 20230350: 20 rows
[lineup] 20230351: 20 rows
[lineup] 20230352: 20 rows
[lineup] 20230353: 20 rows
[lineup] 20230354: 20 rows
[lineup] 20230355: 20 rows
[lineup] 20230356: 20 rows
[lineup] 20230357: 20 rows
[lineup] 20230358: 20 rows
[lineup] 20230359: 20 rows
[lineup] 20230360: 20 rows
[lineup] 20230361: 20 rows
[lineup] 20230362: 20 rows
[lineup] 20230363: 20 rows
[lineup] 20230364: 20 rows
[lineup] 20230365: 20 rows
[lineup] 20230367: 20 rows
[lineup] 20230366: 20 rows
[lineup] 20230368: 20 rows
[lineup] 20230371: 20 rows
[lineup] 20230372: 20 rows
[lineup] 20230373: 20 rows
[lineup] 20230375: 20 rows
[lineup] 20230376: 20 rows
[lineup] 20230377: 20 rows
[lineup] 20230378: 20 rows
[lineup] 20230379: 20 rows
[lineup] 20230380: 20 rows
[lineup] 20230386: 20 rows
[lineup] 20230387: 20 rows
[lineup] 20230388: 20 rows
[lineup] 20230389: 20 rows
[lineup] 20230390: 20 rows
[lineup] 20230391: 20 rows
[lineup] 20230392: 20 rows
[lineup] 20230393: 20 rows
[lineup] 20230394: 20 rows
[lineup] 20230395: 20 rows
[lineup] 20230397: 20 rows
[lineup] 20230396: 20 rows
[lineup] 20230398: 20 rows
[lineup] 20230399: 20 rows
[lineup] 20230400: 20 rows
[lineup] 20230402: 20 rows
[lineup] 20230405: 20 rows
[lineup] 20230406: 20 rows
[lineup] 20230407: 20 rows
[lineup] 20230408: 20 rows
[lineup] 20230409: 20 rows
[lineup] 20230410: 20 rows
[lineup] 20230411: 20 rows
[lineup] 20230412: 20 rows
[lineup] 20230413: 20 rows
[lineup] 20230414: 20 rows
[lineup] 20230415: 20 rows
[lineup] 20230416: 20 rows
[lineup] 20230417: 20 rows
[lineup] 20230421: 20 rows
[lineup] 20230422: 20 rows
[lineup] 20230423: 20 rows
[lineup] 20230424: 20 rows
[lineup] 20230425: 20 rows
[lineup] 20230426: 20 rows
[lineup] 20230427: 20 rows
[lineup] 20230428: 20 rows
[lineup] 20230429: 20 rows
[lineup] 20230430: 20 rows
[lineup] 20230432: 20 rows
[lineup] 20230436: 20 rows
[lineup] 20230437: 20 rows
[lineup] 20230438: 20 rows
[lineup] 20230439: 20 rows
[lineup] 20230440: 20 rows
[lineup] 20230442: 20 rows
[lineup] 20230444: 20 rows
[lineup] 20230445: 20 rows
[lineup] 20230446: 20 rows
[lineup] 20230447: 20 rows
[lineup] 20230448: 20 rows
[lineup] 20230449: 20 rows
[lineup] 20230450: 20 rows
[lineup] 20230452: 20 rows
[lineup] 20230453: 20 rows
[lineup] 20230455: 20 rows
[lineup] 20230458: 20 rows
[lineup] 20230460: 20 rows
[lineup] 20230461: 20 rows
[lineup] 20230462: 20 rows
[lineup] 20230463: 20 rows
[lineup] 20230464: 20 rows
[lineup] 20230465: 20 rows
[lineup] 20230466: 20 rows
[lineup] 20230467: 20 rows
[lineup] 20230468: 20 rows
[lineup] 20230469: 20 rows
[lineup] 20230470: 20 rows
[lineup] 20230471: 20 rows
[lineup] 20230472: 20 rows
[lineup] 20230473: 20 rows
[lineup] 20230474: 20 rows
[lineup] 20230475: 20 rows
[lineup] 20230476: 20 rows
[lineup] 20230477: 20 rows
[lineup] 20230478: 20 rows
[lineup] 20230479: 20 rows
[lineup] 20230480: 20 rows
[lineup] 20230481: 20 rows
[lineup] 20230482: 20 rows
[lineup] 20230483: 20 rows
[lineup] 20230484: 20 rows
[lineup] 20230485: 20 rows
[lineup] 20230487: 20 rows
[lineup] 20230486: 20 rows
[lineup] 20230488: 20 rows
[lineup] 20230489: 20 rows
[lineup] 20230490: 20 rows
[lineup] 20230491: 20 rows
[lineup] 20230492: 20 rows
[lineup] 20230493: 20 rows
[lineup] 20230494: 20 rows
[lineup] 20230495: 20 rows
[lineup] 20230496: 20 rows
[lineup] 20230497: 20 rows
[lineup] 20230498: 20 rows
[lineup] 20230499: 20 rows
[lineup] 20230500: 20 rows
[lineup] 20230501: 20 rows
[lineup] 20230502: 20 rows
[lineup] 20230503: 20 rows
[lineup] 20230504: 20 rows
[lineup] 20230505: 20 rows
[lineup] 20230506: 20 rows
[lineup] 20230507: 20 rows
[lineup] 20230508: 20 rows
[lineup] 20230509: 20 rows
[lineup] 20230510: 20 rows
[lineup] 20230511: 20 rows
[lineup] 20230512: 20 rows
[lineup] 20230513: 20 rows
[lineup] 20230514: 20 rows
[lineup] 20230515: 20 rows
[lineup] 20230516: 20 rows
[lineup] 20230517: 20 rows
[lineup] 20230518: 20 rows
[lineup] 20230519: 20 rows
[lineup] 20230520: 20 rows
[lineup] 20230521: 20 rows
[lineup] 20230522: 20 rows
[lineup] 20230523: 20 rows
[lineup] 20230524: 20 rows
[lineup] 20230526: 20 rows
[lineup] 20230527: 20 rows
[lineup] 20230528: 20 rows
[lineup] 20230529: 20 rows
[lineup] 20230530: 20 rows
[lineup] 20230532: 20 rows
[lineup] 20230536: 20 rows
[lineup] 20230537: 20 rows
[lineup] 20230538: 20 rows
[lineup] 20230539: 20 rows
[lineup] 20230540: 20 rows
[lineup] 20230541: 20 rows
[lineup] 20230542: 20 rows
[lineup] 20230543: 20 rows
[lineup] 20230544: 20 rows
[lineup] 20230545: 20 rows
[lineup] 20230546: 20 rows
[lineup] 20230547: 20 rows
[lineup] 20230548: 20 rows
[lineup] 20230549: 20 rows
[lineup] 20230550: 20 rows
[lineup] 20230551: 20 rows
[lineup] 20230552: 20 rows
[lineup] 20230553: 20 rows
[lineup] 20230554: 20 rows
[lineup] 20230555: 20 rows
[lineup] 20230556: 20 rows
[lineup] 20230557: 20 rows
[lineup] 20230558: 20 rows
[lineup] 20230559: 20 rows
[lineup] 20230560: 20 rows
[lineup] 20230561: 20 rows
[lineup] 20230562: 20 rows
[lineup] 20230563: 20 rows
[lineup] 20230564: 20 rows
[lineup] 20230565: 20 rows
[lineup] 20230567: 20 rows
[lineup] 20230568: 20 rows
[lineup] 20230569: 20 rows
[lineup] 20230570: 20 rows
[lineup] 20230572: 20 rows
[lineup] 20230571: 20 rows
[lineup] 20230573: 20 rows
[lineup] 20230574: 20 rows
[lineup] 20230575: 20 rows
[lineup] 20230577: 20 rows
[lineup] 20230576: 20 rows
[lineup] 20230578: 20 rows
[lineup] 20230579: 20 rows
[lineup] 20230580: 20 rows
[lineup] 20230582: 20 rows
[lineup] 20230584: 20 rows
[lineup] 20230585: 20 rows
[lineup] 20230587: 20 rows
[lineup] 20230591: 20 rows
[lineup] 20230592: 20 rows
[lineup] 20230593: 20 rows
[lineup] 20230594: 20 rows
[lineup] 20230596: 20 rows
[lineup] 20230597: 20 rows
[lineup] 20230598: 20 rows
[lineup] 20230599: 20 rows
[lineup] 20230600: 20 rows
[lineup] 20230601: 20 rows
[lineup] 20230602: 20 rows
[lineup] 20230603: 20 rows
[lineup] 20230604: 20 rows
[lineup] 20230605: 20 rows
[lineup] 20230606: 20 rows
[lineup] 20230607: 20 rows
[lineup] 20230608: 20 rows
[lineup] 20230609: 20 rows
[lineup] 20230610: 20 rows
[lineup] 20230617: 20 rows
[lineup] 20230621: 20 rows
[lineup] 20230622: 20 rows
[lineup] 20230623: 20 rows
[lineup] 20230624: 20 rows
[lineup] 20230625: 20 rows
[lineup] 20230626: 20 rows
[lineup] 20230627: 20 rows
[lineup] 20230628: 20 rows
[lineup] 20230629: 20 rows
[lineup] 20230631: 20 rows
[lineup] 20230632: 20 rows
[lineup] 20230633: 20 rows
[lineup] 20230634: 20 rows
[lineup] 20230636: 20 rows
[lineup] 20230637: 20 rows
[lineup] 20230638: 20 rows
[lineup] 20230639: 20 rows
[lineup] 20230640: 20 rows
[lineup] 20230987: 20 rows
[lineup] 20230642: 20 rows
[lineup] 20230643: 20 rows
[lineup] 20230644: 20 rows
[lineup] 20230645: 20 rows
[lineup] 20230646: 20 rows
[lineup] 20230647: 20 rows
[lineup] 20230648: 20 rows
[lineup] 20230649: 20 rows
[lineup] 20230650: 20 rows
[lineup] 20230651: 20 rows
[lineup] 20230652: 20 rows
[lineup] 20230653: 20 rows
[lineup] 20230654: 20 rows
[lineup] 20230655: 20 rows
[lineup] 20230656: 20 rows
[lineup] 20230657: 20 rows
[lineup] 20230658: 20 rows
[lineup] 20230659: 20 rows
[lineup] 20230660: 20 rows
[lineup] 20230863: 20 rows
[lineup] 20230864: 20 rows
[lineup] 20230865: 20 rows
[lineup] 20230866: 20 rows
[lineup] 20230661: 20 rows
[lineup] 20230662: 20 rows
[lineup] 20230663: 20 rows
[lineup] 20230664: 20 rows
[lineup] 20230665: 20 rows
[lineup] 20230666: 20 rows
[lineup] 20230667: 20 rows
[lineup] 20230668: 20 rows
[lineup] 20230669: 20 rows
[lineup] 20230670: 20 rows
[lineup] 20230867: 20 rows
[lineup] 20230868: 20 rows
[lineup] 20230869: 20 rows
[lineup] 20230870: 20 rows
[lineup] 20230873: 20 rows
[lineup] 20230874: 20 rows
[lineup] 20230875: 20 rows
[lineup] 20230879: 20 rows
[lineup] 20230880: 20 rows
[lineup] 20230881: 20 rows
[lineup] 20230882: 20 rows
[lineup] 20230887: 20 rows
[lineup] 20230888: 20 rows
[lineup] 20230889: 20 rows
[lineup] 20230890: 20 rows
[lineup] 20230891: 20 rows
[lineup] 20230892: 20 rows
[lineup] 20230998: 20 rows
[lineup] 20230999: 20 rows
[lineup] 20230893: 20 rows
[lineup] 20230894: 20 rows
[lineup] 20230895: 20 rows
[lineup] 20230979: 20 rows
[lineup] 20230997: 20 rows
[lineup] 20230901: 20 rows
[lineup] 20230902: 20 rows
[lineup] 20230903: 20 rows
[lineup] 20230904: 20 rows
[lineup] 20230905: 20 rows
[lineup] 20230906: 20 rows
[lineup] 20230907: 20 rows
[lineup] 20230908: 20 rows
[lineup] 20230909: 20 rows
[lineup] 20230910: 20 rows
[lineup] 20230911: 20 rows
[lineup] 20230912: 20 rows
[lineup] 20230913: 20 rows
[lineup] 20230914: 20 rows
[lineup] 20230915: 20 rows
[lineup] 20230916: 20 rows
[lineup] 20230917: 20 rows
[lineup] 20230918: 20 rows
[lineup] 20230922: 20 rows
[lineup] 20230923: 20 rows
[lineup] 20230924: 20 rows
[lineup] 20231006: 20 rows
[lineup] 20231007: 20 rows
[lineup] 20230925: 20 rows
[lineup] 20230926: 20 rows
[lineup] 20230927: 20 rows
[lineup] 20230928: 20 rows
[lineup] 20230929: 20 rows
[lineup] 20230930: 20 rows
[lineup] 20230931: 20 rows
[lineup] 20230932: 20 rows
[lineup] 20230933: 20 rows
[lineup] 20230934: 20 rows
[lineup] 20230935: 20 rows
[lineup] 20230936: 20 rows
[lineup] 20230937: 20 rows
[lineup] 20230938: 20 rows
[lineup] 20230939: 20 rows
[lineup] 20230940: 20 rows
[lineup] 20230941: 20 rows
[lineup] 20230942: 20 rows
[lineup] 20230943: 20 rows
lineup_df.shape = (13760, 13)
=== 4. collect_rosters (all dates) ===
roster date: 2023-03-22
[roster] 2023-03-22 team=1001: 0 rows
[roster] 2023-03-22 team=2002: 0 rows
[roster] 2023-03-22 team=3001: 0 rows
[roster] 2023-03-22 team=5002: 0 rows
[roster] 2023-03-22 team=6002: 0 rows
[roster] 2023-03-22 team=7002: 0 rows
[roster] 2023-03-22 team=9002: 0 rows
[roster] 2023-03-22 team=10001: 0 rows
[roster] 2023-03-22 team=11001: 0 rows
[roster] 2023-03-22 team=12001: 0 rows
roster date: 2023-03-23
[roster] 2023-03-23 team=1001: 0 rows
[roster] 2023-03-23 team=2002: 0 rows
[roster] 2023-03-23 team=3001: 0 rows
[roster] 2023-03-23 team=5002: 0 rows
[roster] 2023-03-23 team=6002: 0 rows
[roster] 2023-03-23 team=7002: 0 rows
[roster] 2023-03-23 team=9002: 0 rows
[roster] 2023-03-23 team=10001: 0 rows
[roster] 2023-03-23 team=11001: 0 rows
[roster] 2023-03-23 team=12001: 0 rows
roster date: 2023-03-24
[roster] 2023-03-24 team=1001: 0 rows
[roster] 2023-03-24 team=2002: 0 rows
[roster] 2023-03-24 team=3001: 0 rows
[roster] 2023-03-24 team=5002: 0 rows
[roster] 2023-03-24 team=6002: 0 rows
[roster] 2023-03-24 team=7002: 0 rows
[roster] 2023-03-24 team=9002: 0 rows
[roster] 2023-03-24 team=10001: 0 rows
[roster] 2023-03-24 team=11001: 0 rows
[roster] 2023-03-24 team=12001: 0 rows

C:\Users\User\AppData\Local\Temp\ipykernel_27996\728866721.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  hitter_out = pd.concat(hitter_list, ignore_index=True) if hitter_list else pd.DataFrame()
C:\Users\User\AppData\Local\Temp\ipykernel_27996\728866721.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pitcher_out = pd.concat(pitcher_list, ignore_index=True) if pitcher_list else pd.DataFrame()

=== 6. deduplicate season stats (last team + aggregate season) ===
season_hit_df.shape after dedup = (289, 15)
season_pit_df.shape after dedup = (280, 13)
=== 7. clean pitcher season stats ===
=== 8. prepare modeling tables ===
=== 9. build hitter team features ===
hitter_team_features.shape = (1376, 9)
=== 10. build starting pitcher features ===
sp_features.shape = (1376, 13)
sp_features rows per (game_id, team_code):
1    1376
Name: count, dtype: int64
=== 11. make game-level dataset ===
model_df.shape = (688, 70)
game_id duplication check:
count
1    688
Name: count, dtype: int64
Top NA counts in diff features:
sp_ERA_diff        30
sp_FIP_diff        30
sp_WHIP_diff       30
sp_K9_diff         30
sp_BB9_diff        30
sp_HR9_diff        30
sp_KBB_diff        30
lineup_OPS_diff     0
lineup_OBP_diff     0
lineup_SLG_diff     0
dtype: int64

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20230711,2023-03-23 04:00:00,2023,10001,1001,1003,14674,11404,김동혁,장필준,...,0.015810,0.014867,-0.59,-1.38480,-0.32,0.371,-1.467,-0.702,0.4166,0
1,20230712,2023-03-23 04:00:00,2023,12001,5002,2002,11318,14780,엄상백,강효종,...,0.000434,0.003559,-2.60,-1.42946,-0.55,1.358,-2.648,0.069,1.9023,0
2,20230716,2023-03-24 04:00:00,2023,10001,1001,1003,11379,14613,최원태,허윤동,...,0.024522,0.027390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,20230717,2023-03-24 04:00:00,2023,12001,5002,2002,15542,13102,슐서,김영준,...,0.007521,-0.003020,-21.38,-8.81277,-4.39,6.342,-24.463,1.087,2.5000,1
4,20230718,2023-03-24 04:00:00,2023,7002,6002,4001,10610,13061,장민재,곽빈,...,-0.009236,-0.007775,1.93,0.87580,0.25,0.465,-1.229,1.070,0.9451,0

(688, 70)

In [ ]:
model_df_23.to_csv("model_df_2023.csv", index=False)

In [ ]:
result_24 = build_modeling_data_pipeline(
    date_list=date_list_24,
    sleep_sec=0.2,
    verbose=True
)

model_df_24 = result_24["model_df"]

display(model_df_24.head())
print(model_df_24.shape)

=== 1. collect_games ===
[games] 2024-03-22: 0 rows
[games] 2024-03-23: 5 rows
[games] 2024-03-24: 5 rows
[games] 2024-03-25: 0 rows
[games] 2024-03-26: 5 rows
[games] 2024-03-27: 5 rows
[games] 2024-03-28: 5 rows
[games] 2024-03-29: 5 rows
[games] 2024-03-30: 5 rows
[games] 2024-03-31: 5 rows
[games] 2024-04-01: 0 rows
[games] 2024-04-02: 5 rows
[games] 2024-04-03: 5 rows
[games] 2024-04-04: 5 rows
[games] 2024-04-05: 5 rows
[games] 2024-04-06: 5 rows
[games] 2024-04-07: 5 rows
[games] 2024-04-08: 0 rows
[games] 2024-04-09: 5 rows
[games] 2024-04-10: 5 rows
[games] 2024-04-11: 5 rows
[games] 2024-04-12: 5 rows
[games] 2024-04-13: 5 rows
[games] 2024-04-14: 5 rows
[games] 2024-04-15: 0 rows
[games] 2024-04-16: 5 rows
[games] 2024-04-17: 5 rows
[games] 2024-04-18: 5 rows
[games] 2024-04-19: 5 rows
[games] 2024-04-20: 5 rows
[games] 2024-04-21: 8 rows
[games] 2024-04-22: 0 rows
[games] 2024-04-23: 5 rows
[games] 2024-04-24: 5 rows
[games] 2024-04-25: 5 rows
[games] 2024-04-26: 5 rows
[games] 2024-04-27: 5 rows
[games] 2024-04-28: 5 rows
[games] 2024-04-29: 0 rows
[games] 2024-04-30: 5 rows
[games] 2024-05-01: 5 rows
[games] 2024-05-02: 5 rows
[games] 2024-05-03: 5 rows
[games] 2024-05-04: 5 rows
[games] 2024-05-05: 5 rows
[games] 2024-05-06: 0 rows
[games] 2024-05-07: 5 rows
[games] 2024-05-08: 5 rows
[games] 2024-05-09: 5 rows
[games] 2024-05-10: 5 rows
[games] 2024-05-11: 5 rows
[games] 2024-05-12: 7 rows
[games] 2024-05-13: 0 rows
[games] 2024-05-14: 5 rows
[games] 2024-05-15: 5 rows
[games] 2024-05-16: 5 rows
[games] 2024-05-17: 5 rows
[games] 2024-05-18: 5 rows
[games] 2024-05-19: 5 rows
[games] 2024-05-20: 0 rows
[games] 2024-05-21: 5 rows
[games] 2024-05-22: 5 rows
[games] 2024-05-23: 5 rows
[games] 2024-05-24: 5 rows
[games] 2024-05-25: 5 rows
[games] 2024-05-26: 5 rows
[games] 2024-05-27: 0 rows
[games] 2024-05-28: 5 rows
[games] 2024-05-29: 5 rows
[games] 2024-05-30: 5 rows
[games] 2024-05-31: 5 rows
[games] 2024-06-01: 5 rows
[games] 2024-06-02: 5 rows
[games] 2024-06-03: 0 rows
[games] 2024-06-04: 5 rows
[games] 2024-06-05: 5 rows
[games] 2024-06-06: 5 rows
[games] 2024-06-07: 5 rows
[games] 2024-06-08: 5 rows
[games] 2024-06-09: 6 rows
[games] 2024-06-10: 0 rows
[games] 2024-06-11: 5 rows
[games] 2024-06-12: 5 rows
[games] 2024-06-13: 5 rows
[games] 2024-06-14: 5 rows
[games] 2024-06-15: 5 rows
[games] 2024-06-16: 5 rows
[games] 2024-06-17: 0 rows
[games] 2024-06-18: 5 rows
[games] 2024-06-19: 5 rows
[games] 2024-06-20: 5 rows
[games] 2024-06-21: 5 rows
[games] 2024-06-22: 5 rows
[games] 2024-06-23: 8 rows
[games] 2024-06-24: 0 rows
[games] 2024-06-25: 5 rows
[games] 2024-06-26: 5 rows
[games] 2024-06-27: 5 rows
[games] 2024-06-28: 5 rows
[games] 2024-06-29: 5 rows
[games] 2024-06-30: 9 rows
[games] 2024-07-01: 0 rows
[games] 2024-07-02: 5 rows
[games] 2024-07-03: 5 rows
[games] 2024-07-04: 5 rows
[games] 2024-07-05: 0 rows
[games] 2024-07-06: 0 rows
[games] 2024-07-07: 0 rows
[games] 2024-07-08: 0 rows
[games] 2024-07-09: 5 rows
[games] 2024-07-10: 5 rows
[games] 2024-07-11: 5 rows
[games] 2024-07-12: 5 rows
[games] 2024-07-13: 5 rows
[games] 2024-07-14: 5 rows
[games] 2024-07-15: 0 rows
[games] 2024-07-16: 5 rows
[games] 2024-07-17: 5 rows
[games] 2024-07-18: 5 rows
[games] 2024-07-19: 5 rows
[games] 2024-07-20: 5 rows
[games] 2024-07-21: 5 rows
[games] 2024-07-22: 0 rows
[games] 2024-07-23: 5 rows
[games] 2024-07-24: 5 rows
[games] 2024-07-25: 5 rows
[games] 2024-07-26: 5 rows
[games] 2024-07-27: 5 rows
[games] 2024-07-28: 5 rows
[games] 2024-07-29: 0 rows
[games] 2024-07-30: 5 rows
[games] 2024-07-31: 5 rows
[games] 2024-08-01: 5 rows
[games] 2024-08-02: 5 rows
[games] 2024-08-03: 5 rows
[games] 2024-08-04: 5 rows
[games] 2024-08-05: 0 rows
[games] 2024-08-06: 5 rows
[games] 2024-08-07: 5 rows
[games] 2024-08-08: 5 rows
[games] 2024-08-09: 5 rows
[games] 2024-08-10: 5 rows
[games] 2024-08-11: 5 rows
[games] 2024-08-12: 0 rows
[games] 2024-08-13: 5 rows
[games] 2024-08-14: 5 rows
[games] 2024-08-15: 5 rows
[games] 2024-08-16: 5 rows
[games] 2024-08-17: 5 rows
[games] 2024-08-18: 5 rows
[games] 2024-08-19: 0 rows
[games] 2024-08-20: 5 rows
[games] 2024-08-21: 5 rows
[games] 2024-08-22: 5 rows
[games] 2024-08-23: 5 rows
[games] 2024-08-24: 5 rows
[games] 2024-08-25: 5 rows
[games] 2024-08-26: 0 rows
[games] 2024-08-27: 5 rows
[games] 2024-08-28: 5 rows
[games] 2024-08-29: 5 rows
[games] 2024-08-30: 2 rows
[games] 2024-08-31: 4 rows
[games] 2024-09-01: 3 rows
[games] 2024-09-02: 0 rows
[games] 2024-09-03: 4 rows
[games] 2024-09-04: 5 rows
[games] 2024-09-05: 4 rows
[games] 2024-09-06: 4 rows
[games] 2024-09-07: 5 rows
[games] 2024-09-08: 4 rows
[games] 2024-09-09: 0 rows
[games] 2024-09-10: 4 rows
[games] 2024-09-11: 4 rows
[games] 2024-09-12: 4 rows
[games] 2024-09-13: 3 rows
[games] 2024-09-14: 5 rows
[games] 2024-09-15: 4 rows
[games] 2024-09-16: 2 rows
[games] 2024-09-17: 5 rows
[games] 2024-09-18: 3 rows
[games] 2024-09-19: 5 rows
[games] 2024-09-20: 3 rows
[games] 2024-09-21: 6 rows
[games] 2024-09-22: 5 rows
[games] 2024-09-23: 3 rows
[games] 2024-09-24: 5 rows
[games] 2024-09-25: 4 rows
[games] 2024-09-26: 3 rows
[games] 2024-09-27: 3 rows
[games] 2024-09-28: 5 rows
[games] 2024-09-29: 1 rows
[games] 2024-09-30: 2 rows
[games] 2024-10-01: 1 rows

C:\Users\User\AppData\Local\Temp\ipykernel_27996\1047996336.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()

=== 2. filter normal games ===
games_df.shape       = (798, 21)
games_df_clean.shape = (717, 21)
=== 3. collect_lineups ===
[lineup] 20240001: 20 rows
[lineup] 20240002: 20 rows
[lineup] 20240003: 20 rows
[lineup] 20240004: 20 rows
[lineup] 20240005: 20 rows
[lineup] 20240006: 20 rows
[lineup] 20240007: 20 rows
[lineup] 20240008: 20 rows
[lineup] 20240010: 20 rows
[lineup] 20240011: 20 rows
[lineup] 20240012: 20 rows
[lineup] 20240013: 20 rows
[lineup] 20240014: 20 rows
[lineup] 20240015: 20 rows
[lineup] 20240016: 20 rows
[lineup] 20240017: 20 rows
[lineup] 20240018: 20 rows
[lineup] 20240019: 20 rows
[lineup] 20240020: 20 rows
[lineup] 20240021: 20 rows
[lineup] 20240022: 20 rows
[lineup] 20240023: 20 rows
[lineup] 20240026: 20 rows
[lineup] 20240027: 20 rows
[lineup] 20240028: 20 rows
[lineup] 20240029: 20 rows
[lineup] 20240030: 20 rows
[lineup] 20240033: 20 rows
[lineup] 20240031: 20 rows
[lineup] 20240032: 20 rows
[lineup] 20240034: 20 rows
[lineup] 20240035: 20 rows
[lineup] 20240036: 20 rows
[lineup] 20240037: 20 rows
[lineup] 20240038: 20 rows
[lineup] 20240039: 20 rows
[lineup] 20240040: 20 rows
[lineup] 20240041: 20 rows
[lineup] 20240042: 20 rows
[lineup] 20240043: 20 rows
[lineup] 20240044: 20 rows
[lineup] 20240045: 20 rows
[lineup] 20240046: 20 rows
[lineup] 20240047: 20 rows
[lineup] 20240048: 20 rows
[lineup] 20240051: 20 rows
[lineup] 20240052: 20 rows
[lineup] 20240053: 20 rows
[lineup] 20240054: 20 rows
[lineup] 20240055: 20 rows
[lineup] 20240056: 20 rows
[lineup] 20240057: 20 rows
[lineup] 20240058: 20 rows
[lineup] 20240059: 20 rows
[lineup] 20240060: 20 rows
[lineup] 20240061: 20 rows
[lineup] 20240062: 20 rows
[lineup] 20240063: 20 rows
[lineup] 20240064: 20 rows
[lineup] 20240065: 20 rows
[lineup] 20240066: 20 rows
[lineup] 20240067: 20 rows
[lineup] 20240068: 20 rows
[lineup] 20240069: 20 rows
[lineup] 20240070: 20 rows
[lineup] 20240071: 20 rows
[lineup] 20240072: 20 rows
[lineup] 20240073: 20 rows
[lineup] 20240074: 20 rows
[lineup] 20240075: 20 rows
[lineup] 20240076: 20 rows
[lineup] 20240077: 20 rows
[lineup] 20240078: 20 rows
[lineup] 20240079: 20 rows
[lineup] 20240080: 20 rows
[lineup] 20240081: 20 rows
[lineup] 20240082: 20 rows
[lineup] 20240083: 20 rows
[lineup] 20240084: 20 rows
[lineup] 20240085: 20 rows
[lineup] 20240086: 20 rows
[lineup] 20240087: 20 rows
[lineup] 20240088: 20 rows
[lineup] 20240089: 20 rows
[lineup] 20240090: 20 rows
[lineup] 20240094: 20 rows
[lineup] 20240091: 20 rows
[lineup] 20240092: 20 rows
[lineup] 20240093: 20 rows
[lineup] 20240095: 20 rows
[lineup] 20240096: 20 rows
[lineup] 20240097: 20 rows
[lineup] 20240098: 20 rows
[lineup] 20240099: 20 rows
[lineup] 20240100: 20 rows
[lineup] 20240101: 20 rows
[lineup] 20240102: 20 rows
[lineup] 20240103: 20 rows
[lineup] 20240104: 20 rows
[lineup] 20240105: 20 rows
[lineup] 20240106: 20 rows
[lineup] 20240107: 20 rows
[lineup] 20240108: 20 rows
[lineup] 20240109: 20 rows
[lineup] 20240110: 20 rows
[lineup] 20240111: 20 rows
[lineup] 20240112: 20 rows
[lineup] 20240113: 20 rows
[lineup] 20240114: 20 rows
[lineup] 20240116: 20 rows
[lineup] 20240117: 20 rows
[lineup] 20240118: 20 rows
[lineup] 20240119: 20 rows
[lineup] 20240120: 20 rows
[lineup] 20240123: 20 rows
[lineup] 20240124: 20 rows
[lineup] 20240126: 20 rows
[lineup] 20240127: 20 rows
[lineup] 20240128: 20 rows
[lineup] 20240129: 20 rows
[lineup] 20240130: 20 rows
[lineup] 20241399: 20 rows
[lineup] 20241400: 20 rows
[lineup] 20241401: 20 rows
[lineup] 20240131: 20 rows
[lineup] 20240132: 20 rows
[lineup] 20240133: 20 rows
[lineup] 20240136: 20 rows
[lineup] 20240137: 20 rows
[lineup] 20240138: 20 rows
[lineup] 20240139: 20 rows
[lineup] 20240140: 20 rows
[lineup] 20240141: 20 rows
[lineup] 20240142: 20 rows
[lineup] 20240143: 20 rows
[lineup] 20240144: 20 rows
[lineup] 20240145: 20 rows
[lineup] 20240146: 20 rows
[lineup] 20240147: 20 rows
[lineup] 20240148: 20 rows
[lineup] 20240149: 20 rows
[lineup] 20240150: 20 rows
[lineup] 20240151: 20 rows
[lineup] 20240152: 20 rows
[lineup] 20240153: 20 rows
[lineup] 20240154: 20 rows
[lineup] 20240155: 20 rows
[lineup] 20240156: 20 rows
[lineup] 20240157: 20 rows
[lineup] 20240158: 20 rows
[lineup] 20240159: 20 rows
[lineup] 20240160: 20 rows
[lineup] 20240161: 20 rows
[lineup] 20240162: 20 rows
[lineup] 20240163: 20 rows
[lineup] 20240164: 20 rows
[lineup] 20240165: 20 rows
[lineup] 20240166: 20 rows
[lineup] 20240167: 20 rows
[lineup] 20240168: 20 rows
[lineup] 20240169: 20 rows
[lineup] 20240170: 20 rows
[lineup] 20240171: 20 rows
[lineup] 20240172: 20 rows
[lineup] 20240173: 20 rows
[lineup] 20240174: 20 rows
[lineup] 20240175: 20 rows
[lineup] 20240176: 20 rows
[lineup] 20240177: 20 rows
[lineup] 20240178: 20 rows
[lineup] 20240179: 20 rows
[lineup] 20240180: 20 rows
[lineup] 20240181: 20 rows
[lineup] 20240182: 20 rows
[lineup] 20240183: 20 rows
[lineup] 20240184: 20 rows
[lineup] 20240185: 20 rows
[lineup] 20240191: 20 rows
[lineup] 20240192: 20 rows
[lineup] 20240196: 20 rows
[lineup] 20240197: 20 rows
[lineup] 20240198: 20 rows
[lineup] 20240199: 20 rows
[lineup] 20240200: 20 rows
[lineup] 20240201: 20 rows
[lineup] 20240202: 20 rows
[lineup] 20240203: 20 rows
[lineup] 20240204: 20 rows
[lineup] 20240205: 20 rows
[lineup] 20240206: 20 rows
[lineup] 20240207: 20 rows
[lineup] 20240208: 20 rows
[lineup] 20240209: 20 rows
[lineup] 20240210: 20 rows
[lineup] 20240212: 20 rows
[lineup] 20240214: 20 rows
[lineup] 20240215: 20 rows
[lineup] 20240216: 20 rows
[lineup] 20240217: 20 rows
[lineup] 20240218: 20 rows
[lineup] 20240219: 20 rows
[lineup] 20240220: 20 rows
[lineup] 20241404: 20 rows
[lineup] 20241405: 20 rows
[lineup] 20240221: 20 rows
[lineup] 20240222: 20 rows
[lineup] 20240223: 20 rows
[lineup] 20240224: 20 rows
[lineup] 20240225: 20 rows
[lineup] 20240229: 20 rows
[lineup] 20240230: 20 rows
[lineup] 20240231: 20 rows
[lineup] 20240232: 20 rows
[lineup] 20240233: 20 rows
[lineup] 20240234: 20 rows
[lineup] 20240235: 20 rows
[lineup] 20240236: 20 rows
[lineup] 20240237: 20 rows
[lineup] 20240238: 20 rows
[lineup] 20240239: 20 rows
[lineup] 20240240: 20 rows
[lineup] 20240241: 20 rows
[lineup] 20240242: 20 rows
[lineup] 20240243: 20 rows
[lineup] 20240244: 20 rows
[lineup] 20240245: 20 rows
[lineup] 20240246: 20 rows
[lineup] 20240247: 20 rows
[lineup] 20240248: 20 rows
[lineup] 20240249: 20 rows
[lineup] 20240250: 20 rows
[lineup] 20240251: 20 rows
[lineup] 20240252: 20 rows
[lineup] 20240253: 20 rows
[lineup] 20240254: 20 rows
[lineup] 20240255: 20 rows
[lineup] 20240256: 20 rows
[lineup] 20240257: 20 rows
[lineup] 20240258: 20 rows
[lineup] 20240259: 20 rows
[lineup] 20240260: 20 rows
[lineup] 20240261: 20 rows
[lineup] 20240262: 20 rows
[lineup] 20240263: 20 rows
[lineup] 20240264: 20 rows
[lineup] 20240265: 20 rows
[lineup] 20240266: 20 rows
[lineup] 20240267: 20 rows
[lineup] 20240268: 20 rows
[lineup] 20240269: 20 rows
[lineup] 20240270: 20 rows
[lineup] 20240271: 20 rows
[lineup] 20240274: 20 rows
[lineup] 20240272: 20 rows
[lineup] 20240273: 20 rows
[lineup] 20240275: 20 rows
[lineup] 20240276: 20 rows
[lineup] 20240279: 20 rows
[lineup] 20240280: 20 rows
[lineup] 20240281: 20 rows
[lineup] 20240282: 20 rows
[lineup] 20240283: 20 rows
[lineup] 20240284: 20 rows
[lineup] 20240285: 20 rows
[lineup] 20240286: 20 rows
[lineup] 20240287: 20 rows
[lineup] 20240288: 20 rows
[lineup] 20240289: 20 rows
[lineup] 20240290: 20 rows
[lineup] 20240291: 20 rows
[lineup] 20240292: 20 rows
[lineup] 20240293: 20 rows
[lineup] 20240294: 20 rows
[lineup] 20240295: 20 rows
[lineup] 20240296: 20 rows
[lineup] 20240297: 20 rows
[lineup] 20240298: 20 rows
[lineup] 20240299: 20 rows
[lineup] 20240300: 20 rows
[lineup] 20240301: 20 rows
[lineup] 20240302: 20 rows
[lineup] 20240303: 20 rows
[lineup] 20240304: 20 rows
[lineup] 20240305: 20 rows
[lineup] 20240306: 20 rows
[lineup] 20240307: 20 rows
[lineup] 20240308: 20 rows
[lineup] 20240309: 20 rows
[lineup] 20240310: 20 rows
[lineup] 20240311: 20 rows
[lineup] 20240312: 20 rows
[lineup] 20240313: 20 rows
[lineup] 20240314: 20 rows
[lineup] 20240315: 20 rows
[lineup] 20240316: 20 rows
[lineup] 20240317: 20 rows
[lineup] 20240318: 20 rows
[lineup] 20240319: 20 rows
[lineup] 20240320: 20 rows
[lineup] 20240322: 20 rows
[lineup] 20240324: 20 rows
[lineup] 20240321: 20 rows
[lineup] 20240323: 20 rows
[lineup] 20240325: 20 rows
[lineup] 20240326: 20 rows
[lineup] 20240327: 20 rows
[lineup] 20240328: 20 rows
[lineup] 20240329: 20 rows
[lineup] 20240330: 20 rows
[lineup] 20240331: 20 rows
[lineup] 20240332: 20 rows
[lineup] 20240333: 20 rows
[lineup] 20240334: 20 rows
[lineup] 20240337: 20 rows
[lineup] 20241407: 20 rows
[lineup] 20240336: 20 rows
[lineup] 20240338: 20 rows
[lineup] 20240339: 20 rows
[lineup] 20240340: 20 rows
[lineup] 20240341: 20 rows
[lineup] 20240342: 20 rows
[lineup] 20240343: 20 rows
[lineup] 20240344: 20 rows
[lineup] 20240345: 20 rows
[lineup] 20240346: 20 rows
[lineup] 20240347: 20 rows
[lineup] 20240348: 20 rows
[lineup] 20240349: 20 rows
[lineup] 20240350: 20 rows
[lineup] 20240351: 20 rows
[lineup] 20240352: 20 rows
[lineup] 20240353: 20 rows
[lineup] 20240354: 20 rows
[lineup] 20240355: 20 rows
[lineup] 20240356: 20 rows
[lineup] 20240357: 20 rows
[lineup] 20240358: 20 rows
[lineup] 20240359: 20 rows
[lineup] 20240360: 20 rows
[lineup] 20240361: 20 rows
[lineup] 20240362: 20 rows
[lineup] 20240363: 20 rows
[lineup] 20240364: 20 rows
[lineup] 20240365: 20 rows
[lineup] 20240367: 20 rows
[lineup] 20240366: 20 rows
[lineup] 20240368: 20 rows
[lineup] 20240369: 20 rows
[lineup] 20240370: 20 rows
[lineup] 20240371: 20 rows
[lineup] 20240372: 20 rows
[lineup] 20240373: 20 rows
[lineup] 20240374: 20 rows
[lineup] 20240375: 20 rows
[lineup] 20240376: 20 rows
[lineup] 20240377: 20 rows
[lineup] 20240378: 20 rows
[lineup] 20240379: 20 rows
[lineup] 20240380: 20 rows
[lineup] 20240381: 20 rows
[lineup] 20240382: 20 rows
[lineup] 20240383: 20 rows
[lineup] 20240384: 20 rows
[lineup] 20240385: 20 rows
[lineup] 20240386: 20 rows
[lineup] 20240387: 20 rows
[lineup] 20240388: 20 rows
[lineup] 20240389: 20 rows
[lineup] 20240390: 20 rows
[lineup] 20240392: 20 rows
[lineup] 20240393: 20 rows
[lineup] 20240397: 20 rows
[lineup] 20241408: 20 rows
[lineup] 20241409: 20 rows
[lineup] 20241410: 20 rows
[lineup] 20240396: 20 rows
[lineup] 20240398: 20 rows
[lineup] 20240399: 20 rows
[lineup] 20240400: 20 rows
[lineup] 20240401: 20 rows
[lineup] 20240402: 20 rows
[lineup] 20240403: 20 rows
[lineup] 20240404: 20 rows
[lineup] 20240405: 20 rows
[lineup] 20240406: 20 rows
[lineup] 20240407: 20 rows
[lineup] 20240408: 20 rows
[lineup] 20240409: 20 rows
[lineup] 20240410: 20 rows
[lineup] 20240411: 20 rows
[lineup] 20240412: 20 rows
[lineup] 20240413: 20 rows
[lineup] 20240414: 20 rows
[lineup] 20240415: 20 rows
[lineup] 20240416: 20 rows
[lineup] 20240417: 20 rows
[lineup] 20240418: 20 rows
[lineup] 20240419: 20 rows
[lineup] 20240420: 20 rows
[lineup] 20241418: 20 rows
[lineup] 20240426: 20 rows
[lineup] 20240427: 20 rows
[lineup] 20240430: 20 rows
[lineup] 20240432: 20 rows
[lineup] 20240433: 20 rows
[lineup] 20240434: 20 rows
[lineup] 20240436: 20 rows
[lineup] 20240437: 20 rows
[lineup] 20240438: 20 rows
[lineup] 20240439: 20 rows
[lineup] 20240440: 20 rows
[lineup] 20240441: 20 rows
[lineup] 20240442: 20 rows
[lineup] 20240443: 20 rows
[lineup] 20240444: 20 rows
[lineup] 20240445: 20 rows
[lineup] 20240446: 20 rows
[lineup] 20240447: 20 rows
[lineup] 20240448: 20 rows
[lineup] 20240451: 20 rows
[lineup] 20240452: 20 rows
[lineup] 20240453: 20 rows
[lineup] 20240454: 20 rows
[lineup] 20240455: 20 rows
[lineup] 20240456: 20 rows
[lineup] 20240457: 20 rows
[lineup] 20240458: 20 rows
[lineup] 20240459: 20 rows
[lineup] 20240460: 20 rows
[lineup] 20240461: 20 rows
[lineup] 20240462: 20 rows
[lineup] 20240463: 20 rows
[lineup] 20240464: 20 rows
[lineup] 20240465: 20 rows
[lineup] 20240466: 20 rows
[lineup] 20240467: 20 rows
[lineup] 20240468: 20 rows
[lineup] 20240469: 20 rows
[lineup] 20240470: 20 rows
[lineup] 20240471: 20 rows
[lineup] 20240472: 20 rows
[lineup] 20240473: 20 rows
[lineup] 20240477: 20 rows
[lineup] 20240479: 20 rows
[lineup] 20240481: 20 rows
[lineup] 20240482: 20 rows
[lineup] 20240483: 20 rows
[lineup] 20240484: 20 rows
[lineup] 20240485: 20 rows
[lineup] 20240487: 20 rows
[lineup] 20240488: 20 rows
[lineup] 20240489: 20 rows
[lineup] 20240490: 20 rows
[lineup] 20240491: 20 rows
[lineup] 20240492: 20 rows
[lineup] 20240493: 20 rows
[lineup] 20240494: 20 rows
[lineup] 20240495: 20 rows
[lineup] 20240499: 20 rows
[lineup] 20240500: 20 rows
[lineup] 20240501: 20 rows
[lineup] 20240502: 20 rows
[lineup] 20240503: 20 rows
[lineup] 20240504: 20 rows
[lineup] 20240505: 20 rows
[lineup] 20240506: 20 rows
[lineup] 20240508: 20 rows
[lineup] 20240509: 20 rows
[lineup] 20240510: 20 rows
[lineup] 20240511: 20 rows
[lineup] 20240512: 20 rows
[lineup] 20240513: 20 rows
[lineup] 20240514: 20 rows
[lineup] 20240516: 20 rows
[lineup] 20240517: 20 rows
[lineup] 20240519: 20 rows
[lineup] 20240520: 20 rows
[lineup] 20240522: 20 rows
[lineup] 20240523: 20 rows
[lineup] 20240524: 20 rows
[lineup] 20240525: 20 rows
[lineup] 20240527: 20 rows
[lineup] 20240528: 20 rows
[lineup] 20240529: 20 rows
[lineup] 20240530: 20 rows
[lineup] 20240532: 20 rows
[lineup] 20240531: 20 rows
[lineup] 20240533: 20 rows
[lineup] 20240534: 20 rows
[lineup] 20240535: 20 rows
[lineup] 20240536: 20 rows
[lineup] 20240537: 20 rows
[lineup] 20240538: 20 rows
[lineup] 20240539: 20 rows
[lineup] 20240540: 20 rows
[lineup] 20240541: 20 rows
[lineup] 20240542: 20 rows
[lineup] 20240543: 20 rows
[lineup] 20240544: 20 rows
[lineup] 20240545: 20 rows
[lineup] 20240546: 20 rows
[lineup] 20240547: 20 rows
[lineup] 20240548: 20 rows
[lineup] 20240549: 20 rows
[lineup] 20240550: 20 rows
[lineup] 20240551: 20 rows
[lineup] 20240552: 20 rows
[lineup] 20240553: 20 rows
[lineup] 20240555: 20 rows
[lineup] 20240556: 20 rows
[lineup] 20240557: 20 rows
[lineup] 20240558: 20 rows
[lineup] 20240559: 20 rows
[lineup] 20240563: 20 rows
[lineup] 20240565: 20 rows
[lineup] 20240566: 20 rows
[lineup] 20240567: 20 rows
[lineup] 20240568: 20 rows
[lineup] 20240569: 20 rows
[lineup] 20240570: 20 rows
[lineup] 20240571: 20 rows
[lineup] 20240572: 20 rows
[lineup] 20240573: 20 rows
[lineup] 20240574: 20 rows
[lineup] 20240575: 20 rows
[lineup] 20240576: 20 rows
[lineup] 20240577: 20 rows
[lineup] 20240578: 20 rows
[lineup] 20240579: 20 rows
[lineup] 20240581: 20 rows
[lineup] 20240582: 20 rows
[lineup] 20240583: 20 rows
[lineup] 20240584: 20 rows
[lineup] 20240585: 20 rows
[lineup] 20240586: 20 rows
[lineup] 20240587: 20 rows
[lineup] 20240588: 20 rows
[lineup] 20240589: 20 rows
[lineup] 20240591: 20 rows
[lineup] 20240592: 20 rows
[lineup] 20240593: 20 rows
[lineup] 20240594: 20 rows
[lineup] 20240595: 20 rows
[lineup] 20240597: 20 rows
[lineup] 20240598: 20 rows
[lineup] 20240599: 20 rows
[lineup] 20240600: 20 rows
[lineup] 20240601: 20 rows
[lineup] 20240602: 20 rows
[lineup] 20240603: 20 rows
[lineup] 20240604: 20 rows
[lineup] 20240607: 20 rows
[lineup] 20240606: 20 rows
[lineup] 20240608: 20 rows
[lineup] 20240609: 20 rows
[lineup] 20240610: 20 rows
[lineup] 20240611: 20 rows
[lineup] 20240612: 20 rows
[lineup] 20240613: 20 rows
[lineup] 20240614: 20 rows
[lineup] 20240615: 20 rows
[lineup] 20240616: 20 rows
[lineup] 20240617: 20 rows
[lineup] 20240618: 20 rows
[lineup] 20240619: 20 rows
[lineup] 20240620: 20 rows
[lineup] 20240621: 20 rows
[lineup] 20240622: 20 rows
[lineup] 20240623: 20 rows
[lineup] 20240624: 20 rows
[lineup] 20240625: 20 rows
[lineup] 20240626: 20 rows
[lineup] 20240627: 20 rows
[lineup] 20240628: 20 rows
[lineup] 20240629: 20 rows
[lineup] 20240631: 20 rows
[lineup] 20240632: 20 rows
[lineup] 20240633: 20 rows
[lineup] 20240634: 20 rows
[lineup] 20240635: 20 rows
[lineup] 20240636: 20 rows
[lineup] 20240637: 20 rows
[lineup] 20240640: 20 rows
[lineup] 20240641: 20 rows
[lineup] 20240642: 20 rows
[lineup] 20240643: 20 rows
[lineup] 20240644: 20 rows
[lineup] 20240645: 20 rows
[lineup] 20240646: 20 rows
[lineup] 20240647: 20 rows
[lineup] 20240648: 20 rows
[lineup] 20240649: 20 rows
[lineup] 20240650: 20 rows
[lineup] 20240652: 20 rows
[lineup] 20240651: 20 rows
[lineup] 20240653: 20 rows
[lineup] 20240654: 20 rows
[lineup] 20240655: 20 rows
[lineup] 20240656: 20 rows
[lineup] 20240657: 20 rows
[lineup] 20240659: 20 rows
[lineup] 20240660: 20 rows
[lineup] 20240661: 20 rows
[lineup] 20240662: 20 rows
[lineup] 20240663: 20 rows
[lineup] 20240664: 20 rows
[lineup] 20240665: 20 rows
[lineup] 20240666: 20 rows
[lineup] 20240667: 20 rows
[lineup] 20240668: 20 rows
[lineup] 20240669: 20 rows
[lineup] 20240670: 20 rows
[lineup] 20241423: 20 rows
[lineup] 20241424: 20 rows
[lineup] 20241425: 20 rows
[lineup] 20241426: 20 rows
[lineup] 20241427: 20 rows
[lineup] 20241428: 20 rows
[lineup] 20241429: 20 rows
[lineup] 20241430: 20 rows
[lineup] 20241431: 20 rows
[lineup] 20241432: 20 rows
[lineup] 20241433: 20 rows
[lineup] 20241434: 20 rows
[lineup] 20241435: 20 rows
[lineup] 20241436: 20 rows
[lineup] 20241437: 20 rows
[lineup] 20241438: 20 rows
[lineup] 20241439: 20 rows
[lineup] 20241526: 20 rows
[lineup] 20241440: 20 rows
[lineup] 20241441: 20 rows
[lineup] 20241442: 20 rows
[lineup] 20241443: 20 rows
[lineup] 20241444: 20 rows
[lineup] 20241445: 20 rows
[lineup] 20241446: 20 rows
[lineup] 20241447: 20 rows
[lineup] 20241448: 20 rows
[lineup] 20241449: 20 rows
[lineup] 20241450: 20 rows
[lineup] 20241451: 20 rows
[lineup] 20241452: 20 rows
[lineup] 20241453: 20 rows
[lineup] 20241454: 20 rows
[lineup] 20241455: 20 rows
[lineup] 20241456: 20 rows
[lineup] 20241457: 20 rows
[lineup] 20241458: 20 rows
[lineup] 20241459: 20 rows
[lineup] 20241460: 20 rows
[lineup] 20241461: 20 rows
[lineup] 20241462: 20 rows
[lineup] 20241463: 20 rows
[lineup] 20241464: 20 rows
[lineup] 20241466: 20 rows
[lineup] 20241467: 20 rows
[lineup] 20241525: 20 rows
[lineup] 20241470: 20 rows
[lineup] 20241472: 20 rows
[lineup] 20241474: 20 rows
[lineup] 20241471: 20 rows
[lineup] 20241473: 20 rows
[lineup] 20241475: 20 rows
[lineup] 20241476: 20 rows
[lineup] 20241477: 20 rows
[lineup] 20241478: 20 rows
[lineup] 20241479: 20 rows
[lineup] 20241480: 20 rows
[lineup] 20241481: 20 rows
[lineup] 20241482: 20 rows
[lineup] 20241483: 20 rows
[lineup] 20241484: 20 rows
[lineup] 20241485: 20 rows
[lineup] 20241486: 20 rows
[lineup] 20241487: 20 rows
[lineup] 20241488: 20 rows
[lineup] 20241489: 20 rows
[lineup] 20241490: 20 rows
[lineup] 20241491: 20 rows
[lineup] 20241492: 20 rows
[lineup] 20241493: 20 rows
[lineup] 20241494: 20 rows
[lineup] 20241498: 20 rows
[lineup] 20241499: 20 rows
[lineup] 20241530: 20 rows
[lineup] 20241503: 20 rows
[lineup] 20241504: 20 rows
[lineup] 20241505: 20 rows
[lineup] 20241506: 20 rows
[lineup] 20241507: 20 rows
[lineup] 20241508: 20 rows
[lineup] 20241531: 20 rows
[lineup] 20241509: 20 rows
[lineup] 20241510: 20 rows
[lineup] 20241511: 20 rows
[lineup] 20241528: 20 rows
[lineup] 20241529: 20 rows
[lineup] 20241512: 20 rows
[lineup] 20241513: 20 rows
[lineup] 20241514: 20 rows
[lineup] 20241532: 20 rows
[lineup] 20241515: 20 rows
[lineup] 20241516: 20 rows
[lineup] 20241527: 20 rows
[lineup] 20241517: 20 rows
[lineup] 20241518: 20 rows
[lineup] 20241519: 20 rows
[lineup] 20241520: 20 rows
[lineup] 20241521: 20 rows
[lineup] 20241522: 20 rows
[lineup] 20241523: 20 rows
[lineup] 20241524: 20 rows
[lineup] 20241534: 20 rows
[lineup] 20241535: 20 rows
[lineup] 20241536: 20 rows
[lineup] 20241537: 20 rows
lineup_df.shape = (14340, 13)
=== 4. collect_rosters (all dates) ===
roster date: 2024-03-22
[roster] 2024-03-22 team=1001: 0 rows
[roster] 2024-03-22 team=2002: 0 rows
[roster] 2024-03-22 team=3001: 0 rows
[roster] 2024-03-22 team=5002: 1 rows
[roster] 2024-03-22 team=6002: 0 rows
[roster] 2024-03-22 team=7002: 0 rows
[roster] 2024-03-22 team=9002: 0 rows
[roster] 2024-03-22 team=10001: 0 rows
[roster] 2024-03-22 team=11001: 0 rows
[roster] 2024-03-22 team=12001: 0 rows
roster date: 2024-03-23

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20240001,2024-03-23 05:00:00,2024,5002,7002,1001,16023,10590,엔스,류현진,...,0.004785,0.019483,0.32,0.36553,-0.05,0.753,0.808,0.177,-0.9509,1
1,20240002,2024-03-23 05:00:00,2024,9002,3001,2001,10126,12295,김광현,윌커슨,...,0.013423,-0.007037,1.09,1.50684,0.24,0.896,2.811,0.507,-4.0756,1
2,20240003,2024-03-23 05:00:00,2024,12001,1001,2002,13942,15860,쿠에바스,코너,...,-0.004067,-0.004753,0.67,-0.18254,0.16,-0.892,0.813,-0.298,-1.3398,0
3,20240004,2024-03-23 05:00:00,2024,2002,10001,6001,16087,15531,크로우,후라도,...,0.082252,0.016166,0.21,-0.78058,0.17,1.604,1.165,-0.452,-1.6980,1
4,20240005,2024-03-23 05:00:00,2024,11001,6002,8005,16065,13941,하트,알칸타라,...,0.063836,0.027098,-2.07,-2.78789,-0.21,5.677,-0.900,-0.768,3.2440,1

(717, 70)

In [ ]:
model_df_24.to_csv("model_df_2024.csv", index=False)

In [ ]:
result_25 = build_modeling_data_pipeline(
    date_list=date_list_25,
    sleep_sec=0.2,
    verbose=True
)

model_df_25 = result_25["model_df"]

display(model_df_25.head())
print(model_df_25.shape)

=== 1. collect_games ===
[games] 2025-03-22: 5 rows
[games] 2025-03-23: 5 rows
[games] 2025-03-24: 0 rows
[games] 2025-03-25: 5 rows
[games] 2025-03-26: 5 rows
[games] 2025-03-27: 5 rows
[games] 2025-03-28: 5 rows
[games] 2025-03-29: 5 rows
[games] 2025-03-30: 5 rows
[games] 2025-03-31: 0 rows
[games] 2025-04-01: 5 rows
[games] 2025-04-02: 5 rows
[games] 2025-04-03: 5 rows
[games] 2025-04-04: 5 rows
[games] 2025-04-05: 5 rows
[games] 2025-04-06: 5 rows
[games] 2025-04-07: 0 rows
[games] 2025-04-08: 5 rows
[games] 2025-04-09: 5 rows
[games] 2025-04-10: 5 rows
[games] 2025-04-11: 5 rows
[games] 2025-04-12: 5 rows
[games] 2025-04-13: 5 rows
[games] 2025-04-14: 0 rows
[games] 2025-04-15: 5 rows
[games] 2025-04-16: 5 rows
[games] 2025-04-17: 5 rows
[games] 2025-04-18: 5 rows
[games] 2025-04-19: 5 rows
[games] 2025-04-20: 5 rows
[games] 2025-04-21: 0 rows
[games] 2025-04-22: 5 rows
[games] 2025-04-23: 5 rows
[games] 2025-04-24: 5 rows
[games] 2025-04-25: 5 rows
[games] 2025-04-26: 5 rows
[games] 2025-04-27: 5 rows
[games] 2025-04-28: 0 rows
[games] 2025-04-29: 5 rows
[games] 2025-04-30: 5 rows
[games] 2025-05-01: 5 rows
[games] 2025-05-02: 5 rows
[games] 2025-05-03: 5 rows
[games] 2025-05-04: 5 rows
[games] 2025-05-05: 5 rows
[games] 2025-05-06: 5 rows
[games] 2025-05-07: 5 rows
[games] 2025-05-08: 0 rows
[games] 2025-05-09: 5 rows
[games] 2025-05-10: 9 rows
[games] 2025-05-11: 8 rows
[games] 2025-05-12: 0 rows
[games] 2025-05-13: 5 rows
[games] 2025-05-14: 5 rows
[games] 2025-05-15: 5 rows
[games] 2025-05-16: 5 rows
[games] 2025-05-17: 10 rows
[games] 2025-05-18: 5 rows
[games] 2025-05-19: 0 rows
[games] 2025-05-20: 5 rows
[games] 2025-05-21: 5 rows
[games] 2025-05-22: 5 rows
[games] 2025-05-23: 5 rows
[games] 2025-05-24: 5 rows
[games] 2025-05-25: 5 rows
[games] 2025-05-26: 0 rows
[games] 2025-05-27: 5 rows
[games] 2025-05-28: 5 rows
[games] 2025-05-29: 5 rows
[games] 2025-05-30: 5 rows
[games] 2025-05-31: 5 rows
[games] 2025-06-01: 5 rows
[games] 2025-06-02: 0 rows
[games] 2025-06-03: 5 rows
[games] 2025-06-04: 5 rows
[games] 2025-06-05: 5 rows
[games] 2025-06-06: 5 rows
[games] 2025-06-07: 5 rows
[games] 2025-06-08: 5 rows
[games] 2025-06-09: 0 rows
[games] 2025-06-10: 5 rows
[games] 2025-06-11: 5 rows
[games] 2025-06-12: 5 rows
[games] 2025-06-13: 5 rows
[games] 2025-06-14: 5 rows
[games] 2025-06-15: 5 rows
[games] 2025-06-16: 0 rows
[games] 2025-06-17: 5 rows
[games] 2025-06-18: 5 rows
[games] 2025-06-19: 5 rows
[games] 2025-06-20: 5 rows
[games] 2025-06-21: 5 rows
[games] 2025-06-22: 5 rows
[games] 2025-06-23: 0 rows
[games] 2025-06-24: 5 rows
[games] 2025-06-25: 5 rows
[games] 2025-06-26: 5 rows
[games] 2025-06-27: 5 rows
[games] 2025-06-28: 5 rows
[games] 2025-06-29: 5 rows
[games] 2025-06-30: 0 rows
[games] 2025-07-01: 5 rows
[games] 2025-07-02: 5 rows
[games] 2025-07-03: 5 rows
[games] 2025-07-04: 5 rows
[games] 2025-07-05: 5 rows
[games] 2025-07-06: 5 rows
[games] 2025-07-07: 0 rows
[games] 2025-07-08: 5 rows
[games] 2025-07-09: 5 rows
[games] 2025-07-10: 5 rows
[games] 2025-07-11: 0 rows
[games] 2025-07-12: 0 rows
[games] 2025-07-13: 0 rows
[games] 2025-07-14: 0 rows
[games] 2025-07-15: 0 rows
[games] 2025-07-16: 0 rows
[games] 2025-07-17: 5 rows
[games] 2025-07-18: 5 rows
[games] 2025-07-19: 5 rows
[games] 2025-07-20: 5 rows
[games] 2025-07-21: 0 rows
[games] 2025-07-22: 5 rows
[games] 2025-07-23: 5 rows
[games] 2025-07-24: 5 rows
[games] 2025-07-25: 5 rows
[games] 2025-07-26: 5 rows
[games] 2025-07-27: 5 rows
[games] 2025-07-28: 0 rows
[games] 2025-07-29: 5 rows
[games] 2025-07-30: 5 rows
[games] 2025-07-31: 5 rows
[games] 2025-08-01: 5 rows
[games] 2025-08-02: 5 rows
[games] 2025-08-03: 5 rows
[games] 2025-08-04: 0 rows
[games] 2025-08-05: 5 rows
[games] 2025-08-06: 5 rows
[games] 2025-08-07: 5 rows
[games] 2025-08-08: 5 rows
[games] 2025-08-09: 5 rows
[games] 2025-08-10: 5 rows
[games] 2025-08-11: 0 rows
[games] 2025-08-12: 5 rows
[games] 2025-08-13: 5 rows
[games] 2025-08-14: 5 rows
[games] 2025-08-15: 5 rows
[games] 2025-08-16: 5 rows
[games] 2025-08-17: 5 rows
[games] 2025-08-18: 0 rows
[games] 2025-08-19: 5 rows
[games] 2025-08-20: 5 rows
[games] 2025-08-21: 5 rows
[games] 2025-08-22: 5 rows
[games] 2025-08-23: 5 rows
[games] 2025-08-24: 5 rows
[games] 2025-08-25: 0 rows
[games] 2025-08-26: 5 rows
[games] 2025-08-27: 5 rows
[games] 2025-08-28: 5 rows
[games] 2025-08-29: 5 rows
[games] 2025-08-30: 5 rows
[games] 2025-08-31: 5 rows
[games] 2025-09-01: 0 rows
[games] 2025-09-02: 4 rows
[games] 2025-09-03: 4 rows
[games] 2025-09-04: 4 rows
[games] 2025-09-05: 4 rows
[games] 2025-09-06: 4 rows
[games] 2025-09-07: 3 rows
[games] 2025-09-08: 0 rows
[games] 2025-09-09: 5 rows
[games] 2025-09-10: 4 rows
[games] 2025-09-11: 4 rows
[games] 2025-09-12: 3 rows
[games] 2025-09-13: 5 rows
[games] 2025-09-14: 4 rows
[games] 2025-09-15: 1 rows
[games] 2025-09-16: 5 rows
[games] 2025-09-17: 6 rows
[games] 2025-09-18: 5 rows
[games] 2025-09-19: 3 rows
[games] 2025-09-20: 5 rows
[games] 2025-09-21: 3 rows
[games] 2025-09-22: 1 rows
[games] 2025-09-23: 4 rows
[games] 2025-09-24: 4 rows
[games] 2025-09-25: 4 rows
[games] 2025-09-26: 4 rows
[games] 2025-09-27: 3 rows
[games] 2025-09-28: 4 rows
[games] 2025-09-29: 3 rows
[games] 2025-09-30: 5 rows
[games] 2025-10-01: 3 rows

C:\Users\User\AppData\Local\Temp\ipykernel_27996\1047996336.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(all_dfs, ignore_index=True).drop_duplicates()

=== 2. filter normal games ===
games_df.shape       = (798, 21)
games_df_clean.shape = (709, 21)
=== 3. collect_lineups ===
[lineup] 20250001: 20 rows
[lineup] 20250002: 20 rows
[lineup] 20250003: 20 rows
[lineup] 20250004: 20 rows
[lineup] 20250005: 20 rows
[lineup] 20250006: 20 rows
[lineup] 20250007: 20 rows
[lineup] 20250008: 20 rows
[lineup] 20250009: 20 rows
[lineup] 20250010: 20 rows
[lineup] 20250011: 20 rows
[lineup] 20250012: 20 rows
[lineup] 20250013: 20 rows
[lineup] 20250014: 20 rows
[lineup] 20250015: 20 rows
[lineup] 20250016: 20 rows
[lineup] 20250017: 20 rows
[lineup] 20250018: 20 rows
[lineup] 20250019: 20 rows
[lineup] 20250020: 20 rows
[lineup] 20250021: 20 rows
[lineup] 20250022: 20 rows
[lineup] 20250023: 20 rows
[lineup] 20250024: 20 rows
[lineup] 20250025: 20 rows
[lineup] 20250026: 20 rows
[lineup] 20250027: 20 rows
[lineup] 20250028: 20 rows
[lineup] 20250029: 20 rows
[lineup] 20250030: 20 rows
[lineup] 20250032: 20 rows
[lineup] 20250033: 20 rows
[lineup] 20250031: 20 rows
[lineup] 20250034: 20 rows
[lineup] 20250035: 20 rows
[lineup] 20250036: 20 rows
[lineup] 20250037: 20 rows
[lineup] 20250038: 20 rows
[lineup] 20250039: 20 rows
[lineup] 20250046: 20 rows
[lineup] 20250048: 20 rows
[lineup] 20250049: 20 rows
[lineup] 20250050: 20 rows
[lineup] 20250051: 20 rows
[lineup] 20250053: 20 rows
[lineup] 20250054: 20 rows
[lineup] 20250055: 20 rows
[lineup] 20250056: 20 rows
[lineup] 20250057: 20 rows
[lineup] 20250058: 20 rows
[lineup] 20250059: 20 rows
[lineup] 20250060: 20 rows
[lineup] 20250064: 20 rows
[lineup] 20250063: 20 rows
[lineup] 20250065: 20 rows
[lineup] 20250066: 20 rows
[lineup] 20250067: 20 rows
[lineup] 20250068: 20 rows
[lineup] 20250069: 20 rows
[lineup] 20250070: 20 rows
[lineup] 20250071: 20 rows
[lineup] 20250072: 20 rows
[lineup] 20250073: 20 rows
[lineup] 20250074: 20 rows
[lineup] 20250075: 20 rows
[lineup] 20250076: 20 rows
[lineup] 20250077: 20 rows
[lineup] 20250078: 20 rows
[lineup] 20250079: 20 rows
[lineup] 20250080: 20 rows
[lineup] 20250081: 20 rows
[lineup] 20250082: 20 rows
[lineup] 20250083: 20 rows
[lineup] 20250084: 20 rows
[lineup] 20250085: 20 rows
[lineup] 20250086: 20 rows
[lineup] 20250087: 20 rows
[lineup] 20250088: 20 rows
[lineup] 20250089: 20 rows
[lineup] 20250090: 20 rows
[lineup] 20250091: 20 rows
[lineup] 20250095: 20 rows
[lineup] 20250096: 20 rows
[lineup] 20250097: 20 rows
[lineup] 20250098: 20 rows
[lineup] 20250099: 20 rows
[lineup] 20250100: 20 rows
[lineup] 20250101: 20 rows
[lineup] 20250102: 20 rows
[lineup] 20250103: 20 rows
[lineup] 20250105: 20 rows
[lineup] 20250106: 20 rows
[lineup] 20250107: 20 rows
[lineup] 20250108: 20 rows
[lineup] 20250110: 20 rows
[lineup] 20250111: 20 rows
[lineup] 20250112: 20 rows
[lineup] 20250113: 20 rows
[lineup] 20250115: 20 rows
[lineup] 20250116: 20 rows
[lineup] 20250117: 20 rows
[lineup] 20250118: 20 rows
[lineup] 20250119: 20 rows
[lineup] 20250120: 20 rows
[lineup] 20250121: 20 rows
[lineup] 20250122: 20 rows
[lineup] 20250123: 20 rows
[lineup] 20250124: 20 rows
[lineup] 20250126: 20 rows
[lineup] 20250127: 20 rows
[lineup] 20250128: 20 rows
[lineup] 20250129: 20 rows
[lineup] 20250130: 20 rows
[lineup] 20250131: 20 rows
[lineup] 20250134: 20 rows
[lineup] 20250135: 20 rows
[lineup] 20250136: 20 rows
[lineup] 20250137: 20 rows
[lineup] 20250138: 20 rows
[lineup] 20250139: 20 rows
[lineup] 20250140: 20 rows
[lineup] 20250141: 20 rows
[lineup] 20250142: 20 rows
[lineup] 20250143: 20 rows
[lineup] 20250144: 20 rows
[lineup] 20250145: 20 rows
[lineup] 20250146: 20 rows
[lineup] 20250147: 20 rows
[lineup] 20250148: 20 rows
[lineup] 20250149: 20 rows
[lineup] 20250150: 20 rows
[lineup] 20250151: 20 rows
[lineup] 20250154: 20 rows
[lineup] 20250152: 20 rows
[lineup] 20250153: 20 rows
[lineup] 20250155: 20 rows
[lineup] 20250156: 20 rows
[lineup] 20250157: 20 rows
[lineup] 20250158: 20 rows
[lineup] 20250159: 20 rows
[lineup] 20250160: 20 rows
[lineup] 20250161: 20 rows
[lineup] 20250162: 20 rows
[lineup] 20250163: 20 rows
[lineup] 20250164: 20 rows
[lineup] 20250165: 20 rows
[lineup] 20250166: 20 rows
[lineup] 20250167: 20 rows
[lineup] 20250168: 20 rows
[lineup] 20250169: 20 rows
[lineup] 20250170: 20 rows
[lineup] 20250171: 20 rows
[lineup] 20250172: 20 rows
[lineup] 20250174: 20 rows
[lineup] 20250176: 20 rows
[lineup] 20250177: 20 rows
[lineup] 20250178: 20 rows
[lineup] 20250179: 20 rows
[lineup] 20250180: 20 rows
[lineup] 20250181: 20 rows
[lineup] 20250182: 20 rows
[lineup] 20250183: 20 rows
[lineup] 20250184: 20 rows
[lineup] 20250186: 20 rows
[lineup] 20250187: 20 rows
[lineup] 20250188: 20 rows
[lineup] 20250189: 20 rows
[lineup] 20250190: 20 rows
[lineup] 20250191: 20 rows
[lineup] 20250192: 20 rows
[lineup] 20250193: 20 rows
[lineup] 20250194: 20 rows
[lineup] 20250195: 20 rows
[lineup] 20250196: 20 rows
[lineup] 20250197: 20 rows
[lineup] 20250198: 20 rows
[lineup] 20250199: 20 rows
[lineup] 20250200: 20 rows
[lineup] 20250201: 20 rows
[lineup] 20250202: 20 rows
[lineup] 20250203: 20 rows
[lineup] 20250204: 20 rows
[lineup] 20250205: 20 rows
[lineup] 20250210: 20 rows
[lineup] 20250213: 20 rows
[lineup] 20250215: 20 rows
[lineup] 20250211: 20 rows
[lineup] 20250212: 20 rows
[lineup] 20250214: 20 rows
[lineup] 20250791: 20 rows
[lineup] 20250216: 20 rows
[lineup] 20250217: 20 rows
[lineup] 20250218: 20 rows
[lineup] 20250219: 20 rows
[lineup] 20250220: 20 rows
[lineup] 20250792: 20 rows
[lineup] 20250793: 20 rows
[lineup] 20250794: 20 rows
[lineup] 20250221: 20 rows
[lineup] 20250222: 20 rows
[lineup] 20250223: 20 rows
[lineup] 20250224: 20 rows
[lineup] 20250225: 20 rows
[lineup] 20250226: 20 rows
[lineup] 20250227: 20 rows
[lineup] 20250228: 20 rows
[lineup] 20250229: 20 rows
[lineup] 20250230: 20 rows
[lineup] 20250231: 20 rows
[lineup] 20250232: 20 rows
[lineup] 20250233: 20 rows
[lineup] 20250234: 20 rows
[lineup] 20250235: 20 rows
[lineup] 20250241: 20 rows
[lineup] 20250242: 20 rows
[lineup] 20250800: 20 rows
[lineup] 20250801: 20 rows
[lineup] 20250804: 20 rows
[lineup] 20250802: 20 rows
[lineup] 20250245: 20 rows
[lineup] 20250244: 20 rows
[lineup] 20250243: 20 rows
[lineup] 20250803: 20 rows
[lineup] 20250246: 20 rows
[lineup] 20250247: 20 rows
[lineup] 20250248: 20 rows
[lineup] 20250249: 20 rows
[lineup] 20250250: 20 rows
[lineup] 20250251: 20 rows
[lineup] 20250252: 20 rows
[lineup] 20250253: 20 rows
[lineup] 20250254: 20 rows
[lineup] 20250255: 20 rows
[lineup] 20250256: 20 rows
[lineup] 20250257: 20 rows
[lineup] 20250258: 20 rows
[lineup] 20250259: 20 rows
[lineup] 20250260: 20 rows
[lineup] 20250261: 20 rows
[lineup] 20250262: 20 rows
[lineup] 20250263: 20 rows
[lineup] 20250264: 20 rows
[lineup] 20250265: 20 rows
[lineup] 20250267: 20 rows
[lineup] 20250268: 20 rows
[lineup] 20250269: 20 rows
[lineup] 20250270: 20 rows
[lineup] 20250274: 20 rows
[lineup] 20250275: 20 rows
[lineup] 20250271: 20 rows
[lineup] 20250272: 20 rows
[lineup] 20250273: 20 rows
[lineup] 20250276: 20 rows
[lineup] 20250277: 20 rows
[lineup] 20250278: 20 rows
[lineup] 20250279: 20 rows
[lineup] 20250280: 20 rows
[lineup] 20250281: 20 rows
[lineup] 20250282: 20 rows
[lineup] 20250283: 20 rows
[lineup] 20250284: 20 rows
[lineup] 20250285: 20 rows
[lineup] 20250286: 20 rows
[lineup] 20250287: 20 rows
[lineup] 20250289: 20 rows
[lineup] 20250290: 20 rows
[lineup] 20250291: 20 rows
[lineup] 20250292: 20 rows
[lineup] 20250293: 20 rows
[lineup] 20250294: 20 rows
[lineup] 20250295: 20 rows
[lineup] 20250296: 20 rows
[lineup] 20250297: 20 rows
[lineup] 20250298: 20 rows
[lineup] 20250299: 20 rows
[lineup] 20250300: 20 rows
[lineup] 20250303: 20 rows
[lineup] 20250304: 20 rows
[lineup] 20250301: 20 rows
[lineup] 20250302: 20 rows
[lineup] 20250305: 20 rows
[lineup] 20250306: 20 rows
[lineup] 20250307: 20 rows
[lineup] 20250308: 20 rows
[lineup] 20250309: 20 rows
[lineup] 20250310: 20 rows
[lineup] 20250314: 20 rows
[lineup] 20250315: 20 rows
[lineup] 20250311: 20 rows
[lineup] 20250312: 20 rows
[lineup] 20250313: 20 rows
[lineup] 20250316: 20 rows
[lineup] 20250317: 20 rows
[lineup] 20250318: 20 rows
[lineup] 20250319: 20 rows
[lineup] 20250320: 20 rows
[lineup] 20250321: 20 rows
[lineup] 20250322: 20 rows
[lineup] 20250323: 20 rows
[lineup] 20250324: 20 rows
[lineup] 20250325: 20 rows
[lineup] 20250326: 20 rows
[lineup] 20250327: 20 rows
[lineup] 20250328: 20 rows
[lineup] 20250329: 20 rows
[lineup] 20250330: 20 rows
[lineup] 20250331: 20 rows
[lineup] 20250332: 20 rows
[lineup] 20250333: 20 rows
[lineup] 20250334: 20 rows
[lineup] 20250335: 20 rows
[lineup] 20250336: 20 rows
[lineup] 20250337: 20 rows
[lineup] 20250338: 20 rows
[lineup] 20250339: 20 rows
[lineup] 20250340: 20 rows
[lineup] 20250341: 20 rows
[lineup] 20250342: 20 rows
[lineup] 20250343: 20 rows
[lineup] 20250344: 20 rows
[lineup] 20250345: 20 rows
[lineup] 20250346: 20 rows
[lineup] 20250347: 20 rows
[lineup] 20250348: 20 rows
[lineup] 20250349: 20 rows
[lineup] 20250350: 20 rows
[lineup] 20250351: 20 rows
[lineup] 20250352: 20 rows
[lineup] 20250353: 20 rows
[lineup] 20250354: 20 rows
[lineup] 20250355: 20 rows
[lineup] 20250361: 20 rows
[lineup] 20250362: 20 rows
[lineup] 20250363: 20 rows
[lineup] 20250364: 20 rows
[lineup] 20250365: 20 rows
[lineup] 20250366: 20 rows
[lineup] 20250367: 20 rows
[lineup] 20250368: 20 rows
[lineup] 20250369: 20 rows
[lineup] 20250370: 20 rows
[lineup] 20250371: 20 rows
[lineup] 20250372: 20 rows
[lineup] 20250373: 20 rows
[lineup] 20250374: 20 rows
[lineup] 20250375: 20 rows
[lineup] 20250376: 20 rows
[lineup] 20250377: 20 rows
[lineup] 20250378: 20 rows
[lineup] 20250379: 20 rows
[lineup] 20250380: 20 rows
[lineup] 20250381: 20 rows
[lineup] 20250382: 20 rows
[lineup] 20250383: 20 rows
[lineup] 20250384: 20 rows
[lineup] 20250385: 20 rows
[lineup] 20250388: 20 rows
[lineup] 20250391: 20 rows
[lineup] 20250392: 20 rows
[lineup] 20250394: 20 rows
[lineup] 20250396: 20 rows
[lineup] 20250397: 20 rows
[lineup] 20250398: 20 rows
[lineup] 20250399: 20 rows
[lineup] 20250400: 20 rows
[lineup] 20250404: 20 rows
[lineup] 20250405: 20 rows
[lineup] 20250407: 20 rows
[lineup] 20250408: 20 rows
[lineup] 20250410: 20 rows
[lineup] 20250411: 20 rows
[lineup] 20250412: 20 rows
[lineup] 20250413: 20 rows
[lineup] 20250414: 20 rows
[lineup] 20250415: 20 rows
[lineup] 20250416: 20 rows
[lineup] 20250417: 20 rows
[lineup] 20250418: 20 rows
[lineup] 20250419: 20 rows
[lineup] 20250420: 20 rows
[lineup] 20250421: 20 rows
[lineup] 20250422: 20 rows
[lineup] 20250423: 20 rows
[lineup] 20250424: 20 rows
[lineup] 20250425: 20 rows
[lineup] 20250426: 20 rows
[lineup] 20250427: 20 rows
[lineup] 20250428: 20 rows
[lineup] 20250429: 20 rows
[lineup] 20250430: 20 rows
[lineup] 20250431: 20 rows
[lineup] 20250432: 20 rows
[lineup] 20250433: 20 rows
[lineup] 20250434: 20 rows
[lineup] 20250435: 20 rows
[lineup] 20250436: 20 rows
[lineup] 20250437: 20 rows
[lineup] 20250438: 20 rows
[lineup] 20250439: 20 rows
[lineup] 20250440: 20 rows
[lineup] 20250441: 20 rows
[lineup] 20250442: 20 rows
[lineup] 20250443: 20 rows
[lineup] 20250444: 20 rows
[lineup] 20250445: 20 rows
[lineup] 20250446: 20 rows
[lineup] 20250447: 20 rows
[lineup] 20250448: 20 rows
[lineup] 20250449: 20 rows
[lineup] 20250450: 20 rows
[lineup] 20250451: 20 rows
[lineup] 20250452: 20 rows
[lineup] 20250453: 20 rows
[lineup] 20250454: 20 rows
[lineup] 20250455: 20 rows
[lineup] 20250456: 20 rows
[lineup] 20250457: 20 rows
[lineup] 20250458: 20 rows
[lineup] 20250459: 20 rows
[lineup] 20250460: 20 rows
[lineup] 20250461: 20 rows
[lineup] 20250462: 20 rows
[lineup] 20250463: 20 rows
[lineup] 20250464: 20 rows
[lineup] 20250465: 20 rows
[lineup] 20250466: 20 rows
[lineup] 20250467: 20 rows
[lineup] 20250468: 20 rows
[lineup] 20250469: 20 rows
[lineup] 20250470: 20 rows
[lineup] 20250471: 20 rows
[lineup] 20250472: 20 rows
[lineup] 20250473: 20 rows
[lineup] 20250474: 20 rows
[lineup] 20250475: 20 rows
[lineup] 20250481: 20 rows
[lineup] 20250484: 20 rows
[lineup] 20250486: 20 rows
[lineup] 20250487: 20 rows
[lineup] 20250491: 20 rows
[lineup] 20250492: 20 rows
[lineup] 20250493: 20 rows
[lineup] 20250494: 20 rows
[lineup] 20250495: 20 rows
[lineup] 20250496: 20 rows
[lineup] 20250497: 20 rows
[lineup] 20250498: 20 rows
[lineup] 20250499: 20 rows
[lineup] 20250500: 20 rows
[lineup] 20250501: 20 rows
[lineup] 20250502: 20 rows
[lineup] 20250503: 20 rows
[lineup] 20250504: 20 rows
[lineup] 20250505: 20 rows
[lineup] 20250506: 20 rows
[lineup] 20250507: 20 rows
[lineup] 20250508: 20 rows
[lineup] 20250509: 20 rows
[lineup] 20250510: 20 rows
[lineup] 20250511: 20 rows
[lineup] 20250512: 20 rows
[lineup] 20250513: 20 rows
[lineup] 20250514: 20 rows
[lineup] 20250515: 20 rows
[lineup] 20250516: 20 rows
[lineup] 20250517: 20 rows
[lineup] 20250518: 20 rows
[lineup] 20250519: 20 rows
[lineup] 20250520: 20 rows
[lineup] 20250521: 20 rows
[lineup] 20250522: 20 rows
[lineup] 20250523: 20 rows
[lineup] 20250524: 20 rows
[lineup] 20250525: 20 rows
[lineup] 20250526: 20 rows
[lineup] 20250527: 20 rows
[lineup] 20250528: 20 rows
[lineup] 20250529: 20 rows
[lineup] 20250530: 20 rows
[lineup] 20250531: 20 rows
[lineup] 20250532: 20 rows
[lineup] 20250533: 20 rows
[lineup] 20250534: 20 rows
[lineup] 20250535: 20 rows
[lineup] 20250536: 20 rows
[lineup] 20250537: 20 rows
[lineup] 20250538: 20 rows
[lineup] 20250539: 20 rows
[lineup] 20250540: 20 rows
[lineup] 20250541: 20 rows
[lineup] 20250542: 20 rows
[lineup] 20250543: 20 rows
[lineup] 20250544: 20 rows
[lineup] 20250545: 20 rows
[lineup] 20250546: 20 rows
[lineup] 20250547: 20 rows
[lineup] 20250548: 20 rows
[lineup] 20250550: 20 rows
[lineup] 20250551: 20 rows
[lineup] 20250552: 20 rows
[lineup] 20250553: 20 rows
[lineup] 20250556: 20 rows
[lineup] 20250557: 20 rows
[lineup] 20250558: 20 rows
[lineup] 20250559: 20 rows
[lineup] 20250560: 20 rows
[lineup] 20250561: 20 rows
[lineup] 20250562: 20 rows
[lineup] 20250563: 20 rows
[lineup] 20250564: 20 rows
[lineup] 20250565: 20 rows
[lineup] 20250566: 20 rows
[lineup] 20250567: 20 rows
[lineup] 20250568: 20 rows
[lineup] 20250569: 20 rows
[lineup] 20250570: 20 rows
[lineup] 20250571: 20 rows
[lineup] 20250572: 20 rows
[lineup] 20250573: 20 rows
[lineup] 20250574: 20 rows
[lineup] 20250575: 20 rows
[lineup] 20250576: 20 rows
[lineup] 20250578: 20 rows
[lineup] 20250580: 20 rows
[lineup] 20250581: 20 rows
[lineup] 20250582: 20 rows
[lineup] 20250583: 20 rows
[lineup] 20250584: 20 rows
[lineup] 20250585: 20 rows
[lineup] 20250586: 20 rows
[lineup] 20250587: 20 rows
[lineup] 20250588: 20 rows
[lineup] 20250589: 20 rows
[lineup] 20250590: 20 rows
[lineup] 20250593: 20 rows
[lineup] 20250595: 20 rows
[lineup] 20250596: 20 rows
[lineup] 20250597: 20 rows
[lineup] 20250598: 20 rows
[lineup] 20250600: 20 rows
[lineup] 20250601: 20 rows
[lineup] 20250602: 20 rows
[lineup] 20250603: 20 rows
[lineup] 20250604: 20 rows
[lineup] 20250605: 20 rows
[lineup] 20250606: 20 rows
[lineup] 20250607: 20 rows
[lineup] 20250608: 20 rows
[lineup] 20250609: 20 rows
[lineup] 20250610: 20 rows
[lineup] 20250611: 20 rows
[lineup] 20250612: 20 rows
[lineup] 20250613: 20 rows
[lineup] 20250614: 20 rows
[lineup] 20250615: 20 rows
[lineup] 20250616: 20 rows
[lineup] 20250617: 20 rows
[lineup] 20250618: 20 rows
[lineup] 20250619: 20 rows
[lineup] 20250620: 20 rows
[lineup] 20250621: 20 rows
[lineup] 20250622: 20 rows
[lineup] 20250623: 20 rows
[lineup] 20250624: 20 rows
[lineup] 20250625: 20 rows
[lineup] 20250626: 20 rows
[lineup] 20250627: 20 rows
[lineup] 20250628: 20 rows
[lineup] 20250629: 20 rows
[lineup] 20250630: 20 rows
[lineup] 20250631: 20 rows
[lineup] 20250632: 20 rows
[lineup] 20250633: 20 rows
[lineup] 20250634: 20 rows
[lineup] 20250635: 20 rows
[lineup] 20250636: 20 rows
[lineup] 20250637: 20 rows
[lineup] 20250638: 20 rows
[lineup] 20250639: 20 rows
[lineup] 20250640: 20 rows
[lineup] 20250641: 20 rows
[lineup] 20250642: 20 rows
[lineup] 20250643: 20 rows
[lineup] 20250644: 20 rows
[lineup] 20250645: 20 rows
[lineup] 20250646: 20 rows
[lineup] 20250647: 20 rows
[lineup] 20250648: 20 rows
[lineup] 20250649: 20 rows
[lineup] 20250650: 20 rows
[lineup] 20250651: 20 rows
[lineup] 20250652: 20 rows
[lineup] 20250653: 20 rows
[lineup] 20250654: 20 rows
[lineup] 20250655: 20 rows
[lineup] 20250656: 20 rows
[lineup] 20250657: 20 rows
[lineup] 20250658: 20 rows
[lineup] 20250659: 20 rows
[lineup] 20250660: 20 rows
[lineup] 20250661: 20 rows
[lineup] 20250662: 20 rows
[lineup] 20250663: 20 rows
[lineup] 20250664: 20 rows
[lineup] 20250665: 20 rows
[lineup] 20250666: 20 rows
[lineup] 20250667: 20 rows
[lineup] 20250668: 20 rows
[lineup] 20250669: 20 rows
[lineup] 20250670: 20 rows
[lineup] 20250671: 20 rows
[lineup] 20250672: 20 rows
[lineup] 20250673: 20 rows
[lineup] 20250674: 20 rows
[lineup] 20250675: 20 rows
[lineup] 20250859: 20 rows
[lineup] 20250860: 20 rows
[lineup] 20250861: 20 rows
[lineup] 20250862: 20 rows
[lineup] 20250863: 20 rows
[lineup] 20250864: 20 rows
[lineup] 20250865: 20 rows
[lineup] 20250866: 20 rows
[lineup] 20250867: 20 rows
[lineup] 20250870: 20 rows
[lineup] 20250871: 20 rows
[lineup] 20250872: 20 rows
[lineup] 20250874: 20 rows
[lineup] 20250877: 20 rows
[lineup] 20250878: 20 rows
[lineup] 20250879: 20 rows
[lineup] 20250880: 20 rows
[lineup] 20250881: 20 rows
[lineup] 20250882: 20 rows
[lineup] 20250883: 20 rows
[lineup] 20250885: 20 rows
[lineup] 20250887: 20 rows
[lineup] 20250888: 20 rows
[lineup] 20250889: 20 rows
[lineup] 20250970: 20 rows
[lineup] 20250890: 20 rows
[lineup] 20250891: 20 rows
[lineup] 20250892: 20 rows
[lineup] 20250893: 20 rows
[lineup] 20250896: 20 rows
[lineup] 20250897: 20 rows
[lineup] 20250898: 20 rows
[lineup] 20250899: 20 rows
[lineup] 20250900: 20 rows
[lineup] 20250901: 20 rows
[lineup] 20250902: 20 rows
[lineup] 20250903: 20 rows
[lineup] 20250904: 20 rows
[lineup] 20250905: 20 rows
[lineup] 20250972: 20 rows
[lineup] 20250906: 20 rows
[lineup] 20250907: 20 rows
[lineup] 20250908: 20 rows
[lineup] 20250909: 20 rows
[lineup] 20250910: 20 rows
[lineup] 20250911: 20 rows
[lineup] 20250914: 20 rows
[lineup] 20250915: 20 rows
[lineup] 20250973: 20 rows
[lineup] 20250916: 20 rows
[lineup] 20250917: 20 rows
[lineup] 20250918: 20 rows
[lineup] 20250919: 20 rows
[lineup] 20250922: 20 rows
[lineup] 20250923: 20 rows
[lineup] 20250924: 20 rows
[lineup] 20250925: 20 rows
[lineup] 20250926: 20 rows
[lineup] 20250927: 20 rows
[lineup] 20250928: 20 rows
[lineup] 20250929: 20 rows
[lineup] 20250930: 20 rows
[lineup] 20250980: 20 rows
[lineup] 20250931: 20 rows
[lineup] 20250932: 20 rows
[lineup] 20250933: 20 rows
[lineup] 20250934: 20 rows
[lineup] 20250935: 20 rows
[lineup] 20250937: 20 rows
[lineup] 20250974: 20 rows
[lineup] 20250938: 20 rows
[lineup] 20250939: 20 rows
[lineup] 20250940: 20 rows
[lineup] 20250966: 20 rows
[lineup] 20250941: 20 rows
[lineup] 20250942: 20 rows
[lineup] 20250943: 20 rows
[lineup] 20250944: 20 rows
[lineup] 20250945: 20 rows
[lineup] 20250946: 20 rows
[lineup] 20250947: 20 rows
[lineup] 20250948: 20 rows
[lineup] 20250949: 20 rows
[lineup] 20250969: 20 rows
[lineup] 20250990: 20 rows
[lineup] 20250991: 20 rows
[lineup] 20250952: 20 rows
[lineup] 20250953: 20 rows
[lineup] 20250954: 20 rows
[lineup] 20250955: 20 rows
[lineup] 20250956: 20 rows
[lineup] 20250981: 20 rows
[lineup] 20250982: 20 rows
[lineup] 20250983: 20 rows
lineup_df.shape = (14180, 13)
=== 4. collect_rosters (all dates) ===
roster date: 2025-03-22
[roster] 2025-03-22 team=1001: 28 rows
[roster] 2025-03-22 team=2002: 28 rows
[roster] 2025-03-22 team=3001: 28 rows
[roster] 2025-03-22 team=5002: 28 rows
[roster] 2025-03-22 team=6002: 28 rows
[roster] 2025-03-22 team=7002: 28 rows
[roster] 2025-03-22 team=9002: 28 rows
[roster] 2025-03-22 team=10001: 28 rows
[roster] 2025-03-22 team=11001: 28 rows
[roster] 2025-03-22 team=12001: 28 rows
roster date: 2025-03-23
[roster] 2025-03-23 team=1001: 28 rows
[roster] 2025-03-23 team=2002: 27 rows
[roster] 2025-03-23 team=3001: 28 rows
[roster] 2025-03-23 team=5002: 28 rows
[roster] 2025-03-23 team=6002: 28 rows

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20250001,2025-03-22 05:00:00,2025,5002,3001,1001,16286,15011,치리노스,반즈,...,0.071262,0.007907,-2.01,-1.07874,-0.22,-0.523,-1.519,-0.534,1.5703,1
1,20250002,2025-03-22 05:00:00,2025,9002,6002,2001,16146,16298,앤더슨,콜어빈,...,-0.046600,0.001351,-2.23,-2.22231,-0.53,4.882,-2.241,0.122,3.1836,1
2,20250003,2025-03-22 05:00:00,2025,1001,10001,7003,15531,16339,후라도,로젠버그,...,0.081965,0.026285,-0.63,0.50802,-0.09,-3.082,-1.345,0.178,0.7444,1
3,20250004,2025-03-22 05:00:00,2025,12001,7002,2002,16138,16313,헤이수스,폰세,...,-0.068278,-0.004885,2.07,1.72832,0.39,-3.481,0.378,0.437,-2.3963,0
4,20250005,2025-03-22 05:00:00,2025,2002,11001,6001,16088,16350,네일,로건,...,-0.010911,-0.005554,-2.28,-1.25967,-0.36,0.574,-1.241,-0.607,1.4834,1

(709, 70)

In [ ]:
model_df_25.to_csv("model_df_2025.csv", index=False)

In [ ]:
date_list_23

['2023-03-22',
 '2023-03-23',
 '2023-03-24',
 '2023-03-25',
 '2023-03-26',
 '2023-03-27',
 '2023-03-28',
 '2023-03-29',
 '2023-03-30',
 '2023-03-31',
 '2023-04-01',
 '2023-04-02',
 '2023-04-03',
 '2023-04-04',
 '2023-04-05',
 '2023-04-06',
 '2023-04-07',
 '2023-04-08',
 '2023-04-09',
 '2023-04-10',
 '2023-04-11',
 '2023-04-12',
 '2023-04-13',
 '2023-04-14',
 '2023-04-15',
 '2023-04-16',
 '2023-04-17',
 '2023-04-18',
 '2023-04-19',
 '2023-04-20',
 '2023-04-21',
 '2023-04-22',
 '2023-04-23',
 '2023-04-24',
 '2023-04-25',
 '2023-04-26',
 '2023-04-27',
 '2023-04-28',
 '2023-04-29',
 '2023-04-30',
 '2023-05-01',
 '2023-05-02',
 '2023-05-03',
 '2023-05-04',
 '2023-05-05',
 '2023-05-06',
 '2023-05-07',
 '2023-05-08',
 '2023-05-09',
 '2023-05-10',
 '2023-05-11',
 '2023-05-12',
 '2023-05-13',
 '2023-05-14',
 '2023-05-15',
 '2023-05-16',
 '2023-05-17',
 '2023-05-18',
 '2023-05-19',
 '2023-05-20',
 '2023-05-21',
 '2023-05-22',
 '2023-05-23',
 '2023-05-24',
 '2023-05-25',
 '2023-05-26',
 '2023-05-27',
 '2023-05-28',
 '2023-05-29',
 '2023-05-30',
 '2023-05-31',
 '2023-06-01',
 '2023-06-02',
 '2023-06-03',
 '2023-06-04',
 '2023-06-05',
 '2023-06-06',
 '2023-06-07',
 '2023-06-08',
 '2023-06-09',
 '2023-06-10',
 '2023-06-11',
 '2023-06-12',
 '2023-06-13',
 '2023-06-14',
 '2023-06-15',
 '2023-06-16',
 '2023-06-17',
 '2023-06-18',
 '2023-06-19',
 '2023-06-20',
 '2023-06-21',
 '2023-06-22',
 '2023-06-23',
 '2023-06-24',
 '2023-06-25',
 '2023-06-26',
 '2023-06-27',
 '2023-06-28',
 '2023-06-29',
 '2023-06-30',
 '2023-07-01',
 '2023-07-02',
 '2023-07-03',
 '2023-07-04',
 '2023-07-05',
 '2023-07-06',
 '2023-07-07',
 '2023-07-08',
 '2023-07-09',
 '2023-07-10',
 '2023-07-11',
 '2023-07-12',
 '2023-07-13',
 '2023-07-14',
 '2023-07-15',
 '2023-07-16',
 '2023-07-17',
 '2023-07-18',
 '2023-07-19',
 '2023-07-20',
 '2023-07-21',
 '2023-07-22',
 '2023-07-23',
 '2023-07-24',
 '2023-07-25',
 '2023-07-26',
 '2023-07-27',
 '2023-07-28',
 '2023-07-29',
 '2023-07-30',
 '2023-07-31',
 '2023-08-01',
 '2023-08-02',
 '2023-08-03',
 '2023-08-04',
 '2023-08-05',
 '2023-08-06',
 '2023-08-07',
 '2023-08-08',
 '2023-08-09',
 '2023-08-10',
 '2023-08-11',
 '2023-08-12',
 '2023-08-13',
 '2023-08-14',
 '2023-08-15',
 '2023-08-16',
 '2023-08-17',
 '2023-08-18',
 '2023-08-19',
 '2023-08-20',
 '2023-08-21',
 '2023-08-22',
 '2023-08-23',
 '2023-08-24',
 '2023-08-25',
 '2023-08-26',
 '2023-08-27',
 '2023-08-28',
 '2023-08-29',
 '2023-08-30',
 '2023-08-31',
 '2023-09-01',
 '2023-09-02',
 '2023-09-03',
 '2023-09-04',
 '2023-09-05',
 '2023-09-06',
 '2023-09-07',
 '2023-09-08',
 '2023-09-09',
 '2023-09-10',
 '2023-09-11',
 '2023-09-12',
 '2023-09-13',
 '2023-09-14',
 '2023-09-15',
 '2023-09-16',
 '2023-09-17',
 '2023-09-18',
 '2023-09-19',
 '2023-09-20',
 '2023-09-21',
 '2023-09-22',
 '2023-09-23',
 '2023-09-24',
 '2023-09-25',
 '2023-09-26',
 '2023-09-27',
 '2023-09-28',
 '2023-09-29',
 '2023-09-30',
 '2023-10-01']

In [ ]:
# save as csv
"""
games_df.to_csv("games.csv", index=False, encoding="utf-8-sig")
lineup_df.to_csv("lineup.csv", index=False, encoding="utf-8-sig")
roster_df.to_csv("roster.csv", index=False, encoding="utf-8-sig")
season_hit_df.to_csv("player_season_hitter.csv", index=False, encoding="utf-8-sig")
season_pit_df.to_csv("player_season_pitcher.csv", index=False, encoding="utf-8-sig")
day_hit_df.to_csv("player_day_hitter.csv", index=False, encoding="utf-8-sig")
day_pit_df.to_csv("player_day_pitcher.csv", index=False, encoding="utf-8-sig")

"""

In [ ]:
def build_prediction_data_for_date(
    date_str,
    team_codes=None,
    roster_code="1",
    sleep_sec=0.2,
    verbose=True
):
    """
    특정 날짜(date_str)의 경기들을 불러와서
    모델 예측에 바로 사용할 수 있는 pred_df를 생성한다.

    Parameters
    ----------
    date_str : str
        예: "2026-04-05"

    team_codes : list[str], optional
        팀코드 리스트. None이면 KBO 10개 구단 기본값 사용.

    roster_code : str, default "1"
        playerRoster 호출용 code 파라미터

    sleep_sec : float, default 0.2
        반복 API 호출 간 텀

    verbose : bool, default True
        진행 로그 출력 여부

    Returns
    -------
    result : dict
        {
            "games_df": ...,
            "games_pred": ...,
            "lineup_df": ...,
            "roster_df": ...,
            "season_hit_df": ...,
            "season_pit_df": ...,
            "lineup_model": ...,
            "season_hit_model": ...,
            "season_pit_model": ...,
            "hitter_team_features": ...,
            "sp_features": ...,
            "pred_df": ...
        }
    """

    # --------------------------------------------------
    # 0) 기본 팀코드
    # --------------------------------------------------
    if team_codes is None:
        team_codes = ["1001", "2002", "3001", "5002", "6002", "7002", "9002", "10001", "11001", "12001"]
        # 삼성, KIA, 롯데, LG, 두산, 한화, SSG, 키움, NC, KT

    # --------------------------------------------------
    # 1) 해당 날짜 경기 수집
    # --------------------------------------------------
    if verbose:
        print("=== 1. collect_games ===")

    games_df = collect_games([date_str], sleep_sec=sleep_sec)

    if verbose:
        print(f"games_df.shape = {games_df.shape}")
        display(games_df.head())

    # --------------------------------------------------
    # 2) 예측 대상으로 사용할 경기 필터
    # --------------------------------------------------
    # 주의:
    # - 학습용 pipeline에서는 game_state == 3 & 점수 존재 조건을 썼음
    # - 만약 미래 경기 예측용이라면 점수 조건은 빼야 함, game_state != 4 활용
    # --------------------------------------------------
    if verbose:
        print("=== 2. filter target games ===")

    games_pred = games_df[
        (games_df["game_state"] != 4)
    ].copy()

    if verbose:
        print(f"games_pred.shape = {games_pred.shape}")
        display(games_pred.head())

    if games_pred.empty:
        raise ValueError("예측 대상으로 사용할 경기가 없습니다. game_state를 확인해봐.")

    # --------------------------------------------------
    # 3) 라인업 수집
    # --------------------------------------------------
    if verbose:
        print("=== 3. collect_lineups ===")

    lineup_df = collect_lineups(games_pred, sleep_sec=sleep_sec)

    if verbose:
        print(f"lineup_df.shape = {lineup_df.shape}")

    # --------------------------------------------------
    # 4) roster 수집
    # --------------------------------------------------
    if verbose:
        print("=== 4. collect_rosters ===")

    roster_df = collect_rosters(
        date=date_str,
        team_codes=team_codes,
        code=roster_code,
        sleep_sec=sleep_sec
    )

    if verbose:
        print(f"roster_df.shape = {roster_df.shape}")

    if roster_df.empty:
        raise ValueError("roster_df가 비어 있습니다. playerSeason 수집이 불가능합니다.")

    # --------------------------------------------------
    # 5) player ids 추출
    # --------------------------------------------------
    player_ids = roster_df["player_id"].astype(str).unique().tolist()

    if verbose:
        print(f"n_unique_player_ids = {len(player_ids)}")

    # --------------------------------------------------
    # 6) playerSeason 수집
    # --------------------------------------------------
    if verbose:
        print("=== 5. collect_player_season ===")

    season_hit_df, season_pit_df = collect_player_season(
        player_ids,
        snapshot_date=date_str,
        sleep_sec=sleep_sec
    )

    target_year = pd.to_datetime(date_str).year

    season_hit_df["year"] = pd.to_numeric(season_hit_df["year"], errors="coerce")
    season_pit_df["year"] = pd.to_numeric(season_pit_df["year"], errors="coerce")

    season_hit_df = season_hit_df[season_hit_df["year"] == target_year].copy()
    season_pit_df = season_pit_df[season_pit_df["year"] == target_year].copy()

    # --------------------------------------------------
    # 7) 시즌 중 팀 이동 선수 처리
    # - player_id + year 기준 1행
    # - team_code는 마지막 팀으로 통일
    # --------------------------------------------------
    if verbose:
        print("=== 6. deduplicate season stats ===")

    season_hit_df = deduplicate_hitter_season_last_team(season_hit_df)
    season_pit_df = deduplicate_pitcher_season_last_team(season_pit_df)

    if verbose:
        print(f"season_hit_df.shape = {season_hit_df.shape}")
        print(f"season_pit_df.shape = {season_pit_df.shape}")

    # --------------------------------------------------
    # 8) pitcher 특수값 처리
    # --------------------------------------------------
    if verbose:
        print("=== 7. clean pitcher season stats ===")

    pit_fill_cols = [c for c in ["ERA", "FIP", "WHIP", "KBB"] if c in season_pit_df.columns]
    if pit_fill_cols:
        season_pit_df[pit_fill_cols] = (
            season_pit_df[pit_fill_cols]
            .replace([np.inf, -np.inf], np.nan)
            .fillna(99.99)
        )

    # --------------------------------------------------
    # 9) 전처리
    # --------------------------------------------------
    if verbose:
        print("=== 8. prepare modeling tables ===")

    # 주의:
    # 여기서는 예측용이므로 prepare_games_for_modeling 대신
    # games_pred를 그대로 쓰되 season/home_win만 맞춰도 충분
    games_pred["game_id"] = games_pred["game_id"].astype(str)
    games_pred["home_team_code"] = games_pred["home_team_code"].astype(str)
    games_pred["away_team_code"] = games_pred["away_team_code"].astype(str)

    if "season" not in games_pred.columns:
        games_pred["season"] = pd.to_datetime(games_pred["game_date"]).dt.year

    lineup_model = prepare_lineup(lineup_df)
    season_hit_model = prepare_season_hitters(season_hit_df)
    season_pit_model = prepare_season_pitchers(season_pit_df)

    # lineup에 season 붙이기
    lineup_model = lineup_model.merge(
        games_pred[["game_id", "season"]],
        on="game_id",
        how="left"
    )

    # --------------------------------------------------
    # 10) 팀 타자 feature 생성
    # --------------------------------------------------
    if verbose:
        print("=== 9. build hitter team features ===")

    hitter_team_features = build_hitter_team_features(lineup_model, season_hit_model)

    if verbose:
        print(f"hitter_team_features.shape = {hitter_team_features.shape}")

    # --------------------------------------------------
    # 11) 선발투수 feature 생성
    # --------------------------------------------------
    if verbose:
        print("=== 10. build starting pitcher features ===")

    sp_features = build_starting_pitcher_features(lineup_model, season_pit_model)

    if verbose:
        print(f"sp_features.shape = {sp_features.shape}")

    # --------------------------------------------------
    # 12) 최종 경기 단위 예측 데이터 생성
    # --------------------------------------------------
    if verbose:
        print("=== 11. make prediction dataframe ===")

    pred_df = make_game_level_dataset(
        games_df_clean=games_pred,
        hitter_team_features=hitter_team_features,
        sp_features=sp_features
    )

    if verbose:
        print(f"pred_df.shape = {pred_df.shape}")
        display(pred_df.head())

    return {
        "games_df": games_df,
        "games_pred": games_pred,
        "lineup_df": lineup_df,
        "roster_df": roster_df,
        "season_hit_df": season_hit_df,
        "season_pit_df": season_pit_df,
        "lineup_model": lineup_model,
        "season_hit_model": season_hit_model,
        "season_pit_model": season_pit_model,
        "hitter_team_features": hitter_team_features,
        "sp_features": sp_features,
        "pred_df": pred_df,
    }

In [ ]:
import joblib
feature_cols = joblib.load("feature_cols.pkl")

In [ ]:
# 예측용 데이터 생성
pred_result = build_prediction_data_for_date(
    date_str="2026-04-05",
    sleep_sec=0.2,
    verbose=True
)

pred_df = pred_result["pred_df"]

# 모델에 실제로 넣을 feature matrix
X_pred = pred_df[feature_cols].copy()

display(X_pred.head())
print(X_pred.shape)

=== 1. collect_games ===
[games] 2026-04-05: 5 rows
games_df.shape = (5, 21)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20260036,2026-04-05 05:00:00,2026,6002,7002,1001,16299,16107,잭로그,황준서,...,0,1,3,14:00:00,10200,13.0,47,21300,2.1,None
1,20260037,2026-04-05 05:00:00,2026,10001,5002,1003,16452,16404,와일스,톨허스트,...,6,0,3,14:00:00,10100,12.9,50,21300,1.5,None
2,20260038,2026-04-05 05:00:00,2026,12001,1001,2002,16448,13574,보쉴리,오러클린,...,0,1,3,14:00:00,10100,13.2,52,21100,1.6,None
3,20260039,2026-04-05 05:00:00,2026,2002,11001,6001,16261,16454,올러,토다,...,0,1,3,14:00:00,10100,16.7,37,21100,2.7,None
4,20260040,2026-04-05 05:00:00,2026,3001,9002,8001,11310,16446,박세웅,베니지아노,...,4,0,3,14:00:00,10100,17.2,59,20900,3.2,None

=== 2. filter target games ===
games_pred.shape = (5, 21)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20260036,2026-04-05 05:00:00,2026,6002,7002,1001,16299,16107,잭로그,황준서,...,0,1,3,14:00:00,10200,13.0,47,21300,2.1,None
1,20260037,2026-04-05 05:00:00,2026,10001,5002,1003,16452,16404,와일스,톨허스트,...,6,0,3,14:00:00,10100,12.9,50,21300,1.5,None
2,20260038,2026-04-05 05:00:00,2026,12001,1001,2002,16448,13574,보쉴리,오러클린,...,0,1,3,14:00:00,10100,13.2,52,21100,1.6,None
3,20260039,2026-04-05 05:00:00,2026,2002,11001,6001,16261,16454,올러,토다,...,0,1,3,14:00:00,10100,16.7,37,21100,2.7,None
4,20260040,2026-04-05 05:00:00,2026,3001,9002,8001,11310,16446,박세웅,베니지아노,...,4,0,3,14:00:00,10100,17.2,59,20900,3.2,None

=== 3. collect_lineups ===
[lineup] 20260036: 20 rows
[lineup] 20260037: 20 rows
[lineup] 20260038: 20 rows
[lineup] 20260039: 20 rows
[lineup] 20260040: 20 rows
lineup_df.shape = (100, 13)
=== 4. collect_rosters ===
[roster] 2026-04-05 team=1001: 29 rows
[roster] 2026-04-05 team=2002: 29 rows
[roster] 2026-04-05 team=3001: 29 rows
[roster] 2026-04-05 team=5002: 29 rows
[roster] 2026-04-05 team=6002: 29 rows
[roster] 2026-04-05 team=7002: 29 rows
[roster] 2026-04-05 team=9002: 29 rows
[roster] 2026-04-05 team=10001: 29 rows
[roster] 2026-04-05 team=11001: 29 rows
[roster] 2026-04-05 team=12001: 29 rows
roster_df.shape = (290, 5)
n_unique_player_ids = 290
=== 5. collect_player_season ===
[playerSeason] 10892: OK
[playerSeason] 10363: OK
[playerSeason] 10640: OK
[playerSeason] 10527: OK
[playerSeason] 10232: OK
[playerSeason] 14116: OK
[playerSeason] 14618: OK
[playerSeason] 12936: OK
[playerSeason] 14798: OK
[playerSeason] 15034: OK
[playerSeason] 15035: OK
[playerSeason] 12934: OK
[playerSeason] 10894: OK
[playerSeason] 11422: OK
[playerSeason] 11489: OK
[playerSeason] 14616: OK
[playerSeason] 16162: OK
[playerSeason] 11379: OK
[playerSeason] 13157: OK
[playerSeason] 14121: OK
[playerSeason] 15531: OK
[playerSeason] 16239: OK
[playerSeason] 16242: OK
[playerSeason] 10891: OK
[playerSeason] 10909: OK
[playerSeason] 10344: OK
[playerSeason] 16412: OK
[playerSeason] 16423: OK
[playerSeason] 13574: OK
[playerSeason] 10058: OK
[playerSeason] 10008: OK
[playerSeason] 12537: OK
[playerSeason] 11298: OK
[playerSeason] 12540: OK
[playerSeason] 14608: OK
[playerSeason] 14788: OK
[playerSeason] 12869: OK
[playerSeason] 10659: OK
[playerSeason] 15056: OK
[playerSeason] 15057: OK
[playerSeason] 15063: OK
[playerSeason] 11162: OK
[playerSeason] 13113: OK
[playerSeason] 10459: OK
[playerSeason] 16085: OK
[playerSeason] 16088: OK
[playerSeason] 15125: OK
[playerSeason] 11126: OK
[playerSeason] 16250: OK
[playerSeason] 16252: OK
[playerSeason] 16261: OK
[playerSeason] 14764: OK
[playerSeason] 16344: OK
[playerSeason] 16289: OK
[playerSeason] 10609: OK
[playerSeason] 11411: OK
[playerSeason] 16425: OK
[playerSeason] 13592: OK
[playerSeason] 10266: OK
[playerSeason] 11310: OK
[playerSeason] 10825: OK
[playerSeason] 12928: OK
[playerSeason] 12930: OK
[playerSeason] 13155: OK
[playerSeason] 14624: OK
[playerSeason] 14642: OK
[playerSeason] 14792: OK
[playerSeason] 10804: OK
[playerSeason] 15048: OK
[playerSeason] 10753: OK
[playerSeason] 11165: OK
[playerSeason] 14796: OK
[playerSeason] 10238: OK
[playerSeason] 16090: OK
[playerSeason] 16091: OK
[playerSeason] 16106: OK
[playerSeason] 14590: OK
[playerSeason] 13071: OK
[playerSeason] 13073: OK
[playerSeason] 15051: OK
[playerSeason] 12530: OK
[playerSeason] 13145: OK
[playerSeason] 16429: OK
[playerSeason] 16433: OK
[playerSeason] 16434: OK
[playerSeason] 16443: OK
[playerSeason] 16455: OK
[playerSeason] 10475: OK
[playerSeason] 10749: OK
[playerSeason] 10652: OK
[playerSeason] 12697: OK
[playerSeason] 13009: OK
[playerSeason] 13056: OK
[playerSeason] 12546: OK
[playerSeason] 14137: OK
[playerSeason] 14669: OK
[playerSeason] 13112: OK
[playerSeason] 11094: OK
[playerSeason] 11190: OK
[playerSeason] 11166: OK
[playerSeason] 15532: OK
[playerSeason] 10387: OK
[playerSeason] 15084: OK
[playerSeason] 14140: OK
[playerSeason] 14816: OK
[playerSeason] 14783: OK
[playerSeason] 15081: OK
[playerSeason] 11164: OK
[playerSeason] 14846: OK
[playerSeason] 16274: OK
[playerSeason] 16286: OK
[playerSeason] 14134: OK
[playerSeason] 14606: OK
[playerSeason] 16404: OK
[playerSeason] 13104: OK
[playerSeason] 16398: OK
[playerSeason] 11098: OK
[playerSeason] 12850: OK
[playerSeason] 13061: OK
[playerSeason] 10195: OK
[playerSeason] 12524: OK
[playerSeason] 11087: OK
[playerSeason] 14770: OK
[playerSeason] 11213: OK
[playerSeason] 11300: OK
[playerSeason] 13070: OK
[playerSeason] 15099: OK
[playerSeason] 12894: OK
[playerSeason] 10165: OK
[playerSeason] 13124: OK
[playerSeason] 14736: OK
[playerSeason] 14737: OK
[playerSeason] 16067: OK
[playerSeason] 15104: OK
[playerSeason] 15253: OK
[playerSeason] 16287: OK
[playerSeason] 16288: OK
[playerSeason] 16293: OK
[playerSeason] 16299: OK
[playerSeason] 14771: OK
[playerSeason] 10217: OK
[playerSeason] 11261: OK
[playerSeason] 15512: OK
[playerSeason] 16426: OK
[playerSeason] 16457: OK
[playerSeason] 11117: OK
[playerSeason] 10913: OK
[playerSeason] 10170: OK
[playerSeason] 14125: OK
[playerSeason] 14710: OK
[playerSeason] 11414: OK
[playerSeason] 12585: OK
[playerSeason] 15013: OK
[playerSeason] 15014: OK
[playerSeason] 12871: OK
[playerSeason] 11215: OK
[playerSeason] 15421: OK
[playerSeason] 15422: OK
[playerSeason] 14707: OK
[playerSeason] 16107: OK
[playerSeason] 16108: OK
[playerSeason] 16110: OK
[playerSeason] 16118: OK
[playerSeason] 10590: OK
[playerSeason] 15015: OK
[playerSeason] 11334: OK
[playerSeason] 16301: OK
[playerSeason] 14196: OK
[playerSeason] 13168: OK
[playerSeason] 16121: OK
[playerSeason] 16415: OK
[playerSeason] 16421: OK
[playerSeason] 16424: OK
[playerSeason] 16458: OK
[playerSeason] 10106: OK
[playerSeason] 10815: OK
[playerSeason] 10783: OK
[playerSeason] 12613: OK
[playerSeason] 12922: OK
[playerSeason] 13126: OK
[playerSeason] 14587: OK
[playerSeason] 14687: OK
[playerSeason] 10249: OK
[playerSeason] 14806: OK
[playerSeason] 14807: OK
[playerSeason] 13228: OK
[playerSeason] 10203: OK
[playerSeason] 15461: OK
[playerSeason] 15467: OK
[playerSeason] 15530: OK
[playerSeason] 14145: OK
[playerSeason] 14153: OK
[playerSeason] 10312: OK
[playerSeason] 14805: OK
[playerSeason] 16042: OK
[playerSeason] 14803: OK
[playerSeason] 13167: OK
[playerSeason] 15032: OK
[playerSeason] 16324: OK
[playerSeason] 11153: OK
[playerSeason] 10643: OK
[playerSeason] 16446: OK
[playerSeason] 16456: OK
[playerSeason] 11222: OK
[playerSeason] 11225: OK
[playerSeason] 14580: OK
[playerSeason] 10870: OK
[playerSeason] 11244: OK
[playerSeason] 15472: OK
[playerSeason] 12516: OK
[playerSeason] 14591: OK
[playerSeason] 10182: OK
[playerSeason] 12860: OK
[playerSeason] 16122: OK
[playerSeason] 10557: OK
[playerSeason] 16328: OK
[playerSeason] 16330: OK
[playerSeason] 16335: OK
[playerSeason] 16384: OK
[playerSeason] 13941: OK
[playerSeason] 11425: OK
[playerSeason] 14809: OK
[playerSeason] 10014: OK
[playerSeason] 14849: OK
[playerSeason] 12858: OK
[playerSeason] 15068: OK
[playerSeason] 16407: OK
[playerSeason] 16410: OK
[playerSeason] 16441: OK
[playerSeason] 16451: OK
[playerSeason] 16452: OK
[playerSeason] 16453: OK
[playerSeason] 11137: OK
[playerSeason] 13081: OK
[playerSeason] 13085: OK
[playerSeason] 13088: OK
[playerSeason] 12897: OK
[playerSeason] 14716: OK
[playerSeason] 11355: OK
[playerSeason] 14765: OK
[playerSeason] 14220: OK
[playerSeason] 10189: OK
[playerSeason] 15111: OK
[playerSeason] 13261: OK
[playerSeason] 15450: OK
[playerSeason] 15453: OK
[playerSeason] 11248: OK
[playerSeason] 13250: OK
[playerSeason] 14221: OK
[playerSeason] 16059: OK
[playerSeason] 16066: OK
[playerSeason] 14785: OK
[playerSeason] 14829: OK
[playerSeason] 11353: OK
[playerSeason] 11099: OK
[playerSeason] 15115: OK
[playerSeason] 16442: OK
[playerSeason] 16450: OK
[playerSeason] 16454: OK
[playerSeason] 16480: OK
[playerSeason] 16630: OK
[playerSeason] 11317: OK
[playerSeason] 11323: OK
[playerSeason] 10235: OK
[playerSeason] 11212: OK
[playerSeason] 14106: OK
[playerSeason] 14600: OK
[playerSeason] 11308: OK
[playerSeason] 11397: OK
[playerSeason] 15089: OK
[playerSeason] 10320: OK
[playerSeason] 14108: OK
[playerSeason] 14191: OK
[playerSeason] 10523: OK
[playerSeason] 16035: OK
[playerSeason] 15092: OK
[playerSeason] 14777: OK
[playerSeason] 14581: OK
[playerSeason] 12583: OK
[playerSeason] 12916: OK
[playerSeason] 10812: OK
[playerSeason] 10187: OK
[playerSeason] 12534: OK
[playerSeason] 11119: OK
[playerSeason] 15523: OK
[playerSeason] 16437: OK
[playerSeason] 16447: OK
[playerSeason] 16448: OK
[playerSeason] 16449: OK
[playerSeason] 16568: OK
=== 6. deduplicate season stats ===
season_hit_df.shape = (145, 15)
season_pit_df.shape = (138, 13)
=== 7. clean pitcher season stats ===
=== 8. prepare modeling tables ===
=== 9. build hitter team features ===
hitter_team_features.shape = (10, 9)
=== 10. build starting pitcher features ===
sp_features.shape = (10, 13)
=== 11. make prediction dataframe ===
pred_df.shape = (5, 70)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20260036,2026-04-05 05:00:00,2026,6002,7002,1001,16299,16107,잭로그,황준서,...,-0.072501,-0.034328,-2.77,2.10000,-0.30,-6.923,-2.077,0.692,0.1667,1
1,20260037,2026-04-05 05:00:00,2026,10001,5002,1003,16452,16404,와일스,톨허스트,...,-0.104238,-0.042049,-3.09,-0.82424,-0.01,-4.636,-1.364,-1.182,0.5000,0
2,20260038,2026-04-05 05:00:00,2026,12001,1001,2002,16448,13574,보쉴리,오러클린,...,0.237371,0.078335,-5.59,-0.13699,-0.28,-0.084,-0.451,0.000,0.2500,1
3,20260039,2026-04-05 05:00:00,2026,2002,11001,6001,16261,16454,올러,토다,...,-0.167259,-0.064485,-3.27,-1.38322,-0.73,0.629,-3.399,0.000,6.8000,1
4,20260040,2026-04-05 05:00:00,2026,3001,9002,8001,11310,16446,박세웅,베니지아노,...,-0.075523,-0.075791,-1.65,0.35291,-0.15,-0.697,0.987,-0.871,-0.8333,0

,lineup_OPS_diff,lineup_OBP_diff,lineup_SLG_diff,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff
0,-0.156134,-0.075005,-0.081128,-0.072501,-0.034328,-2.77,2.10000,-0.30,-6.923,-2.077,0.692,0.1667
1,-0.041897,-0.025866,-0.016031,-0.104238,-0.042049,-3.09,-0.82424,-0.01,-4.636,-1.364,-1.182,0.5000
2,0.133775,0.065463,0.068312,0.237371,0.078335,-5.59,-0.13699,-0.28,-0.084,-0.451,0.000,0.2500
3,-0.096762,-0.049168,-0.047594,-0.167259,-0.064485,-3.27,-1.38322,-0.73,0.629,-3.399,0.000,6.8000
4,-0.130325,-0.083252,-0.047073,-0.075523,-0.075791,-1.65,0.35291,-0.15,-0.697,0.987,-0.871,-0.8333

(5, 12)

In [ ]:
pred_df.to_csv("x_pred.csv", index=False, encoding="utf-8-sig")

In [ ]:
pred_df

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,top5_OPS_diff,top5_OBP_diff,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,y_home_win
0,20260036,2026-04-05 05:00:00,2026,6002,7002,1001,16299,16107,잭로그,황준서,...,-0.072501,-0.034328,-2.77,2.10000,-0.30,-6.923,-2.077,0.692,0.1667,1
1,20260037,2026-04-05 05:00:00,2026,10001,5002,1003,16452,16404,와일스,톨허스트,...,-0.104238,-0.042049,-3.09,-0.82424,-0.01,-4.636,-1.364,-1.182,0.5000,0
2,20260038,2026-04-05 05:00:00,2026,12001,1001,2002,16448,13574,보쉴리,오러클린,...,0.237371,0.078335,-5.59,-0.13699,-0.28,-0.084,-0.451,0.000,0.2500,1
3,20260039,2026-04-05 05:00:00,2026,2002,11001,6001,16261,16454,올러,토다,...,-0.167259,-0.064485,-3.27,-1.38322,-0.73,0.629,-3.399,0.000,6.8000,1
4,20260040,2026-04-05 05:00:00,2026,3001,9002,8001,11310,16446,박세웅,베니지아노,...,-0.075523,-0.075791,-1.65,0.35291,-0.15,-0.697,0.987,-0.871,-0.8333,0

### 예측 데이터 셋 형성

In [ ]:
def build_prediction_data_for_date(
    date_str,
    team_codes=None,
    roster_code="1",
    sleep_sec=0.2,
    verbose=True
):
    """
    특정 날짜(date_str)의 경기들을 불러와서
    모델 예측에 바로 사용할 수 있는 pred_df를 생성한다.

    Parameters
    ----------
    date_str : str
        예: "2026-04-05"

    team_codes : list[str], optional
        팀코드 리스트. None이면 KBO 10개 구단 기본값 사용.

    roster_code : str, default "1"
        playerRoster 호출용 code 파라미터

    sleep_sec : float, default 0.2
        반복 API 호출 간 텀

    verbose : bool, default True
        진행 로그 출력 여부

    Returns
    -------
    result : dict
        {
            "games_df": ...,
            "games_pred": ...,
            "lineup_df": ...,
            "roster_df": ...,
            "season_hit_df": ...,
            "season_pit_df": ...,
            "lineup_model": ...,
            "season_hit_model": ...,
            "season_pit_model": ...,
            "hitter_team_features": ...,
            "sp_features": ...,
            "pred_df": ...
        }
    """

    # --------------------------------------------------
    # 0) 기본 팀코드
    # --------------------------------------------------
    if team_codes is None:
        team_codes = ["1001", "2002", "3001", "5002", "6002", "7002", "9002", "10001", "11001", "12001"]
        # 삼성, KIA, 롯데, LG, 두산, 한화, SSG, 키움, NC, KT

    # --------------------------------------------------
    # 1) 해당 날짜 경기 수집
    # --------------------------------------------------
    if verbose:
        print("=== 1. collect_games ===")

    games_df = ut.collect_games([date_str], sleep_sec=sleep_sec)

    if verbose:
        print(f"games_df.shape = {games_df.shape}")
        display(games_df.head())

    # --------------------------------------------------
    # 2) 예측 대상으로 사용할 경기 필터
    # --------------------------------------------------
    # 주의:
    # - 학습용 pipeline에서는 game_state == 3 & 점수 존재 조건을 썼음
    # - 여기서는 "어제 완료된 경기"라서 동일하게 써도 됨
    # - 만약 미래 경기 예측용이라면 점수 조건은 빼야 함. game_state != 4 활용
    # --------------------------------------------------
    if verbose:
        print("=== 2. filter target games ===")

    games_pred = games_df[
        (games_df["game_state"] != 4)
    ].copy()

    if verbose:
        print(f"games_pred.shape = {games_pred.shape}")
        display(games_pred.head())

    if games_pred.empty:
        raise ValueError("예측 대상으로 사용할 경기가 없습니다. game_state를 확인해봐.")

    # --------------------------------------------------
    # 3) 라인업 수집
    # --------------------------------------------------
    if verbose:
        print("=== 3. collect_lineups ===")

    lineup_df = ut.collect_lineups(games_pred, sleep_sec=sleep_sec)

    if verbose:
        print(f"lineup_df.shape = {lineup_df.shape}")

    # --------------------------------------------------
    # 4) roster 수집
    # --------------------------------------------------
    if verbose:
        print("=== 4. collect_rosters ===")

    roster_df = ut.collect_rosters(
        date=date_str,
        team_codes=team_codes,
        code=roster_code,
        sleep_sec=sleep_sec
    )

    if verbose:
        print(f"roster_df.shape = {roster_df.shape}")

    if roster_df.empty:
        raise ValueError("roster_df가 비어 있습니다. playerSeason 수집이 불가능합니다.")

    # --------------------------------------------------
    # 5) player ids 추출
    # --------------------------------------------------
    player_ids = roster_df["player_id"].astype(str).unique().tolist()

    if verbose:
        print(f"n_unique_player_ids = {len(player_ids)}")

    # --------------------------------------------------
    # 6) playerSeason 수집
    # --------------------------------------------------
    if verbose:
        print("=== 5. collect_player_season ===")

    season_hit_df, season_pit_df = ut.collect_player_season(
        player_ids,
        snapshot_date=date_str,
        sleep_sec=sleep_sec
    )

    target_year = pd.to_datetime(date_str).year

    season_hit_df["year"] = pd.to_numeric(season_hit_df["year"], errors="coerce")
    season_pit_df["year"] = pd.to_numeric(season_pit_df["year"], errors="coerce")

    season_hit_df = season_hit_df[season_hit_df["year"] == target_year].copy()
    season_pit_df = season_pit_df[season_pit_df["year"] == target_year].copy()

    # --------------------------------------------------
    # 7) 시즌 중 팀 이동 선수 처리
    # - player_id + year 기준 1행
    # - team_code는 마지막 팀으로 통일
    # --------------------------------------------------
    if verbose:
        print("=== 6. deduplicate season stats ===")

    season_hit_df = ut.deduplicate_hitter_season_last_team(season_hit_df)
    season_pit_df = ut.deduplicate_pitcher_season_last_team(season_pit_df)

    if verbose:
        print(f"season_hit_df.shape = {season_hit_df.shape}")
        print(f"season_pit_df.shape = {season_pit_df.shape}")

    # --------------------------------------------------
    # 8) pitcher 특수값 처리
    # --------------------------------------------------
    if verbose:
        print("=== 7. clean pitcher season stats ===")

    pit_fill_cols = [c for c in ["ERA", "FIP", "WHIP", "KBB"] if c in season_pit_df.columns]
    if pit_fill_cols:
        season_pit_df[pit_fill_cols] = (
            season_pit_df[pit_fill_cols]
            .replace([np.inf, -np.inf], np.nan)
            .fillna(99.99)
        )

    # --------------------------------------------------
    # 9) 전처리
    # --------------------------------------------------
    if verbose:
        print("=== 8. prepare modeling tables ===")

    # 주의:
    # 여기서는 예측용이므로 prepare_games_for_modeling 대신
    # games_pred를 그대로 쓰되 season/home_win만 맞춰도 충분
    games_pred["game_id"] = games_pred["game_id"].astype(str)
    games_pred["home_team_code"] = games_pred["home_team_code"].astype(str)
    games_pred["away_team_code"] = games_pred["away_team_code"].astype(str)

    if "season" not in games_pred.columns:
        games_pred["season"] = pd.to_datetime(games_pred["game_date"]).dt.year

    lineup_model = ut.prepare_lineup(lineup_df)
    season_hit_model = ut.prepare_season_hitters(season_hit_df)
    season_pit_model = ut.prepare_season_pitchers(season_pit_df)

    # lineup에 season 붙이기
    lineup_model = lineup_model.merge(
        games_pred[["game_id", "season"]],
        on="game_id",
        how="left"
    )

    # --------------------------------------------------
    # 10) 팀 타자 feature 생성
    # --------------------------------------------------
    if verbose:
        print("=== 9. build hitter team features ===")

    hitter_team_features = ut.build_hitter_team_features(lineup_model, season_hit_model)

    if verbose:
        print(f"hitter_team_features.shape = {hitter_team_features.shape}")

    # --------------------------------------------------
    # 11) 선발투수 feature 생성
    # --------------------------------------------------
    if verbose:
        print("=== 10. build starting pitcher features ===")

    sp_features = ut.build_starting_pitcher_features(lineup_model, season_pit_model)

    if verbose:
        print(f"sp_features.shape = {sp_features.shape}")

    # --------------------------------------------------
    # 12) 최종 경기 단위 예측 데이터 생성
    # --------------------------------------------------
    if verbose:
        print("=== 11. make prediction dataframe ===")

    pred_df = ut.make_game_level_dataset(
        games_df_clean=games_pred,
        hitter_team_features=hitter_team_features,
        sp_features=sp_features
    )

    if verbose:
        print(f"pred_df.shape = {pred_df.shape}")
        display(pred_df.head())

    return {
        "games_df": games_df,
        "games_pred": games_pred,
        "lineup_df": lineup_df,
        "roster_df": roster_df,
        "season_hit_df": season_hit_df,
        "season_pit_df": season_pit_df,
        "lineup_model": lineup_model,
        "season_hit_model": season_hit_model,
        "season_pit_model": season_pit_model,
        "hitter_team_features": hitter_team_features,
        "sp_features": sp_features,
        "pred_df": pred_df,
    }

In [ ]:
import pandas as pd
import numpy as np

def build_season_pit_df_from_model_dfs(df_dict: dict[int, pd.DataFrame]) -> pd.DataFrame:
    """
    model_df_2023/2024/2025 같은 경기 단위 데이터에서
    시즌별 선발투수 요약 테이블(season_pit_df) 생성

    Parameters
    ----------
    df_dict : dict[int, pd.DataFrame]
        예: {2023: model_df_2023, 2024: model_df_2024, 2025: model_df_2025}

    Returns
    -------
    pd.DataFrame
        columns:
        ['year', 'player_id', 'player_name', 'ERA', 'FIP', 'WHIP',
         'K9', 'BB9', 'HR9', 'KBB', 'QS', 'GS']
    """

    all_pitchers = []

    for year, df in df_dict.items():
        tmp = df.copy()

        # home
        home_cols = [
            "home_sp_player_id", "home_sp_player_name",
            "home_sp_ERA", "home_sp_FIP", "home_sp_WHIP",
            "home_sp_K9", "home_sp_BB9", "home_sp_HR9", "home_sp_KBB",
            "home_sp_QS", "home_sp_GS"
        ]
        home = tmp[home_cols].copy()
        home.columns = [
            "player_id", "player_name",
            "ERA", "FIP", "WHIP",
            "K9", "BB9", "HR9", "KBB",
            "QS", "GS"
        ]
        home["year"] = year

        # away
        away_cols = [
            "away_sp_player_id", "away_sp_player_name",
            "away_sp_ERA", "away_sp_FIP", "away_sp_WHIP",
            "away_sp_K9", "away_sp_BB9", "away_sp_HR9", "away_sp_KBB",
            "away_sp_QS", "away_sp_GS"
        ]
        away = tmp[away_cols].copy()
        away.columns = [
            "player_id", "player_name",
            "ERA", "FIP", "WHIP",
            "K9", "BB9", "HR9", "KBB",
            "QS", "GS"
        ]
        away["year"] = year

        season_pitchers = pd.concat([home, away], ignore_index=True)

        # 타입 정리
        season_pitchers["year"] = pd.to_numeric(season_pitchers["year"], errors="coerce")
        season_pitchers["player_id"] = season_pitchers["player_id"].astype(str)

        num_cols = ["ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB", "QS", "GS"]
        for c in num_cols:
            season_pitchers[c] = pd.to_numeric(season_pitchers[c], errors="coerce")

        # player_id 없는 행 제거
        season_pitchers = season_pitchers[
            season_pitchers["player_id"].notna() &
            (season_pitchers["player_id"] != "nan")
        ].copy()

        # 같은 시즌, 같은 투수가 여러 경기에서 반복되므로 1행만 남김
        # 혹시 값이 조금이라도 다르면 GS 큰 값 기준 마지막 기록 사용
        season_pitchers = (
            season_pitchers
            .sort_values(["year", "player_id", "GS"])
            .drop_duplicates(subset=["year", "player_id"], keep="last")
        )

        all_pitchers.append(season_pitchers)

    season_pit_df = pd.concat(all_pitchers, ignore_index=True)

    # 보기 좋게 정렬
    season_pit_df = season_pit_df.sort_values(["year", "player_id"]).reset_index(drop=True)

    return season_pit_df

In [ ]:
model_df_2023 = pd.read_csv("model_df_2023.csv")
model_df_2024 = pd.read_csv("model_df_2024.csv")
model_df_2025 = pd.read_csv("model_df_2025.csv")

season_pit_df = build_season_pit_df_from_model_dfs({
    2023: model_df_2023,
    2024: model_df_2024,
    2025: model_df_2025
})

display(season_pit_df.head())
print(season_pit_df.shape)
print(season_pit_df["year"].value_counts().sort_index())

In [ ]:
season_pit_df.to_csv('seaon_pit_df.csv', index=False)

In [1]:
import pandas as pd

def extract_unique_sp(df: pd.DataFrame) -> pd.DataFrame:
    """
    선발투수 ID + 이름 unique하게 추출

    Parameters
    ----------
    df : model_df 형태의 DataFrame

    Returns
    -------
    sp_df : DataFrame (columns: sp_name, sp_id)
    """

    # 홈/원정 각각 추출
    home_sp = df[["home_sp_name", "home_sp_id"]].rename(
        columns={"home_sp_name": "sp_name", "home_sp_id": "sp_id"}
    )

    away_sp = df[["away_sp_name", "away_sp_id"]].rename(
        columns={"away_sp_name": "sp_name", "away_sp_id": "sp_id"}
    )

    # 합치기
    sp_df = pd.concat([home_sp, away_sp], axis=0)

    # 결측 제거
    sp_df = sp_df.dropna(subset=["sp_id"])

    # 중복 제거 (ID 기준)
    sp_df = sp_df.drop_duplicates(subset=["sp_id"])

    # 정렬 (선택)
    sp_df = sp_df.sort_values("sp_id").reset_index(drop=True)

    return sp_df

In [2]:
df_2023 = pd.read_csv("model_df_2023.csv")
df_2024 = pd.read_csv("model_df_2024.csv")
df_2025 = pd.read_csv("model_df_2025.csv")

df_all = pd.concat([df_2023, df_2024, df_2025], axis=0)

sp_df = extract_unique_sp(df_all)

print(sp_df.head())

  sp_name  sp_id
0     양현종  10058
1     김광현  10126
2     박종훈  10131
3     정우람  10156
4     이용찬  10217

In [4]:
sp_df.to_csv('sp_df.csv', index=False)

In [ ]:
sp_df = pd.read_csv("sp_df.csv")

In [9]:
def get_players_by_name(sp_df, names):
    """
    선수명 리스트를 입력하면 해당 행 반환

    Parameters
    ----------
    sp_df : DataFrame (columns: sp_name, sp_id)
    names : list[str] or str

    Returns
    -------
    DataFrame
    """

    # 문자열 하나 들어와도 처리 가능하게
    if isinstance(names, str):
        names = [names]

    result = sp_df[sp_df["sp_name"].isin(names)].copy()

    return result

In [ ]:
# 걍 id를 때려박을까 고민

def get_players_by_name_safe(sp_df, names): # 찾을 수 없는 선수는 NA로, 그리고 입력한 선수명의 순서대로 list로 출력. 수정해야함

    if isinstance(names, str):
        names = [names]

    result = sp_df[sp_df["sp_name"].isin(names)].copy()

    found_names = set(result["sp_name"])
    missing = list(set(names) - found_names)

    if missing:
        print(f"[경고] 다음 선수는 찾을 수 없음: {missing}")

    return result

In [25]:
names_away = ["알칸타라", "에르난데스", "후라도", "김광현", "치리노스"]
names_home = ["곽빈", "화이트", "네일", "류현진", "구창모"]

id_list_away = get_players_by_name_safe(sp_df, names_away)['sp_id'].tolist()
id_list_home = get_players_by_name_safe(sp_df, names_home)['sp_id'].tolist()

print(id_list_away)
print(id_list_home)

[10126, 13941, 15531, 16160, 16286]
[10590, 11353, 13061, 16088, 16324]

In [22]:
names = ['에르난데스', '화이트']
get_players_by_name_safe(sp_df, names)

    sp_name  sp_id
202   에르난데스  16160
215     화이트  16324

In [34]:
import pandas as pd
import numpy as np


def build_prediction_data_for_date_with_manual_sp(
    target_date,
    schedule_df: pd.DataFrame,
    season_pit_df: pd.DataFrame,
    manual_sp_df: pd.DataFrame,
    target_year: int,
    use_prev_year: bool = True,
    return_full: bool = True
) -> pd.DataFrame:
    """
    수동 입력한 선발투수 ID를 사용하여 pred_df 유사 형태의 예측용 데이터 생성.
    타격 라인업, 날씨 정보는 포함하지 않음.

    Parameters
    ----------
    target_date : str or datetime-like
        예측 대상 날짜
    schedule_df : pd.DataFrame
        경기 일정 데이터.
        최소 필요 정보:
        - game_id
        - game_date
        - home_team_code
        - away_team_code
        선택:
        - season
        - stadium_code
    season_pit_df : pd.DataFrame
        투수 시즌 성적 데이터.
        필요 컬럼(이름은 자동 탐색):
        - player_id / p_no / sp_id
        - player_name / name / p_name
        - year / season
        - ERA, FIP, WHIP, K9, BB9, HR9, KBB, QS, GS
    manual_sp_df : pd.DataFrame
        수동 선발투수 입력 데이터
        필수 컬럼:
        - game_id
        - home_sp_id
        - away_sp_id
    target_year : int
        예측 연도
    use_prev_year : bool, default True
        target_year 기록이 없으면 전년도 기록 fallback
    return_full : bool, default True
        True면 pred_df 유사 전체 컬럼 반환
        False면 최소 컬럼만 반환

    Returns
    -------
    pd.DataFrame
    """

    # -----------------------------
    # 0) 내부 유틸
    # -----------------------------
    def pick_col(candidates, cols, label):
        for c in candidates:
            if c in cols:
                return c
        raise ValueError(f"{label} 컬럼을 찾지 못함. 후보: {candidates}")

    def ensure_datetime_col(df, col):
        out = df.copy()
        out[col] = pd.to_datetime(out[col]).dt.date
        return out

    # -----------------------------
    # 1) manual_sp_df 검증
    # -----------------------------
    required_manual_cols = ["game_id", "home_sp_id", "away_sp_id"]
    missing_manual = [c for c in required_manual_cols if c not in manual_sp_df.columns]
    if missing_manual:
        raise ValueError(f"manual_sp_df에 필요한 컬럼이 없음: {missing_manual}")

    if manual_sp_df["game_id"].duplicated().any():
        dup_ids = manual_sp_df.loc[manual_sp_df["game_id"].duplicated(), "game_id"].tolist()
        raise ValueError(f"manual_sp_df에 중복 game_id가 있음: {dup_ids}")

    manual_sp_df = manual_sp_df.copy()

    # -----------------------------
    # 2) schedule_df 컬럼 탐색
    # -----------------------------
    sch = schedule_df.copy()

    game_id_col = pick_col(["game_id", "s_no"], sch.columns, "경기 ID")
    game_date_col = pick_col(["game_date", "date", "gday"], sch.columns, "경기 날짜")
    home_team_col = pick_col(["home_team_code", "home_t_code", "home_code"], sch.columns, "홈팀 코드")
    away_team_col = pick_col(["away_team_code", "away_t_code", "away_code"], sch.columns, "원정팀 코드")

    season_col = None
    for c in ["season", "year"]:
        if c in sch.columns:
            season_col = c
            break

    stadium_col = None
    for c in ["stadium_code", "stadium", "stadium_id"]:
        if c in sch.columns:
            stadium_col = c
            break

    # 날짜 필터
    sch = sch.rename(columns={
        game_id_col: "game_id",
        game_date_col: "game_date",
        home_team_col: "home_team_code",
        away_team_col: "away_team_code"
    })

    if season_col is not None:
        sch = sch.rename(columns={season_col: "season"})
    else:
        sch["season"] = target_year

    if stadium_col is not None:
        sch = sch.rename(columns={stadium_col: "stadium_code"})
    else:
        sch["stadium_code"] = np.nan

    sch = ensure_datetime_col(sch, "game_date")
    target_date = pd.to_datetime(target_date).date()

    sch = sch.loc[sch["game_date"] == target_date].copy()

    if len(sch) == 0:
        raise ValueError(f"{target_date}에 해당하는 경기 일정이 schedule_df에 없음")

    # -----------------------------
    # 3) 해당 날짜 일정 + manual starter merge
    # -----------------------------
    pred_df = sch.merge(
        manual_sp_df[["game_id", "home_sp_id", "away_sp_id"]],
        on="game_id",
        how="inner"
    ).copy()

    if len(pred_df) == 0:
        raise ValueError("해당 날짜 일정과 manual_sp_df가 매칭되는 game_id가 없음")

    # -----------------------------
    # 4) season_pit_df 컬럼 탐색 및 정리
    # -----------------------------
    pit = season_pit_df.copy()

    pit_id_col = pick_col(["player_id", "p_no", "sp_id"], pit.columns, "투수 ID")
    pit_name_col = pick_col(["player_name", "name", "p_name"], pit.columns, "투수명")
    pit_year_col = pick_col(["year", "season"], pit.columns, "연도")

    stat_cols = ["ERA", "FIP", "WHIP", "K9", "BB9", "HR9", "KBB", "QS", "GS"]
    missing_stats = [c for c in stat_cols if c not in pit.columns]
    if missing_stats:
        raise ValueError(f"season_pit_df에 필요한 지표 컬럼이 없음: {missing_stats}")

    pit = pit[[pit_id_col, pit_name_col, pit_year_col] + stat_cols].copy()

    for c in stat_cols:
        pit[c] = pd.to_numeric(pit[c], errors="coerce")

    # -----------------------------
    # 5) target_year / prev_year / 리그 평균 준비
    # -----------------------------
    pit_this = pit.loc[pit[pit_year_col] == target_year].copy()
    pit_prev = pit.loc[pit[pit_year_col] == (target_year - 1)].copy() if use_prev_year else pit.iloc[0:0].copy()

    if len(pit_prev) > 0:
        league_means = pit_prev[stat_cols].mean()
    elif len(pit_this) > 0:
        league_means = pit_this[stat_cols].mean()
    else:
        league_means = pit[stat_cols].mean()

    pit_this_map = pit_this.drop_duplicates(subset=[pit_id_col]).set_index(pit_id_col) if len(pit_this) > 0 else pd.DataFrame()
    pit_prev_map = pit_prev.drop_duplicates(subset=[pit_id_col]).set_index(pit_id_col) if len(pit_prev) > 0 else pd.DataFrame()

    def get_pitcher_row(pid):
        # 올해 기록 우선
        if len(pit_this_map) > 0 and pid in pit_this_map.index:
            row = pit_this_map.loc[pid]
            if isinstance(row, pd.DataFrame):
                row = row.iloc[0]
            return row.to_dict()

        # 전년도 fallback
        if len(pit_prev_map) > 0 and pid in pit_prev_map.index:
            row = pit_prev_map.loc[pid]
            if isinstance(row, pd.DataFrame):
                row = row.iloc[0]
            return row.to_dict()

        # 없으면 리그 평균
        return {
            pit_name_col: np.nan,
            **{c: league_means[c] for c in stat_cols}
        }

    # -----------------------------
    # 6) 홈/원정 선발 정보 생성
    # -----------------------------
    home_rows = pred_df["home_sp_id"].apply(get_pitcher_row)
    away_rows = pred_df["away_sp_id"].apply(get_pitcher_row)

    home_pitcher_df = pd.DataFrame(list(home_rows))
    away_pitcher_df = pd.DataFrame(list(away_rows))

    pred_df["home_sp_player_id"] = pred_df["home_sp_id"]
    pred_df["away_sp_player_id"] = pred_df["away_sp_id"]

    pred_df["home_sp_player_name"] = home_pitcher_df[pit_name_col]
    pred_df["away_sp_player_name"] = away_pitcher_df[pit_name_col]

    pred_df["home_sp_name"] = pred_df["home_sp_player_name"]
    pred_df["away_sp_name"] = pred_df["away_sp_player_name"]

    for c in stat_cols:
        pred_df[f"home_sp_{c}"] = home_pitcher_df[c]
        pred_df[f"away_sp_{c}"] = away_pitcher_df[c]

    # -----------------------------
    # 7) diff 계산
    # -----------------------------
    diff_map = {
        "ERA": "sp_ERA_diff",
        "FIP": "sp_FIP_diff",
        "WHIP": "sp_WHIP_diff",
        "K9": "sp_K9_diff",
        "BB9": "sp_BB9_diff",
        "HR9": "sp_HR9_diff",
        "KBB": "sp_KBB_diff"
    }

    for raw_col, diff_col in diff_map.items():
        pred_df[diff_col] = pred_df[f"home_sp_{raw_col}"] - pred_df[f"away_sp_{raw_col}"]

    # -----------------------------
    # 8) pred_df 유사 컬럼 구성
    #    (라인업/날씨 없음)
    # -----------------------------
    pred_df["home_score"] = np.nan
    pred_df["away_score"] = np.nan
    pred_df["home_win"] = np.nan
    pred_df["game_state"] = np.nan
    pred_df["game_time"] = np.nan

    full_cols = [
        "game_id", "game_date", "season",
        "home_team_code", "away_team_code", "stadium_code",
        "home_sp_id", "away_sp_id",
        "home_sp_name", "away_sp_name",
        "home_score", "away_score", "home_win",
        "game_state", "game_time",
        "home_sp_player_id", "home_sp_player_name",
        "home_sp_ERA", "home_sp_FIP", "home_sp_WHIP",
        "home_sp_K9", "home_sp_BB9", "home_sp_HR9",
        "home_sp_KBB", "home_sp_QS", "home_sp_GS",
        "away_sp_player_id", "away_sp_player_name",
        "away_sp_ERA", "away_sp_FIP", "away_sp_WHIP",
        "away_sp_K9", "away_sp_BB9", "away_sp_HR9",
        "away_sp_KBB", "away_sp_QS", "away_sp_GS",
        "sp_ERA_diff", "sp_FIP_diff", "sp_WHIP_diff",
        "sp_K9_diff", "sp_BB9_diff", "sp_HR9_diff", "sp_KBB_diff"
    ]

    minimal_cols = [
        "game_id", "game_date", "season",
        "home_team_code", "away_team_code", "stadium_code",
        "home_sp_id", "away_sp_id",
        "home_sp_name", "away_sp_name",
        "sp_ERA_diff", "sp_FIP_diff", "sp_WHIP_diff",
        "sp_K9_diff", "sp_BB9_diff", "sp_HR9_diff", "sp_KBB_diff"
    ]

    if return_full:
        pred_df = pred_df[[c for c in full_cols if c in pred_df.columns]].copy()
    else:
        pred_df = pred_df[[c for c in minimal_cols if c in pred_df.columns]].copy()

    return pred_df

In [47]:
import pandas as pd
import json
import urllib.request
import time
import utils as ut

import pandas as pd
import json
import urllib.request
import time

def get_schedule_df(date_str, API_KEY, SECRET):
    """
    date_str: 'YYYY-MM-DD'
    반환: 해당 날짜 경기 일정 DataFrame
    """

    METHOD = "GET"
    PATH = "prediction/gameSchedule"

    # API 구조상 date 전체를 넣기보다 year/month/day로 보내는 형태일 수도 있으니
    # 기존에 네 API 명세대로 맞춰 써도 되고,
    # 일단 현재는 date로 호출이 됐으니 그대로 유지
    QUERY = {
        "date": date_str
    }

    normalized = ut.normalize_query(QUERY)
    timestamp = str(int(time.time()))
    payload = f"{METHOD}|{PATH}|{normalized}|{timestamp}"
    signature = ut.make_signature(SECRET, payload)

    url = f"https://api.statiz.co.kr/baseballApi/{PATH}?{normalized}"

    headers = {
        "X-API-KEY": API_KEY,
        "X-TIMESTAMP": timestamp,
        "X-SIGNATURE": signature,
    }

    req = urllib.request.Request(url, method=METHOD, headers=headers)

    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    # 결과 체크
    if data.get("result_cd") not in [1, "1", 100, "100", None]:
        raise ValueError(f"API 오류: result_cd={data.get('result_cd')}, result_msg={data.get('result_msg')}")

    # '2026-04-09' -> '0409'
    date_key = pd.to_datetime(date_str).strftime("%m%d")

    if date_key not in data:
        raise KeyError(f"응답에 날짜 키 {date_key}가 없음. 사용 가능한 키: {list(data.keys())[:10]} ...")

    games = data[date_key]

    if not isinstance(games, list):
        raise ValueError(f"{date_key}의 값이 list가 아님: {type(games)}")

    df = pd.DataFrame(games)

    return df

In [52]:
# 1. schedule 가져오기
schedule_df = get_schedule_df("2026-04-11", API_KEY, SECRET)
print(schedule_df.head())

       s_no  state  leagueType  year  month  day halfYear  week        hm  \
0  20260064      1       10100  2026      4   11        F     6  14:00:00
1  20260061      1       10100  2026      4   11        F     6  17:00:00
2  20260062      1       10100  2026      4   11        F     6  17:00:00
3  20260063      1       10100  2026      4   11        F     6  17:00:00
4  20260065      1       10100  2026      4   11        F     6  17:00:00

     gameDate  ...  rainprobability  s_code  awayTeam  awaySP  homeTeam  \
0  1775883600  ...                0    4003      2002       0      7002
1  1775894400  ...                0    1001      9002       0      5002
2  1775894400  ...                0    1003      3001       0     10001
3  1775894400  ...                0    2002      6002       0     12001
4  1775894400  ...                0    7003     11001       0      1001

   homeSP  awaySPName  homeSPName  awayScore  homeScore
0       0        None        None       None       None
1       0        None        None       None       None
2       0        None        None       None       None
3       0        None        None       None       None
4       0        None        None       None       None

[5 rows x 26 columns]

In [54]:
manual_sp_df = pd.DataFrame({
    "game_id": [20260056, 20260057, 20260058, 20260059, 20260060],
    "home_sp_id": id_list_home,
    "away_sp_id": id_list_away,
})

season_pit_df = pd.read_csv('seaon_pit_df.csv')

pred_df_manual = build_prediction_data_for_date_with_manual_sp(
    target_date="2026-04-11",
    schedule_df=schedule_df,
    season_pit_df=season_pit_df,
    manual_sp_df=manual_sp_df,
    target_year=2026,
    use_prev_year=True,
    return_full=True
)

ValueError: 경기 날짜 컬럼을 찾지 못함. 후보: ['game_date', 'date', 'gday']